### ISSUE TITLE
Census site only allows one person at a time for an address

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#100]
Feedback:
_"went to fill out census information on line only allows 1 person to register per address !!!!
You have got to be kidding !! please hire someone who knows what they are doing ! Didn't anyone actually test this thing !

How important is this! Federal and state dollars are allocated by population by this snafu you probably eliminated 10% of the population."_

Constituent is referring to this form on the old site: https://www.cityofboston.gov/elections/arl/

**Comment by matthewcrist** [comment]
Closing as this work is being done in our forms.
