### ISSUE TITLE
search ux: remove the extra step 

### ISSUE THREAD

**Issue by BrutiAnteneh** [CityOfBoston/boston.gov#1007]
## The Problem

Users are primed (by Google/Bing/Yahoo) to start typing their search query after clicking the search spyglass. On boston.gov, however, we have an extra step: after clicking on the spyglass, _**users have to click inside the search box first for in order for the cursor to appear**_.

  ## <summary>Reproduced Below: </summary>

![ezgif com-resize](https://user-images.githubusercontent.com/33470951/36175565-ed2c243a-10dd-11e8-997e-bc582feb384b.gif)

**Comment by reillyzlab** [comment]
We should change this so that the cursor appears already in the search when the search is opened.

**Comment by reillyzlab** [comment]
@BrutiAnteneh to test

**Comment by BrutiAnteneh** [comment]
The issue passed as expected.
