### ISSUE TITLE
Drupal module to render the datasource / map web components based on JSON configuration.

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov#1014]
**Needed functionality:** Drupal needs to: 
* render vizwiz application inside the maps component editor 
* consume and store the JSON object rendered by vizwiz 
* pass the JSON object to the maps web component stored in the patterns library

**Comment by paylakatel** [comment]
@coordt do you mind adding a little more detail to this so Jim has a better idea what needs to happen from a technical stand point?

**Comment by finneganh** [comment]
Configuration side:
 - [ ] load the Vizwiz JS bundle and CSS into the editor page
 - [ ] component is configured with a `<textarea>` that Vizwiz binds to. This needs to be saved as the component’s configuration.

Display side:
 - [ ] load the web-components JS from https://patterns.boston.gov/web-components/all.js
 - [ ] Write a `<cob-vizwiz>` tag onto the page with the config JSON in an internal `<script>` tag. (See example: https://github.com/CityOfBoston/patterns/blob/ac30fbc577a38ee72a575739a04ac99571f83a64/web-components/html/index.html#L45 )

**Comment by finneganh** [comment]
Current issue is needing to pass the ID of Drupal's JSON storage field to the `<vizwiz>` component.
