### ISSUE TITLE
Boston.gov 500/404 February Report 

### ISSUE THREAD

**Issue by jfalvey** [CityOfBoston/boston.gov#1016]
[boston.gov-500 and 400 (1) (1).xlsx](https://github.com/CityOfBoston/boston.gov/files/1760024/boston.gov-500.and.400.1.1.xlsx)

This will be a monthly pull by Acquia to scan the site for page errors. Bruti will be on point for reviewing and adding other tickets as necessary to resolve with appropriate team members.

**Comment by BrutiAnteneh** [comment]
Opened the following ticket with Acquia 


## 500 Errors:
I’d like to see if dead links are causing our high-frequency 500 errors (see screenshot:[4/17/2018] Requesting URL for 500 errors). Would you be able to provide us with the page URLs for these links?

## 400 Errors:
**Robots.txt entries**
We have multiple robots.txt entries (see screenshot [4-17-2018] 400 errors - Filtered - robots.txt). Would these be resolved using the Fast 404 (fast_404) module, as suggested in this article:
[Serving alternate robots.txt files from a multisite](https://docs.acquia.com/article/serving-alternate-robotstxt-files-multisite)

**/apple-touch-icon entries**
Our highest frequency 400 errors come from iOS based favicons, or /apple-touch-icon (see screenshot 4/17/2018 - 400 Errors). For favicons, Acquia recommends installing Favicon module [Acquia Cloud Site Factory: Favicon Issues
](https://docs.acquia.com/article/acquia-cloud-site-factory-favicon-issues)
Would this resolve the issues we’re having with apple-touch-icons? 

Please let me know if you have any questions for me.  

-Bruti
