### ISSUE TITLE
SVG images look broken in Drupal

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#1018]
The SVG images uploaded to Drupal look broken when you try to find them later in the system:

![image](https://user-images.githubusercontent.com/7929556/36808432-0fd491c8-1c93-11e8-9114-456521ef6b37.png)

Users can't preview the images, and aren't sure what they are adding to the page. I've only noticed this issue with SVGs -- PNG and JPG files look fine.

**Comment by BrutiAnteneh** [comment]
For A/B testing: a small number of SVGs that do preview as thumbnails: 

<img width="1048" alt="screen shot 2018-03-22 at 8 00 36 pm" src="https://user-images.githubusercontent.com/33470951/37804714-06f15c5a-2e0c-11e8-93d1-7e58bf285227.png">

**Comment by BrutiAnteneh** [comment]
Bill Dennen (Acquia TAM Team) documented this issue in a TAM Team Support ticket when troubleshooting 500 error entries:

![4_17_2018 broken image links 500 errors](https://user-images.githubusercontent.com/33470951/40253598-5c946e80-5aae-11e8-9fed-e3fa9f7e278c.png)

I'm including that information below in case helpful for sleuthing.

## 500 Errors

Just about all of the 500 errors are related to images on the edit.boston.gov domain, so they're not visible to the public.  It looks like they occur when an editor edits a node on edit.boston.gov. it's important to note that the public does not see these errors.

Here's an example:
```
access.log:104.129.194.80 - - [02/May/2018:18:14:27 +0000] "GET /sites/default/files/styles/media_thumbnail/public/department_icons/icons_new_urban_mechanics.svg?itok=3SISRIRT HTTP/1.1" 500 23 "https://edit.boston.gov/node/96/edit" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36" vhost=boston.prod.acquia-sites.com host=edit.boston.gov hosting_site=boston pid=22261 request_time=156287 forwarded_for="104.129.194.80" request_id="v-a6bfbdc4-4e34-11e8-b288-22000b5d9b0e"
```
The actual error (from drupal-watchdog.log) is:

```
drupal-watchdog.log:May  2 18:14:27 web-15135 boston: https://edit.boston.gov|1525284867|image|104.129.194.80|https://edit.boston.gov/sites/default/files/styles/media_thumbnail/public/department_icons/icons_new_urban_mechanics.svg?itok=3SISRIRT|https://edit.boston.gov/node/96/edit|206||Unable to generate the derived image located at public://styles/media_thumbnail/public/department_icons/icons_new_urban_mechanics.svg. request_id="v-a6bfbdc4-4e34-11e8-b288-22000b5d9b0e"
```

**Note**: 
`Unable to generate the derived image located at public://styles/media_thumbnail/public/department_icons/icons_new_urban_mechanics.svg`


When you view the actual public page as an anonymous user -- ie. /node/96/, which translates to https://www.boston.gov/departments/new-urban-mechanics, you can see the image on that page (filename: icons_new_urban_mechanics.svg).

https://www.boston.gov/sites/default/files/department_icons/icons_new_urban_mechanics.svg

When I edit that node, I can see a broken image under "Alternative Display" -- see below:

![screen shot 2018-05-02 at 4 03 27 pm](https://user-images.githubusercontent.com/33470951/40253767-fc063250-5aae-11e8-9901-6453fbac6b7d.png)


I spot-checked a couple other Department Profile nodes and saw similar behavior. Is this something you have noticed, as well? There may be an issue with how this image is stored or the style is created.



**View original Acquia TAM Team support ticket:**
https://insight.acquia.com/support/requests/663402#comment-398620981174

**View the relevant server log:**
[boston-400-500-errors-20180417.csv.xlsx](https://github.com/CityOfBoston/boston.gov/files/2018261/boston-400-500-errors-20180417.csv.xlsx)

**Comment by kdonaldson** [comment]
The media broswer uses Media thumbnail (100x100) to style images. It's not possible to use SVGs with image styles, because the image style system only works with raster graphics. The core Image module is unaware of the distinction, and may attempt to process SVGs anyway, which can result in errors and other user-facing ugliness.  Previewing SVGs is not possible.  PNG should be used if a preview is necessary.
