### ISSUE TITLE
What to do with the bids content on the procurement site

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#102]
We need to move over the content here:

http://www.cityofboston.gov/purchasing/bid.asp

For right now, it makes sense to create a page with drawers for each bid or event. The current max for bids is 22 - 25 on the page. Suggestions for an ideal state:

We create a new type of content called "bids" and a new listing for a listing page called "bids - listing."
The list page would pull these "bids", and have all of the recently published bids on the page.
A user would have the ability to set an expire date on these individual bids, so that after two weeks, they disappear from the page and are unpublished on the site.

**Comment by hackajesse** [comment]
@jduffy2001 this is something you and Steve were working on. Can you post an update here w/progress? If it's stalled, ok, but just share what's happened.

**Comment by jduffy2001** [comment]
closing this. we're creating a new content type.
