### ISSUE TITLE
Can't edit/open items in Voting in Boston guide

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#1020]
The "quick links" transaction grid component on the [Voting in Boston page](https://www.boston.gov/voting-boston) won't let me edit existing content or new content. I tried recreating the whole transaction grid component, but I'm seeing the same message:

![image](https://user-images.githubusercontent.com/7929556/36909672-a941dfee-1e0c-11e8-9e7c-24759e668aff.png)

**Comment by jimafisk** [comment]
Talked with @jduffy2001 about this issue, it appears to be related to workbench moderation drafts: https://www.drupal.org/project/paragraphs/issues/2562875

A temp fix is to publish the node and then start a new draft. If it's something that keeps happening, please flag to me so I can address it. Thanks!

**Comment by jduffy2001** [comment]
thanks @jimafisk, all good now.
