### ISSUE TITLE
Mobile/tablet views on Hub don't have 'log in' button or link.

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#1028]
Before someone is logged in, the log in button should appear in the menu where 'my account' shows up.

Then, once someone is logged in, the log in button should be replaced by 'my account'

**Comment by finneganh** [comment]
OK, looks like this is the default header behavior of hiding all non-"Translate" links on lower breakpoints. You can see this on Boston.gov as well.

I'll need to put in a class that lets this stay visible in the pattens library, then update this to use it..

**Comment by finneganh** [comment]
Added coverage for this in CityOfBoston/patterns#272 but it looks like all we need is to add `nv-h-l-a--k` to the “Login” and “My Account” `<a>` tags.

**Comment by reillyzlab** [comment]
@BrutiAnteneh for you to test
