### ISSUE TITLE
Numbered lists bug in Drupal text components

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#1033]
The circle for our numbered lists is getting cut off in text components when you use a fifty / fifty split:
![image](https://user-images.githubusercontent.com/7929556/37607321-16700e9c-2b6e-11e8-8b89-c7718a68ae3a.png)

Looks like the margin in this snippet of CSS might be causing the issue:

article ol>li:before {
    border: 3px solid;
    border-radius: 100%;
    counter-increment: a;
    content: counters(a,".") " ";
    display: inline-block;
    height: 40px;
    line-height: 40px;
    margin: 9.75px 0 0;
    margin: .54167rem 0 0;
    text-align: center;
    width: 40px;
    font-family: Montserrat,sans-serif;
    text-indent: 0;
    margin-left: -55px; /* Think this is the issue */
    margin-right: 5px;
}

When I removed the "margin-left" syntax through dev tools, it looked fixed:
![image](https://user-images.githubusercontent.com/7929556/37607569-bdab9186-2b6e-11e8-9e90-181c8b61faae.png)

**Comment by davidrkupton** [comment]
@jduffy2001 I cannot reproduce this issue on local or staging.  
https://edit-stg.boston.gov/node/17356/draft#text-2-col-50-50
For me in Chrome and Firefox the margin is not an issue when logged in as anon or admin.

**Comment by jduffy2001** [comment]
@davidrkupton you are correct! Just checked the problem page and it's resolved. I can't remember what was happening when I added this ticket. I assume there was something extra in the source code.
