### ISSUE TITLE
Leading / line hight is off on titles and text for landing page

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#105]
Leading/ line hight is off on titles and text for landing page, across the board

![screenshot 2016-07-13 17 04 48](https://cloud.githubusercontent.com/assets/20642299/17137476/5455e31a-5309-11e6-832f-0e55f7fd6c50.png)

@sebastianebarb  need some clarification on this. 

Could you specify the heights? 
- height between the two lines of the title?
- height between the title and the neighborhood?

In the beta sketch files, it's 16px between the blue title and the neighborhood name. 

<img width="494" alt="screen shot 2016-08-02 at 10 41 22 am" src="https://cloud.githubusercontent.com/assets/6685950/17332727/b711a482-589d-11e6-8cf3-2cf20573492f.png">

**Comment by sebastianebarb** [comment]
@hackajesse do you want me to provide dimensions or check that the task has been completed?

**Comment by sebastianebarb** [comment]
@hackajesse 
Top photo
Top # is 11px
bottom is 24px

Bottom photo
bottom is 24px

**Comment by hackajesse** [comment]
@matthewcrist measurements included whenever you update styles for place profiles.

**Comment by matthewcrist** [comment]
Fixed on production.
