### ISSUE TITLE
Potential issue with newsletter signup component

### ISSUE THREAD

**Issue by rachelbraun** [CityOfBoston/boston.gov#1052]
Looks like there might be an issue with our newsletter signup component.

The flagged newsletter list ('Neighborhood Development Policy') looks like it was set up properly in the component and that the taxonomy is  connected to the right list.

Screenshots from Upaknee/Boston.gov showing matching ID number:

![screen shot 2018-05-09 at 9 57 57 am](https://user-images.githubusercontent.com/35377030/39818790-b5d62fe2-536f-11e8-856c-61487757720e.png)

![screen shot 2018-05-09 at 10 00 56 am](https://user-images.githubusercontent.com/35377030/39818800-bc61e554-536f-11e8-802a-2382217e870b.png)

**Comment by rachelbraun** [comment]
Gary Battiston from DND was having a problem with new subscriptions to the Policy Development list (a list of people that _have_ to be notified – and that doesn't require a re-engagement email from Upaknee.)

Yesterday, they tried to add two new names using the newsletter sign-up widget here:
[https://www.boston.gov/departments/neighborhood-development/plans-reports-and-notices]

Neither subscriber received a re-engagement email (which is good) _but_ neither name is on the list. They’re concern that folks may have subscribed that they don't know about.

**Comment by rachelbraun** [comment]
Upaknee support investigated the occurrence and the form within the page cited above and recommended flagging for our own dev team.

There appears to be an issue that is not allowing existing subscriber profiles to be updated with new subscriptions, and that is why both diane.marchioni@boston.gov and shana.berry@boston.gov were unable to subscribe to the Policy Development list.

They tested their internal process for creating and updating new subscriptions and were unable to replicate the problem. When reasonable, they’d like to know more about how the form works and the steps it takes to create subscriptions.

**Comment by rachelbraun** [comment]
From Gary:
Here's a screenshot of the form for the DND newsletter signup:

![2018 05 09 dnd email 1](https://user-images.githubusercontent.com/35377030/39824522-8d210f0a-537d-11e8-9566-79accca5b45b.png)

And here's the very similar form for the Policy news sign up:

![2018 05 09 dnd email 2](https://user-images.githubusercontent.com/35377030/39824524-8f73694c-537d-11e8-9bfa-091b2082c955.png)

"Since it is the basic template, I don't see why the form should be the problem, unless the form isn't working for any of the other lists, or there is something wrong with the name of the Policy list in the drop down list so that it is not sending it to the right Upaknee list."

**Comment by cob-hondo** [comment]
I looked at the contact form and I'm not seeing any errors. (This is in the API at contactform.boston.gov, not Drupal). It also looks like both of those emails are subscribed to the #5 newsletter. Is that the right one?

<img width="1100" alt="screen shot 2018-05-09 at 2 05 58 pm" src="https://user-images.githubusercontent.com/34665739/39831366-35965190-5392-11e8-9726-834bf729afa9.png">
<img width="1186" alt="screen shot 2018-05-09 at 2 06 28 pm" src="https://user-images.githubusercontent.com/34665739/39831367-35a33220-5392-11e8-8daf-df4711457a87.png">

**Comment by rachelbraun** [comment]
@matthewcrist deployed the updates to resolve the issues with getting added to lists on June 7th.
