### ISSUE TITLE
Dig into Drupal 7 tests

### ISSUE THREAD

**Issue by finneganh** [CityOfBoston/boston.gov#1091]
Get awareness of what the Drupal 7 tests are running, take steps to reduce flakiness.

**Comment by davidrkupton** [comment]
See notes on google: 
Phing Map: https://drive.google.com/open?id=1tD7ux3HyhTTgv71Tpcx4VYrmqYdENBz_
Phing Analysis: https://drive.google.com/open?id=1HsNHkBC_UJlUA02zkaQTqzFkHUoZaX-FDPr5tFMT5B0
Document: https://drive.google.com/open?id=1xR21m9EHPxRgbJHIlNEXvbdX4_SH7h-ysJOmTD0iAqI

**Comment by davidrkupton** [comment]
Closing issue as bask finished.
