### ISSUE TITLE
Can't save new draft of event content type

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#1096]
#### Expected Behavior/Acceptance Criteria 
<br>
A user should be able to:
- create an event in Drupal
- publish that event, and
- then go back into the published event to edit and save a new draft of the page.

#### Actual Behavior
<br>
Users don't have the ability to save new drafts of events. Because they can't save changes, they also don't have an ability to preview drafts. The curious thing is that, if a user changes the moderation state to "published", instead of "draft," the proposed changes will be published to the page.

#### Browser
<br> 
All browsers

#### Device
<br> 
All devices

#### Example URL
<br> 
First noticed the issue with this event:
https://www.boston.gov/calendar/celebration-summer-v-donna-summer-roller-disco-party

#### Steps to Reproduce the Behavior/How to Test
<br> 

1. Create a new event in Drupal
2. Publish that event
3. Go back into the published event
4. Try to edit, save, and preview a new draft.

_Reminder: Add any relevant Labels, Projects, and/or Milestone(s). If fields don't apply, please right N/A._

**Comment by jimafisk** [comment]
Related: https://www.drupal.org/node/2824607

**Note:** this is also happening on Posts

**Comment by jimafisk** [comment]
The fix for this has been deployed to stg. @jduffy2001 if this looks ok, I'll push it out to production. Thank you!

**Comment by jimafisk** [comment]
I confirmed with @jduffy2001 that this is work on prod now.
