### ISSUE TITLE
Extra dotted line in sidebar on Script pages

### ISSUE THREAD

**Issue by BrutiAnteneh** [CityOfBoston/boston.gov#1097]
For issue background, refer to https://github.com/CityOfBoston/boston.gov/issues/951
#954 

**TREE AND BENCH DONATION PROGRAM APPLICATION**
URL: https://www.boston.gov/tree-and-bench-donation-program-application

![screen shot on jun 5th at 03_25 pm](https://user-images.githubusercontent.com/33470951/40998135-d81b2ec0-68d4-11e8-9261-fb0e9b94054a.png)

**Example URLs::**
https://www.boston.gov/code-enforcement-public-records-request-form
https://www.boston.gov/annual-statement-financial-interest-filing
https://edit-stg.boston.gov/annual-statement-financial-interest-filing

**Comment by reillyzlab** [comment]
Implement if easy to fix. Close and move on if not.

**Comment by jimafisk** [comment]
Seems to be very similar to https://github.com/CityOfBoston/boston.gov/issues/951

I'll take a look
