### ISSUE TITLE
Remove ability for content authors to unpublish content

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#1122]
#### Expected Behavior/Acceptance Criteria 
<br>
Content authors should not be able to unpublish content on Boston.gov

#### Actual Behavior
<br>
From the moderation tab, a content author could unpublish a page on the website. See the screenshot for the "unpublish" button.

#### Browser
<br>
All browsers

#### Device
<br>
All devices

#### Example URL
<br> 
https://edit.boston.gov/node/7536/moderation

#### Relevant Screenshot(s) or Logs
<br> 
![image](https://user-images.githubusercontent.com/7929556/41659194-9272eab4-7466-11e8-91be-362b52411a92.png)

#### Steps to Reproduce the Behavior/How to Test
<br> 

1. Log into Drupal as a content author
2. Create a "new draft" of any page.
3. Click the moderate button in the top right.

_Reminder: Add any relevant Labels, Projects, and/or Milestone(s). If fields don't apply, please right N/A._

**Comment by jimafisk** [comment]
In `permissions.settings.php`, we removed all instances of `moderate content from published to archive` and `moderate content from published to draft` from the following roles:
- Content Author
- Events Editor
- Press Release Editor
- Procurement Editor
- Status Alert Editor
- Developer
- Site Administrator
- Content Editor

**Comment by jimafisk** [comment]
**Update:** These are the desired permissions broken down by role.

Should be able to publish and unpublish:
- Developer
- Site Administrator
- Content Editor

Should only be able to publish (no unpublish):
- Events Editor
- Press Release Editor
- Procurement Editor
- Status Alert Editor

Should not be able to publish or unpublish:
- Content Author
