### ISSUE TITLE
Add "short title" to Commissions Modules

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov#1123]
Add "short title" to commissions modules that makes a blue secondary navigation link appear at the top of the page. When the user clicks the link, they will be brought to the location of the module on the page.

Example:
<img width="766" alt="screen shot 2018-06-20 at 9 51 38 am" src="https://user-images.githubusercontent.com/12868231/41663077-9a6914fa-7470-11e8-9970-11980aa70c13.png">

**Comment by finneganh** [comment]
Fixed in CityOfBoston/boston.gov#1120
