### ISSUE TITLE
Sidebar module to full-width page module

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov#1124]
Convert the commissions sidebar module to a full-width page module. 

We won't put commissions information in the sidebar due to white spaces issues it creates. Instead we'll create full-width module that displays the same information and can be placed anywhere on the page. 

This component will need a "short title" that creates a secondary navigation link on the top of the page.

The goal is to address this white-space issue: 
<img width="1122" alt="screen shot 2018-06-20 at 10 07 35 am" src="https://user-images.githubusercontent.com/12868231/41663584-c8cb86ba-7471-11e8-9ec5-982d93f314cf.png">

**Comment by finneganh** [comment]
Fixed in CityOfBoston/boston.gov#1120
