### ISSUE TITLE
Grid of card component external links not opening in new tab

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov#1138]
#### Expected Behavior/Acceptance Criteria 
<br>
When a user clicks on an external link in a grid of cards component, this link should open in a new tab in the browser.

#### Actual Behavior
<br>
When a user clicks on an external link in a grid of cards component, they stay in the same tab in their browser.

#### Browser
<br> 
All browsers

#### Device
<br> 
All devices

#### Example URL
<br> 
boston.gov/imagine
<br>
The first link in the "Taking Action" section should open a new tab, but it's staying in the browser. I know @kdonaldson has done some work on this component to add a "lightbox" feature, and I wonder if that might be affecting it.

#### Steps to Reproduce the Behavior/How to Test
<br> 

1. Log into Drupal
2. Create a new draft of the [Imagine Boston 2030 page](https://www.boston.gov/departments/mayors-office/imagine-boston-2030)
4. Attempt to add a new external link to one of the grid of cards sections on the page
5. After saving your draft, see if the link you added is creating a new tab or staying in the same tab

_Reminder: Add any relevant Labels, Projects, and/or Milestone(s). If fields don't apply, please right N/A._

**Comment by BrutiAnteneh** [comment]
The issue passed as expected.
