### ISSUE TITLE
Upcoming events component showing featured event in list below

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#117]
Before, when I placed a "featured" event in the upcoming events component, it wouldn't then show up in the list below.

This seems to have reverted back, so that when you put a "featured" event up top, it still appears in the list below. You can see an example of this on the [Transportation page](https://www.boston.gov/departments/transportation).

**Comment by hackajesse** [comment]
Added to Aha. Will manage from there. Closing here.
