### ISSUE TITLE
Public Notice Content Type

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/boston.gov#128]
For the creation of public notices to meet the open meeting law requirements, we need to create a new content type. This content type will need fields specific to public notices. It will also need to provide a public feed that can be consumed by other applications (signage primarily). 

Here is a doc with the requirements:

https://docs.google.com/a/boston.gov/document/d/1R8oYwwqDnR_0oqutVRPARhgYR-9EDxdUyIoyXxXxvy8/edit?usp=sharing

**Comment by hlieberman** [comment]
@matthewcrist, the Google document linked appears to have sharing restrictions on it.  Can you make it viewable by those who have the URL?

**Comment by hackajesse** [comment]
@hlieberman made it commentable. We've nearly finished it, though at this point. Sorry for the delayed response. We expect to be more responsive in the future. Also, just as a repo management point, the Help Wanted label will be issues we're most in need of feedback / thoughts on. Thanks for checking us out!
