### ISSUE TITLE
City seal doesn't align with top nav

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#129]
As you scroll down any page on Boston.gov, the City seal in the center of the top nav slides up. The bottom of that image doesn't align with the top nav.

http://whatsmybrowser.org/b/C1LW3WD

![seal-reduce](https://cloud.githubusercontent.com/assets/3886936/19742235/11353f6e-9b92-11e6-8115-039ef32f79a2.PNG)

**Comment by hlieberman** [comment]
Is the problem here that you are looking for the bottom seal to end up flush with the bottom of the top nav?

The top bar isn't large enough by my check -- nevertheless that the seal is measured in px, and the bar is measured in rem.

**Comment by hackajesse** [comment]
Thanks, Harlan. You got it - looking for the seal to line up flush w/the
bottom of the top nav.

Recognized that my browser was zoomed to 90%, which is why it showed up.
That said, we're finishing up a new version of the seal, which will be in
rem, not px. :)

Feel free to file your own issues as you see them, too!


[image: COB_B_Blue_square-01.png]

Jesse Biroscak

Product Manager, Boston.gov

Department of Innovation & Technology

City of Boston

617.635.2869 (w), 415.439.3164 (c)

Twitter: @jbiroscak <http://twitter.com/jbiroscak>
P.S. Have feedback on Boston.gov? Email Feedback@Boston.gov!
