### ISSUE TITLE
How should the public be able to reserve rooms on City property?

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#133]
The Bruce Bolling Building in Roxbury, City Hall, Faneuil Hall, 1010 Mass Ave. - these are all City-owned buildings, but we don't have a good way of reserving available rooms in them. For that matter, we don't have a good way of seeing whether they're even available to be reserved.

Research which solution we should use to help us with reserving space properly.

**Comment by edrohler** [comment]
The State of Indiana is using a service on Microsoft Azure titled Azure AD B2C as their authentication mechanism for their citizen users. Citizens can sign up with Facebook, Google, LinkedIn, Microsoft or an email. In addition, we can use azure's search service for each of spaces. Do you have organized data on the listings?

**Comment by matthewcrist** [comment]
Closing this as it would be a separate app and not something built into Boston.gov.
