### ISSUE TITLE
Is there a good open source solution for an online catalogue / store?

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#134]
We have an AMAZING set of old artifacts in Boston. Tons! So many, in fact, that our resident archeologist (yes, we have one and he's seriously awesome) would like to create an online catalogue of them to show them to the world!

Turns out that our Arts and Culture department also has a bunch of stellar artwork for lease or exhibition use. But you wouldn't know about it unless you could find it online, right? They need an online catalogue, too. 

Interestingly, an online catalogue is simply an online store without a "buy" button. With that simple modification, we can expand our use case to the Registry department. They offer marriage, birth, and death certificates for purchase. They need a simple online store so people can search the person they want the certificate for and then buy the certificate. Easy!

Which online catalogue / store service should we use? Are there any open source solutions available that we could hook into Stripe or another payments processor?

**Comment by scuerda** [comment]
Given that you're a Drupal shop I'd imagine you're looking for a PHP implementation to minimize required developer skills, but if you're open to Python implementations something like [Saleor](http://getsaleor.com/l) or maybe [Oscar](https://github.com/django-oscar) could serve your needs.

Saleor looks to be more of a all-in-one solution, with a fairly developed admin backend and a built-in frontend.

Oscar offers the same, but also has the option to use Django REST to expose a RESTful API if there was a desire to roll your own single page front-end or integrate w/ existing sites.

**Comment by hackajesse** [comment]
This is a great set of thoughts, @scuerda! Thank you! @joshuagee want to investigate? You've been the lead on this issue for death certificates in particular. 

I'd be most interested in the roll-your-own option since we have to integrate it seamlessly into Boston.gov styles / includes files.

**Comment by joshuagee** [comment]
That's a ton @scuerda -- probably agree with Jesse about the roll-you-own. The real tough part is integrating with our payment system. This is a great starting place, though.
