### ISSUE TITLE
Set up Boston.gov's github repo as a Docker project

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#136]
For someone without Drupal on their computer, it can take 5 hours to set up their development environment before they're able to constructively contribute to the Boston.gov codebase. 

We should change that. Use the code at our Github repository to make it easy for folks to develop with us.

**Comment by reillyzlab** [comment]
Complete: https://github.com/CityOfBoston/boston.gov/issues/651
