### ISSUE TITLE
Create a test page on Boston.gov showcasing every component

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#138]
Boston.gov has a lot of components and a lot of variations of those components. That makes them hard to check to see if we messed something up in their user interface. 

We'd like to change that. There are likely two options for remedying this situation. For both of these, it would be great to have a program to check the UI against a set of tests or standards we pre-set: 
1. Manually create a page with every component and every variation of those components. For example, add an upcoming events component AND an upcoming events component with a featured event showing.
2. Programmatically create a page with every component and every variation of those components. This would happen during every build process. Use filler text (or a sample database!) for each component.

**Comment by matthewcrist** [comment]
This is done now and visible here: https://www.boston.gov/departments/digital-team/test-page
