### ISSUE TITLE
How-to title and summary expanding past hero on iphone

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#14]
Might be related to component refactoring.

https://www.boston.gov/departments/assessing/how-file-residential-exemption

![](https://cloud.githubusercontent.com/assets/20580335/18928080/94f1c49c-858c-11e6-868c-8d8c37fc00cf.PNG)

**Comment by hackajesse** [comment]
@matthewcrist another image that might be relevant. Lmk if not and I'll create a separate issue.
![image 1](https://cloud.githubusercontent.com/assets/3886936/20942539/b8044c8e-bbc9-11e6-9e66-f281a31b2973.png)

**Comment by matthewcrist** [comment]
Increasing the estimate on this we dig into it.
