### ISSUE TITLE
Make Boston.gov more open source friendly

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#140]
We've opened the source code for Boston.gov and added some good documentation, but it's still time consuming to actually contribute to the code base. 

You have to set up your development environment, you should probably have a sample database to work with, and you might not really know what the components look like with actual content in them. 

This epic is about making Boston.gov easier to develop against and ultimately share with other cities if they choose to fork our repository.

**Comment by scuerda** [comment]
I've seen this topic split up across a few issues ( #139, #137, #136 ). It also looks like you are deploying via Acquia Cloud? 

Given that, I wonder if an Ansible-based playbook that uses [Drupal VM](https://www.drupalvm.com/) might not be a better way to set up both a development environment for contributors and a framework for enabling other municipalities to fork and deploy their own versions than Docker. I love Docker, but doing things like rolling your own fixture loading can get / feel a little magic-y IMO where as Ansible brings a lot of that to the surface in a more explicit way. Drupal VM already uses Ansible as part of the workflow and easily supports using an existing site in the build step. That would allow users to not only set up a development environment but also become familiar to with some of the production deployment steps.

**Comment by hackajesse** [comment]
Thanks for the constructive thoughts, @scuerda. We are on Acquia Cloud, yes. The goal is really to help people get more engaged w/the repo faster. 

I'd ask @matthewcrist, our lead dev, to weigh in on what you wrote.

Are you interested in helping us out on this, assuming Drupal VM?

**Comment by scuerda** [comment]
@hackajesse possibly. TBH I haven't worked much with Drupal which is partially what drew me to looking at these issues.

FWIW, it might be worth teasing out two lines of devops improvements. One for folks who want to fork and deploy and one for folks who want to contribute to the core repo. Probably a lot of overlap, but the Drupal VM seems more relevant for the fork-and-deploy crowd.

**Comment by hackajesse** [comment]
@scuerda all good. 

If you have suggestions for how to tease out those two lines, I'm all eyes. :) At the moment, we're prob targeting the contributors more than the fork-and-deploy crowd, but it's important to offer options.

**Comment by geerlingguy** [comment]
If you want to go the Drupal VM route and run into any issues at all, please feel free to post issues in the drupal-vm issue queue. It was made for drop-in use cases like this, and you can either have it installed via composer as a dependency, or download it, stick it in a 'box' or 'vm' directory, and include it with the code base. See Acquia's BLT project elsewhere on GitHub for an example.

If you include a sample database dump, you could add a post-install Ansible task file that imports it using Ansible's MySQL module, and then setup on a new contributor's computer would be as simple as 'clone project, run composer install, then run vagrant up' (assuming git/PHP/Composer/Vagrant are already present on the computer).

**Comment by BrianGilbert** [comment]
If your looking at Drupal VM you might want to check out Beetbox VM instead, it's built on top of Drupal VM..  https://github.com/beetboxvm/beetbox

**Comment by hackajesse** [comment]
Ref #136 and #191 folks. Let's make sure we're coordinating.
