### ISSUE TITLE
Create a maps component

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#141]
Maps. We love them, but we're not scheduled to build them for a little while (as of end of October 2016) because we need to improve the site navigation, build a new 311 interface, and create an interactive budget page, among other projects.

Are you game to help us?

Some things to know:
- Components on the site are modifications to [Drupal paragraphs](https://www.drupal.org/project/paragraphs).
- We have a few designs already done by IDEO and need someone to execute. 
- This would be a heavily used component, but we just don't have the time-resources to build it soon.

From [IDEO's design spec](https://github.com/CityOfBoston/boston.gov/files/556058/functional-spec-maps.pdf):
The map component shows a map with one or more locations specified. Constituents will use this to view a location on a map, or click to get more information on a place. This is a full width component. Clicking on the pin should show the name and address of the location by default, but there will be special cases (like bike rack locations) where the editor should be able to specify what appears in the tooltip. The map should be Google maps, and can be colored to match these designs using Snazzymaps (click “create” in the top nav).

Use a map page when you need a permanent, singular home for a map component. If you’ve created a map component for bike racks around the city, you can use it in context on articles and topic pages, but you can also deep link to it on its own page. We see maps needing to be used both in context with content and on their own.

Be sure to remember our [brand guidelines](https://www.boston.gov/departments/innovation-and-technology/brand-guidelines) when you're creating this. 

Questions? Just ask and @ mention me.

**Comment by reillyzlab** [comment]
Closing
