### ISSUE TITLE
Create landing page author role in Drupal 

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#143]
Some people [particularly on Hub] will need to edit landing pages in Drupal. However, content author permissions do not include any editing/creating of this page type.

This would be a separate role called Landing Page Author. It would be added to someone's existing Content Author role, so the permissions are specifically related to editing/creating landing pages.

Permissions to enable:

Landing Page: Create new content
Landing Page: Edit own content
Landing: Edit any content

**Comment by matthewcrist** [comment]
Should be on production.

**Comment by reillyzlab** [comment]
On production and working as expected. Closing ticket.
