### ISSUE TITLE
How to: Hide tab if only one tab is used

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#150]
On how to page type, if only one tab is used, then the tab should be hidden. If two or more tabs are used, then the how to page should act as is current built.

This will mostly likely mean that the line height will also need to adjusted to fill the space where the tabs would normally appear.

Description text should be added to this page: /node/add/how-to to explain this functionality
![how to description text](https://cloud.githubusercontent.com/assets/20731897/19819609/77fef8a6-9d23-11e6-98fc-fe5466a09485.PNG)

Example text: If only one tab is entered, then the tab will not appear. Consider adding more descriptive text to the 'intro text' under basic information.

**Comment by matthewcrist** [comment]
This is blocked until #14 is done. Removing the tabs is easy, but the styling to handle the removed tab case needs to be done along side #14.
