### ISSUE TITLE
How to: Change title of field

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#151]
On how to, under 'basic information', change the 'body' field to be 'intro text' to match the other page types throughout the sites;

![body to intro text](https://cloud.githubusercontent.com/assets/20731897/19820070/953af922-9d25-11e6-8e54-f2d683ba7ae0.PNG)

This should enhance a content contributors ability to understand where they should be entering relevant content.

**Comment by matthewcrist** [comment]
Ready on production

**Comment by reillyzlab** [comment]
Tested on both hub and boston.gov and confirmed changed. closing ticket.
