### ISSUE TITLE
Make End Date in date picker start closer to today's date

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#160]
On /events and /news, the end date date picker starts ~7 months after today's date. Make it start 2 weeks after today's date.

![date-picker-events](https://cloud.githubusercontent.com/assets/3886936/19868232/8b9317c4-9f7d-11e6-9b5d-90302b46b461.PNG)

**Comment by matthewcrist** [comment]
After talking with Jesse, here's what has changed:

 * On events, the filter starts with today and ends three months from now. We've limited the number of results to 30 per page.
 * On news, the filters remain blank and we've changed the number per page to 30.

**Comment by hackajesse** [comment]
Looks good to me for Boston.gov. @reillyzlab for the Hub?

**Comment by reillyzlab** [comment]
good on Hub too so closing
