### ISSUE TITLE
Repeating Events features

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#161]
Events can repeat on Boston.gov, but the experience isn't good for either the event creator or the event posting viewer. Repeating events should be intuitive to both create and understand. 

[Initial user stories and acceptance criteria. ](https://docs.google.com/document/d/1HliqgW85EYMtNV1YCDBMZXD2xTqVQ1sUk7PQUqDZ4uU/edit?usp=sharing)

@asalsman would you flesh out some of the tech requirements, asking any questions you have in this epic conversation? You can create issues afterwards for the epic task list. Epic!

**Comment by asalsman** [comment]
[Results of technical assessment and research as well as questions](https://docs.google.com/a/boston.gov/document/d/1WOXTV-wnb0qhcmtVJAQywuTbsRmX4k5V3Nxs2T8lhUs/edit?usp=sharing)

**Comment by hackajesse** [comment]
Creating a new issue from our product management software and syncing here. Closing this.
