### ISSUE TITLE
Showcase "documents" more on Boston.gov

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#163]
Feedback from a constituent. Responded with questions about which documents she'd like more easily discoverable.

URL: https://www.boston.gov/
BROWSER: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
--------------

The new site looks great and has clearly been re-tooled towards residents.  However, as a resident and a professional who is used to getting documents off the site, it is harder to locate the documents that are needed to do business with the city (for example, engineering specs).

In my 30+ years as a resident of Boston, I have used Boston.gov for professional needs significantly more than I have for personal needs.  I'm sure I'm not alone.

There should be some balance between the two users - or at least a way to easily access studies and documents.  Perhaps there could be a link to documents on the front page.

**Comment by gilronc** [comment]
Maybe a Publications Content Type can be created......A great example is Gov.UK (https://www.gov.uk/government/publications) and they've even documented their reasoning behind their choices and provided sample use-cases(https://www.gov.uk/guidance/content-design/content-types).  This can probably work on Boston's website by creating a Page View of all Publications.  Departments would be able to add their publications to the City's main Publications Page(Similar to Events/News) and they can use a Component to list their featured Publications on their homepage.

Possible Fields:
Title (Text Field)
Publication Type(Taxonomy Reference--Eg: Policy, Report,Guidance etc)
Document(File Field)
Details (Body Field)
Publication Date (Date Field)
Date Updated (Drupal Default)
Department(Taxonomy Reference)
Optional---Thumbnail/Image
