### ISSUE TITLE
Link to this repo from post announcing that boston.gov is open source

### ISSUE THREAD

**Issue by timmc** [CityOfBoston/boston.gov#164]
I was excited to read https://www.boston.gov/news/mayor-walsh-announces-open-sourcing-bostongov but then had to guess my way to this repo. I was surprised that there was not a link!

Perhaps a part of #140. :-)

**Comment by matthewcrist** [comment]
@jduffy2001 can you tackle this?

**Comment by jduffy2001** [comment]
I added a link to the press release. That's all set:

https://www.boston.gov/news/mayor-walsh-announces-open-sourcing-bostongov?new
