### ISSUE TITLE
Workbench Moderation security update

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/boston.gov#180]
There's a security update for the workbench moderation module. The version that is required to move to contains major changes to how content is moderated. Will need to spend some time with it to figure out the best path forward.

**Comment by matthewcrist** [comment]
Here is an issue on the Drupal side: https://www.drupal.org/node/2824607

**Comment by hackajesse** [comment]
@matthewcrist that doesn't look fun at all for our content authors / editors. :/ Thx for the update. 

Adding Help Wanted label so folks checking out our repo can potentially help.
