### ISSUE TITLE
News and announcements component - require title

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#182]
On the news and announcements component, if a title is not entered a title line is still appearing.

If a title is not entered, then the line below the title should disappear.

![news and announcements title](https://cloud.githubusercontent.com/assets/20731897/20062713/b0b6db1c-a4d2-11e6-9a95-926940ded061.PNG)

**Comment by matthewcrist** [comment]
Seems like the issue here is that the title isn't required. @reillyzlab or @hackajesse is there any reason why the title shouldn't be required? i don't see one.

**Comment by reillyzlab** [comment]
I don't see a reason that it shouldn't be required, but if we do that could we make it required and allow for content contributors to 'hide title bar' like their able to do on the text component?

**Comment by hackajesse** [comment]
My preference would be to require it. A component like this should be titled - sometimes tough to tell whether the cards are events or posts, so that clarity is important.

@reillyzlab thoughts?

**Comment by jduffy2001** [comment]
Agree with the title being required. The only difference between the events and posts components is the author information under posts. Might get confusing for a user.

**Comment by reillyzlab** [comment]
Confirming: Please make the title required and don't allow for people to hide the title.

**Comment by reillyzlab** [comment]
Passed QA on Hub. Assigning to @hackajesse to check on Boston.gov

**Comment by hackajesse** [comment]
Passes Boston.gov. Closing.
