### ISSUE TITLE
Events Component (Detailed Listing Page) - Cost Field Not Appearing

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#183]
**Background:** 
On many events the 'cost' field is being left off.

On events detailed listing page, the cost isn't showing up even when it is entered by a content contributor. Cost does show up on the events listing page at /events.

Shows up on boston.gov/events
![events-screen](https://cloud.githubusercontent.com/assets/20731897/20147812/aebc8b12-a677-11e6-8514-742bee5d65bd.PNG)

Doesn't show up on:
https://www.boston.gov/calendar/veterans-day-parade

**Goal:** Ensure that all events have a cost field entered so that as a user I can see whether there is a cost associated with the event or not.

**Requirements:**
- Please make adjustments to ensure that 'cost' field shows up on all event detail pages like the following:

This should appear in the right sidebar (see functional spec.) and fall between 'contact' field and 'neighborhoods'
![functional spect for price sidebar](https://cloud.githubusercontent.com/assets/20731897/20148316/048a6698-a67a-11e6-9bd7-99cfca1b361f.PNG)

- When adjusting this field, please also make this field required for content contributors.

**Acceptance Criteria:**
- Cost shows up on events detail page.
- Cost field is required for content contributors.

**Comment by matthewcrist** [comment]
This is on staging.

**Comment by hackajesse** [comment]
Sending back to Ready column.
On staging:
Cost entry field is not required in the CMS and accordingly [does not display](https://edit-stg.boston.gov/calendar/city-hall-go-cart-hyde-park-0) on every event. While it does display if the content author enters a cost, if there's nothing in that field, there's nothing on the event page. 

Default to an event being "Free" if not changed in the CMS.

**Comment by hackajesse** [comment]
This looks good on Boston.gov. 

However, realized that if someone doesn't use the dollar $ign, the number shows up as entered. Aka if you type 9,000 instead of $9,000, you get 9,000. We should think about adding a $ and commas automatically if someone enters a number. Didn't specify that in the spec, so will create a new issue pending chat w/ @reillyzlab when she reviews.

**Comment by reillyzlab** [comment]
Passes on Hub.

Agreed - we need to create a separate ticket that would include value validation.
