### ISSUE TITLE
Create an RSS feed in the CMS

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#192]
Hi @asalsman - 

We can create RSS feeds in Drupal via path Structure >> View, but only Hub and staging have access to that menu item. 

Can you investigate:

1. Why it is only in those environments
2. Whether it is in those environments by accident

and then give both Hub and Boston.gov Administrator roles access to that menu item?

Thank you!

**Comment by matthewcrist** [comment]
We shouldn't allow View access in Production. We need to investigate why it shows up in Hub prod and disable it. Then turn it on in the staging environments for both sites. This will need to be done in the settings files via the Acquia Environment variables.

**Comment by hackajesse** [comment]
@matthewcrist ok. @asalsman end goal is to be able to create RSS feeds without developer help.

**Comment by matthewcrist** [comment]
Assigning to @hackajesse to think about how to best apply this to the site.

**Comment by reillyzlab** [comment]
Closing b/c separated into tickets based on content types
