### ISSUE TITLE
Dates not appearing on news or events components on tablet or mobile

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#193]
Dates not appearing on news or events components on tablet or mobile at all.

See boston.gov homepage:

![img_5463](https://cloud.githubusercontent.com/assets/20731897/20311209/ea62c60a-ab1c-11e6-8df8-66450dd23c4e.PNG)

**Comment by asalsman** [comment]
Definitely caused by the changes I made in issue #25. Same flag, different event box layouts. Working it now.

**Comment by reillyzlab** [comment]
Was fixed. Closing ticket.
