### ISSUE TITLE
Events and Public Notices: Add additional clarifying language for event date (end time)

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#197]
When content contributors enter event date start date/time and end date/time they must select a checkbox says 'show end date' Only after they select this select this checkbox does the option to add in an end date/time appear for content contributors to enter those items.

A fair number of content contributors seem to be missing the option to add in an end time.

To resolve, please add the words 'and time' to the line that says 'show end date'.
![end date-time](https://cloud.githubusercontent.com/assets/20731897/20352039/b90dc15a-abe3-11e6-9a3b-77aa80853737.PNG)

**Comment by hackajesse** [comment]
@asalsman this applies to public notices _and_ events on both the Hub and Boston.gov

**Comment by reillyzlab** [comment]
Passed QA on Hub. Reassigning to @hackajesse to check on boston.gov

**Comment by hackajesse** [comment]
Passes boston.gov too. Closing
