### ISSUE TITLE
Tools/apps list becoming unchecked/unavailable post-deploy

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#199]
After we made a deploy to incorporate the new public notice feed the tools/apps somehow became unchecked and wasn't surfacing the list of applications for /tools on Hub.

Matt resolved by re-enabling, but further investigation is needed to determine if this will do this again next time we have a deploy and how to resolve if so.

**Comment by matthewcrist** [comment]
This should be fixed. You should be able to edit the page after this deployment.

**Comment by reillyzlab** [comment]
Confirming fixed. Closing ticket.
