### ISSUE TITLE
Show event date in events that have passed

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#20]
Right now, when an event date passes, the date of the event is removed in the top right section of the event. You can [see an example](https://www.boston.gov/calendar/ada-day-2016) here.

Passed event:
![passed-event](https://cloud.githubusercontent.com/assets/3886936/19360042/d784b96c-914a-11e6-9f30-ab9ea837ac76.PNG)

Future event (desired UI):
![future-event](https://cloud.githubusercontent.com/assets/3886936/19360055/e4b3290c-914a-11e6-9e73-aed585bcc82b.PNG)

**Comment by asalsman** [comment]
Confirmed this is functional on both Events and Public Notices.
