### ISSUE TITLE
Related content field functionality

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#201]
Related content fields in the CMS are non-functional except for the one titled "Related Content". There are opportunities for the other types of fields. This is a detail of that opportunity.

- [ ] Tagging events and public notices with a related content field
    When I tag a field in Related Content on {event / public notice} content type, it should display in the {UPCOMING\_EVENTS} component of the associated node, assuming a content creator has already created such a component.
    
- [ ] Tagging posts with a related content field
    When I tag a field in Related Content on {post} content type, it should display in the {NEWS\_ANNOUNCEMENTS} component of the associated node, assuming a content creator has already created such a component.

**Comment by asalsman** [comment]
In researching I've found that not-Public Notices display related departments down at the bottom of the page with "TBD:" as a header instead of something akin to Public Notices which displays the header as "WHO'S INVOLVED:"

Thoughts on how to handle this on non-Public Notice pages?

**Comment by hackajesse** [comment]
@asalsman Replicate what exists on Public Notice pages w/"WHO'S INVOLVED:" for posts and events content types. Note that related departments seem to be doing triple duty: they're relevant for search, for tagging (related content), and for the UI display at the bottom of public notices, events, and posts.

**Comment by asalsman** [comment]
Thoughts/investigation on Related Content/News Tags:
https://docs.google.com/a/boston.gov/document/d/1BxBfu6067YCgpNJbxaC9g5sH1jAyAxjxtbewY4a_c34/edit?usp=sharing

Will set some time up tomorrow to discuss.

**Comment by asalsman** [comment]
Assigning to @hackajesse for next steps after our last conversation.

**Comment by asalsman** [comment]
After meeting with @matthewcrist and @hackajesse yesterday, our plan is to attempt to make the "News & Announcement" view contextually aware of the content it is slotted on with a final conditional that if it can't create a context, to just use the default "Related Content: Related Content" field (soon to be known as "Other Content").

Barring that, we will make multiple views, each with a different context so that the view is made to be contextually aware.

But, hopefully, the first one.

**Comment by hackajesse** [comment]
It's been a long run, Epic. I'm closing you down since everything is checking out nicely.
