### ISSUE TITLE
Related content functionality on Public Notices

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#202]
How are Public Notices (on boston.gov/public-notices) filterable? How are Public Notices taggable with related content? Reference  [#BOS-3](https://cityofbostondigital.aha.io/features/BOS-3)  aka #﻿201

- [x] People
    References person profiles
    
- [x] Places
    Should reference the following type of place profiles:
    
    - cemeteries
    - community centers
    - parks
    - historic districts
- [x] Events or Public Notices
    References both events and public notice content types
    
- [x] Posts
    References posts
    
- [x] Programs / Initiatives
    References program / initiative content type
    
- [ ] Neighborhoods
    These should reference neighborhoods (one type of place profiles).
    
    These should appear in a two column, checkbox format. Not an auto-fill reference field.
    
    Outside of normal related content functionality, this should allow public notices to be filterable by selected neighborhood.
    
- [x] Guides
    References guide content type
    
- [ ] Related Departments
    These should reference departments, but allow for more than one department to be entered.
    
    Should not be required.
    
- [x] All Other Content
    These should reference any content not covered in the other fields. That likely means articles. No need to reference How Tos.

**Comment by matthewcrist** [comment]
This story should be broken up into more discreet items. For example: 

---- Story 1 ----

**As a content editor, I want to be able to add related people to public notices.**

## Acceptance Criteria

 * Content editor can add related people to public notices
 * People should be listed as checkboxes

---- Story 2 ----

**As a site visitor, I want to be able to see related public notices and events on people profile.**

## Acceptance Criteria

 * When a user visits a person profile page, they should see all public notices and events that have been tagged with that specific person.

**Comment by hackajesse** [comment]
Creating separated-out issues from this one. Will reference from those. Closing.
