### ISSUE TITLE
Events component should display Public Notices

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#205]
A public notice content type tagged with any related content should show up in the events component on the specified related content node(s).

**Comment by hackajesse** [comment]
@sebastianebarb - would you create a comp for what a public notice should look like when shown within an events component? This is the public notice equivalent for an event in an events component.

**Comment by sebastianebarb** [comment]
[Public notices in news.pdf](https://github.com/CityOfBoston/boston.gov/files/604085/Public.notices.in.news.pdf)
@hackajesse

**Comment by hackajesse** [comment]
Not so much  in /events as in an actual events component, @sebastianebarb. Would you comp a public notice for the events component?

![events-component](https://cloud.githubusercontent.com/assets/3886936/20490705/dcb91bb6-afdc-11e6-824d-fc3d2d6602fe.PNG)

**Comment by sebastianebarb** [comment]
@hackajesse how about this?
Mock
![public notices hero](https://cloud.githubusercontent.com/assets/20642299/20527801/b9805c34-b097-11e6-9c1d-6991fcf96dad.png)

SVG
https://drive.google.com/open?id=0B0RwQU94BhGecjA5RkJWWjdSTEk

Sketch
https://drive.google.com/open?id=0B0RwQU94BhGeaXBWa19yU1d6NjA

**Comment by hackajesse** [comment]
Add copy to the icon: "public notice". 
Change from News / Announcements component to Upcoming events component
Ensure there's a Featured public notice and a non-featured public notice in the comp. 
See what adding Dept name onto each card looks like.

**Comment by sebastianebarb** [comment]
![public notices hero](https://cloud.githubusercontent.com/assets/20642299/20630836/76830672-b301-11e6-9517-1cb2783210a5.png)

**Comment by hackajesse** [comment]
Thanks, @sebastianebarb. Closing this issue and opening a new one for the tech part.
