### ISSUE TITLE
Location updates to Public Notices content type

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#208]
Updating the location section of the public notices to adjust post user testing.

- [x] Remove "Company"
- [x] Change copy on Full Name and add help text
    - Make "Full name" optional
    - change to "Name of location".
    - Add help text "For example: Ianella Chamber, BPDA Conference Room, or Environment Department."
- [x] Change copy on Address 1 and add help text
    - Make Address 1 required
    - Change to "Address of location".
    - Add help text "For example: 1 City Hall Plaza or 1010 Massachusetts Ave."
- [x] Change copy on Address 2 and add help text
    - Make sure Address 2 is optional
    - Change to "Room or floor number".
    - Add help text: "For example: Fifth floor or Room 709."
- [x] Add help text to zip code: "City Hall is 02201."

**Comment by matthewcrist** [comment]
Ready on production

**Comment by hackajesse** [comment]
Looks great. Thank you! Closing.
