### ISSUE TITLE
Public Notice content type doesn't style "Who's Involved" 

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#209]
Related departments under "Who's Involved" don't style as defined department mini-cards, but should. They appear in Lora.

 

https://www.boston.gov/public-notices/11406

whos-involved-public-notices.PNG (https://cityofbostondigital.aha.io/attachments/token/dfb20fdd95094858acaca016fffa8112e9a31f6bd761cad47dfa7e5dd60f2882.download)

**Comment by matthewcrist** [comment]
Ready on production

**Comment by hackajesse** [comment]
Confirmed - looks good. Closing.
