### ISSUE TITLE
Repeating events

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#211]
Events can repeat on Boston.gov, but the experience isn't good for either the event creator or the event posting viewer. Repeating events should be intuitive to both create and understand.

- [ ] Cancel an event in a series without affecting the whole series
- [ ] Update a single event, all events, or all events after a certain date in an event series
- [ ] Create a multi-day event with specific hours for each day
- [ ] Viewers see an event listed past its start time
    1. Events with start and end times should display the entire time they are running
    2. Events without an end time should display the entire day they are running
    3. Events that are part of a multi-day consecutive series should display the entire day they are running.
- [ ] Viewers should see the date displayed on events already past
- [ ] Viewers should understand an event is part of a series
    Assumes the event is part of a series.
    
- [ ] Viewers should understand immediately whether an event has been canceled
- [ ] Viewers should know when an event was first posted and whether it has been updated
- [ ] Event creators should not spend twice the effort to create two events if the events are similar.
    Event creators should not have to expend as much effort to produce an event of similar detail as another existing event (phone, type, location, contact, title, body copy, thumbnail, date, time, hero) as they would to create a new event. Aka, they can clone, duplicate, use a template, or some other solution that is easy to use.
    

Repeating Events Requirements.pdf (https://cityofbostondigital.aha.io/attachments/token/558fb4d11d8998a3c35588bf9c7176ee075c8792b87dc012e718e4cdb090c8ee.download)
Repeating Events: The Technical War.pdf (https://cityofbostondigital.aha.io/attachments/token/3d559923d3884ea455636266f8df18ee99a74481008f0cbb1f7d3d7ada651d23.download)

**Comment by reillyzlab** [comment]
@hackajesse might be reflected above but can't 100% tell. 

We also need to make sure that when any event repeats and you click on a version of the event that is not the first day (i.e. event is originally entered/starts on 1/30 but when you click on the calendar for 2/6 that the 2/6 day shows 2/6 as the date and not 1/30).
