### ISSUE TITLE
Live stream indicators on /events not quite right

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#212]
The live stream indicators on /events aren't quite as defined. Here's what needs to be improved:

- [ ] Show the video icon when events have a video component
    Just the play icon, not the word "LIVE"
    
- [ ] Events with a live stream need "LIVE"
    Any event with a video component on it and the live stream box checked should have the word "LIVE" show up to the right of the play video icon when on /events
    
- [ ] Make play icon thicker to match font weight
    It won't be an exact match of font weight, so play around and check with @sebastianebarb before moving on.
    
- [ ] Make "LIVE" the same font size as the event title
    Make the font bigger
    
    Add ":" after the word "LIVE" so it looks like the event is live.

**Comment by asalsman** [comment]
Points 2, 3, and 4 should all be addressed with the commit I'm about to make.

Point 1 is problematic. With some work, I was able to get the calendar view to know that components are attached to an event, but neither the event or the calendar know anything about the components.

There's no meta that gets sent to either of them that differentiates between, say, a video component and a grid of people component.

So point 1 will remain outstanding for now. Maybe spin it off into it's own issue?

**Comment by hackajesse** [comment]
Created #253 to account for the first checkbox. Feel free to address that separately.

@asalsman - move this issue to QA when you merge.

**Comment by matthewcrist** [comment]
@asalsman please verify this on edit-stg.boston.gov. if working, move to acceptance queue and assign to @hackajesse.

**Comment by asalsman** [comment]
Changes are *NOT* on edit-stg. Looks like PR 231 was closed but never merged:
https://github.com/CityOfBoston/boston.gov/pull/231

@matthewcrist: Does it need to get re-opened or should I create a new PR?

**Comment by matthewcrist** [comment]
@asalsman this should be on stg now. please test. if there, move to acceptance and assign to jesse

**Comment by asalsman** [comment]
When live stream was on the event, the data was able to pass through to the calendar front. Now that it's not, the data isn't either. Going to need to revisit this.

**Comment by asalsman** [comment]
Turns out we do something similar to what I had in mind on topic pages where we go, get the components, get some data off of them, and set them to variables on the topic pages in boston_preprocess_node_topic_page();

Stands to reason that I can do the same thing for an event page and then have that data available to the event that gets passed to the calendar. Going to start playing with it now that I've done some investigation.

**Comment by asalsman** [comment]
I'll leave final confirmation of this for when @hackajesse is back in the office, but this is working properly now on dev and stg. Everything should have been cleared up in a patch that went up two weeks back.

**Comment by reillyzlab** [comment]
All set on Hub

**Comment by hackajesse** [comment]
Looks good on Boston.gov staging.

**Comment by hackajesse** [comment]
Closing.
