### ISSUE TITLE
Live stream page doesn't reload after countdown finishes

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#213]
Any page with a live stream should reload the page or show the play button after the countdown finishes. It doesn't at the moment. You have to reload the page yourself and many folks don't know how to do that.

**Comment by matthewcrist** [comment]
@asalsman please verify this on edit-stg.boston.gov. if working, move to acceptance queue and assign to @hackajesse.

**Comment by asalsman** [comment]
Confirmed on edit-stg.

**Comment by hackajesse** [comment]
Well done, @asalsman. Thanks! Assigning to @matthewcrist to confirm it makes it into the release.
