### ISSUE TITLE
Live Stream needs to be associated with the Video component type, not the Event & Public Notice content type

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#214]
Shouldn't live stream be associated with the video component on the page?

For example, the checkbox for "this is a live stream event" is on an event content type rather than in the video component.

**Comment by asalsman** [comment]
Valid, based on request. Focused on event, missed that one little sentence.

My concern of attaching it to the video component is that it now opens up any content type with video attached to have a live stream component. We'd want to build it to short circuit if the the parent isn't an event page, at least in the short term, and go straight to being a video.

Once we do that, one by one, we can add in content types, if/as desired, to make the QA lift manageable.

**Comment by hackajesse** [comment]
@asalsman that sounds reasonable (short circuiting). 
Can you clarify whether you'd be short circuiting the JS for the countdown or the UI changes to listing pages or both? Specifically any dev difficulties / excessive work. My preference would be to short circuit the UI changes to listing pages only.

**Comment by matthewcrist** [comment]
@asalsman @hackajesse we should be able to have live stream video components on any content. the component should be the driver of whether there's a live stream going to happen.

**Comment by asalsman** [comment]
So says @matthewcrist, so say we all. Will kick this off.

**Comment by asalsman** [comment]
So, here's a caveat I've realized now that I'm 80% done:

Based on functional specs, Live Stream requires a start time. Before that start time, there's a "the stream starts later" message. Most content types don't actually have a start time meta field. This leads us to extending the video component further *OR* building in failsafes to not display the live stream pre-message.

Given @matthewcrist's opinion above, it would seem to be most prudent to include a start date/time on the video component. This does force the user to set duplicate start times when a live stream video is included on Events & Public Notices, but makes them available for all other content types.

I'm going to proceed under that assumption. If it's decided to take a different route, it won't be difficult to course correct.

**Comment by hackajesse** [comment]
@asalsman confirming you should proceed as you wrote.

**Comment by matthewcrist** [comment]
@asalsman your PR for this is on stg. can you test and send to acceptance?

**Comment by asalsman** [comment]
This looks good on stg to me and is functioning as expected.

**Comment by hackajesse** [comment]
@asalsman can you clarify why Live Stream shows on the event content type still? Is that necessary for the JS to function? Or is this an oversight?

![live-stream-event](https://cloud.githubusercontent.com/assets/3886936/21459299/03151192-c90b-11e6-9322-5766648b648c.PNG)

**Comment by asalsman** [comment]
That shouldn't be there. And wasn't there on either my local or on edit-stg. I'm not certain how that is actually there. I may need to look at @matthewcrist for some thoughts.

**Comment by matthewcrist** [comment]
@asalsman the field needs to get added to a vertical tab group and then the feature needs to be re-exported.

**Comment by asalsman** [comment]
@matthewcrist The live stream field is no longer associated with events, but with videos. But despite deleting it via the UI (at this point it disappears), exporting it, committing it, and running build:local (at this point, it reappears), it persists. I did try adding it to a vertical group before deleting it and running build:local through those steps, but no love. Very confused.

**Comment by matthewcrist** [comment]
@asalsman you need to create a hook in bos_core to delete the field ... something like 

```php
/**
 * Delete field_feature_an_item from the news and announcements component.
 *
 * Work for: Sprint 11
 */
function bos_core_update_7001() {
  $delete_fields = array(
    'field_feature_an_item',
  );
  foreach ($delete_fields as $field) {
    if (field_info_field($field)) {
      field_delete_field($field);
    }
  }

  field_purge_batch(10);
}
```

**Comment by reillyzlab** [comment]
All set on Hub

**Comment by hackajesse** [comment]
Looks good on Boston.gov staging.

**Comment by hackajesse** [comment]
Closing.
