### ISSUE TITLE
Add department to Video component

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#216]
Department doesn't show in the video component, but it should. Take the department from the contact required on whichever content type the video component appears on.  @sebastianebarb will add a comp.

**Comment by sebastianebarb** [comment]
https://drive.google.com/open?id=0B0RwQU94BhGeT2NuSlUzTWt2cFE

**Comment by asalsman** [comment]
I can't find anything in that sketch file to direct me on where department should be rendered/how it should look. Can I get some additional direction, @hackajesse?

**Comment by asalsman** [comment]
@sebastianebarb hooked me up. I kinda grok what's going on in sketch and he showed me what I'm missing.

**Comment by asalsman** [comment]
So, on an event, we have contact which refers to department. Then there's video credit on the video component (non-required field).

What is the priority between video credit and department credit? Should:
- Both be displayed
- Department always win
- Video credit beats Department, when it's entered

No horse in this race for me, just want to know priority meta.

**Comment by hackajesse** [comment]
Is there space for both?
Can dept become a link?

No commitment yet on priority. ;)

**Comment by asalsman** [comment]
@hackajesse All of the data is available, so anything is possible. I'll work something up today. You/ @sebastianebarb can take a look and offer some direction once I have it all built out.

**Comment by asalsman** [comment]
I've got something done locally, but the more I look at and test this, the more confusing I think this can end up being for both the person inputting the video and the end user.

On the video, there's a field "video credit" where the instructions tell the user how to tag a dept. and then pulling in the dept. from the event itself. I can see situations where it gets duplicated by the user and then in the display.

Additionally, based on the comps, where does the "By:" factor in on the display?

Am I overthinking this?

**Comment by hackajesse** [comment]
@asalsman data will stay contained in the component itself. So don't pull department into the Video credit on the video component. 
Instead, turn the Video Credit field into an autopopulating field pulling data from departments and programs / initiatives. 
Copy should be "Credit: ___name of dept / program / intiative___"

Not required.

**Comment by asalsman** [comment]
I can have the field pull from Department OR Initiative/Program, but not both. Or we can add two optional fields so both are covered.

**Comment by hackajesse** [comment]
@asalsman move to QA if ready for review.

Pull from Department only if that's the only option. @matthewcrist can you confirm Adam's statement above?

**Comment by matthewcrist** [comment]
@asalsman is this done?

**Comment by hackajesse** [comment]
@asalsman let's clean up this component a bit. Please keep the Department auto-populate and rename "Department credit". Please ditch the "Video Credit" and associated field since they don't do anything.

Screenshot taken from staging. 

![video-department-credit](https://cloud.githubusercontent.com/assets/3886936/21647800/b2394eba-d269-11e6-8476-12bb5956b223.PNG)

**Comment by reillyzlab** [comment]
All set on Hub

**Comment by hackajesse** [comment]
Works for me. Closing.
