### ISSUE TITLE
Show department full contact info on Posts

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#217]
Posts currently show only a small snippet of the department. See attachment. 

Posts _should_ pull in all information from the sidebar of a department's contact page. See revised attachment (including any extra phone numbers, contact info, etc. added as additional sidebar components). 

posts-sidebar-contact.PNG (https://cityofbostondigital.aha.io/attachments/token/09d2a77c5feba6a6d154710a907f06b28500aeef946ed547f572d779eb4d1e3f.download)
posts-sidebar-revised-contact.png (https://cityofbostondigital.aha.io/attachments/token/a15fc3605d002f84e1112be6c5691c03479bbc1cb42f0837973370c451961845.download)

**Comment by reillyzlab** [comment]
Hasn't been tested so would need to be including in D8 if we implement
