### ISSUE TITLE
Have authenticated users be able to see all unpublished content

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#232]
In the CMS under People >> Permissions >> Authenticated Users >> Workbench Moderation, enable "View all unpublished content."

**Comment by matthewcrist** [comment]
@reillyzlab should this apply on the Hub? My guess is not, since everyone is authenticated in the Hub.

**Comment by reillyzlab** [comment]
@matthewcrist Yes, please no on this for Hub

**Comment by hackajesse** [comment]
This is on production now. Closing.
