### ISSUE TITLE
Turn moderation notes into a record of page edits

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#235]
In the CMS, content authors do not generally use moderation notes. However, moderation notes make the process of approving draft content much faster for users with publishing rights. This story details how moderation notes should evolve so that they become a regular part of a content creator's content creation process.

Note that this applies to all content types.

- [ ] Make moderation notes required
    Moderation notes are not required currently. They should be.
    
- [ ] Change help text
    From: "Provide an explanation of the changes you are making. This will help other authors understand your motivations."
    
    To: "Briefly explain what changes you made. The page will be published sooner. For example: Added a mission statement, updated the link to the PDF on housing equity, and/or switched the photo of the dept chief."
    
- [ ] Change "Moderation Notes" section title to "What changes did you make?"

0e36ce82-83fe-11e6-92b9-b235a4b6bdf5.PNG (https://cityofbostondigital.aha.io/attachments/token/aafe4878c984e7c86d9d422e4932881ab376a1dac3b3c527527cf907d4e96aac.download)

**Comment by hackajesse** [comment]
Takes the place of #88.

**Comment by matthewcrist** [comment]
This one will need to wait until #180 is fixed. The moderation structure is completely different between the two version. Any custom work needed to complete this task would lock us in to the 1.x branch which has security issues.

**Comment by hackajesse** [comment]
Thx for the heads up. Will wait. 
cc @jduffy2001 @reillyzlab
