### ISSUE TITLE
Public notices shouldn't be promoted to front page automatically

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#236]
Public notices are defaulting to "promoted to the front page" in Publishing Options when creating a public notice. They shouldn't.

promoted-to-front-page.PNG (https://cityofbostondigital.aha.io/attachments/token/ab5c3c2ffa98604c70b10a51422b04988ef68fbaebaa82438247ad0227eec691.download)

**Comment by matthewcrist** [comment]
Ready in prod

**Comment by hackajesse** [comment]
Looks good. Closing.
