### ISSUE TITLE
Boston logo cutting off 'Public Notices' in header

### ISSUE THREAD

**Issue by WheresHJ** [CityOfBoston/boston.gov#238]
At non-mobile screen sizes, the 'P' in 'Public Notices' is cut off by the logo. See screenshot.

![screen shot 2016-11-29 at 8 55 58 pm](https://cloud.githubusercontent.com/assets/642810/20738073/a6b4c24c-b67e-11e6-811a-e45c81259d3e.png)

**Comment by matthewcrist** [comment]
This is fixed.
