### ISSUE TITLE
See all places / nodes with a specific "feature"

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#24]
Each BYCF has a set of "features" (see screenshot from [this page](https://www.boston.gov/community-centers/bcyf-blackstone)). Those features should be clickable and show all places / nodes with the clicked feature. 

Possibly add this the way someone can filter places in the BYCF search bar. Where does this search live ultimately? 

![screen shot 2016-10-13 at 1 55 13 pm](https://cloud.githubusercontent.com/assets/3886936/19360467/bfdbf6a2-914c-11e6-8024-6d3777a9ceaf.png)

**Comment by hackajesse** [comment]
@asalsman have you seen anything in your investigations into related content that would help create this type of internal navigation?

**Comment by reillyzlab** [comment]
James stopped using these altogether so closing
