### ISSUE TITLE
Bypass login for internal traffic

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#240]
Goal: As an employee (full-time, part-time, contractor, intern, etc.), I would like to have as many barriers to entering the site removed as possible.

Acceptance Criteria:

1. If a user is on a City of Boston network, then the user should not be forced to log into the site except when needing to access sensitive information, such as personnel information and related applications.
2. If a user is not on a City of Boston network, then the user should be forced to log into the site during the very first interaction with site and should be redirected from the Hub URL to the City's log in page.

Success Metric:

1. Users will have their log in experience decreased by one log in session when both on and off a City network.
2. Contractors and interns won't need to request an IDM account purely to access the Hub unless they need access to another Web application.

**Comment by matthewcrist** [comment]
Moving this to the backlog until the City's new network can support.
