### ISSUE TITLE
Public testimony not displaying on public notices

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#241]
The public testimony button under "details" doesn't appear to be doing anything on the [public notices listing page](https://www.boston.gov/public-notices) or on the [public notice itself](https://www.boston.gov/public-notices/11756).

![image](https://cloud.githubusercontent.com/assets/7929556/20803698/1c554dd8-b7be-11e6-87c2-0244b3449ad9.png)

Also, we need an option for this public testimony button where it's not specific to a time. Here's copy you can use for both instances.

No time: "The public can offer testimony."

Time: "Public testimony begins at [time]."

**Comment by matthewcrist** [comment]
This is fixed on production.
