### ISSUE TITLE
Flag on upcoming events broken

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#25]
Flag on upcoming event featured item on iPhone 6 broken and overlaps title text of event.

Boston.gov:
![img_5219](https://cloud.githubusercontent.com/assets/20731897/19360688/7dd5e582-914d-11e6-80f9-dc4c287f8647.jpg)

Hub:
![f124c4fc-7f3e-11e6-8aab-5d5e155bb651](https://cloud.githubusercontent.com/assets/20731897/19360694/82b9c14a-914d-11e6-8151-ff719a52ed4a.png)

**Comment by asalsman** [comment]
Can you link me an example? I did some digging, but a) am still figuring out the content on the sites and b) couldn't find a page like this.
