### ISSUE TITLE
Breadcrumb collides with Last Updated

### ISSUE THREAD

**Issue by asalsman** [CityOfBoston/boston.gov#250]
As an example:
https://www.boston.gov/public-notices/12036

Extremely long page titles used in the breadcrumb are smashing into/overlapping with the Last Updated field on desktop and up.

This may could be a content, design, or technology issue, but I figure folks wiser than me should be the judge.

**Comment by matthewcrist** [comment]
@hackajesse and @sebastianebarb My vote would be to ellipsis the breadcrumb at a sane size. We also need to keep the last updated right aligned. Looks like it moves left at lower widths.

<img width="1004" alt="screen shot 2016-12-06 at 11 11 08 am" src="https://cloud.githubusercontent.com/assets/9234/20933023/bcda9080-bba4-11e6-9919-1adb095ca3e8.png">

**Comment by sebastianebarb** [comment]
I'm on board with that.

**Comment by matthewcrist** [comment]
The updated breadcrumb component will fix this.
