### ISSUE TITLE
Ensure avatar/log out appears even without email

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#255]
Background: If a user does not have an email in HCM, then they do not have the avatar in the header appear.

Goal: As an authenticated user, I want to be able to quickly log out from the Hub.

Acceptance Criteria: For users without an email, there should be a conditional item set so that the avatar still appears and allows a user to log out of the site.

Success Metric: Zero people are contacting the digital team or the Employee Connect Center with questions on how to log out of the site.

**Comment by matthewcrist** [comment]
This is on stg.

**Comment by matthewcrist** [comment]
This is on staging.
