### ISSUE TITLE
Build 'Grid of Cards - Video' component for both Drupal sites

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/boston.gov#257]
The Jobs page, Cable office, MONUM and others are need of a grid of Videos. @reillyzlab do you think could be good for training videos on the Hub? No more then 9 videos should be displayed in the component. On click the video viewer should appear over the component and play the video. 

![grid of videos](https://cloud.githubusercontent.com/assets/20642299/20975410/711ae1b2-bc6d-11e6-8e56-c4a6e592e079.png)

Sketch file
https://drive.google.com/open?id=0B0RwQU94BhGeT2NuSlUzTWt2cFE

**Comment by reillyzlab** [comment]
@sebastianebarb think it's a great idea for Hub too.

**Comment by matthewcrist** [comment]
This should be an enhancement to the grid of cards component. What happens when the video is clicked?

**Comment by reillyzlab** [comment]
We should enable this is a component on boston.gov and Hub using work we did for amazon.boston.gov

**Comment by BrutiAnteneh** [comment]
Related to [#308 Add "Grid of Cards - Video" component to Pattern Library]( https://github.com/CityOfBoston/patterns/issues/308)
