### ISSUE TITLE
Grid of Links with Photos

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/boston.gov#259]
@jduffy2001 Requested a grid of links that allows for a photo to be attached. This would allow for grater visual diversity on the page. This should fallow the same programmatic rules as Grid of Links - D

![grid-of-links-w-photo-1440](https://cloud.githubusercontent.com/assets/20642299/20975927/f052a374-bc6e-11e6-90de-d035cd58bf3e.png)

Sketch file
https://drive.google.com/open?id=0B0RwQU94BhGeT2NuSlUzTWt2cFE

**Comment by matthewcrist** [comment]
Closing as this is grid of cards component now.
