### ISSUE TITLE
Startup instructions?

### ISSUE THREAD

**Issue by hamhands** [CityOfBoston/boston.gov#260]
This is sort of a _meta issue_, but I'd love to see some startup instructons for running boston.gov locally. 

## User story

I'd like to contribute back to boston.gov, but I don't know how to start up locally on my machine. Instructions for starting up a local dev environment once the installation processes are complete would be super helpful!

## Acceptance criteria

1. Be able to access startup instructions in the dev guide
2. Links to any external apps typically used for running locally

**Comment by hamhands** [comment]
@matthewcrist I don't think I can assign issues, so tagging you instead 👍

**Comment by matthewcrist** [comment]
@hamhands I've added a section on setting up Acquia Dev Desktop.

**Comment by hamhands** [comment]
Thanks @matthewcrist! 💯
