### ISSUE TITLE
Bullets broken in text component

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#263]
When you try to use bullets in any public notice, they appear to be broken. Looks like they're pulling in numbers instead of the bullets and adding in the carot from 'lists':

![image](https://cloud.githubusercontent.com/assets/7929556/21011728/8f6306f0-bd20-11e6-85ae-6d672ddb35f1.png)

**Comment by reillyzlab** [comment]
See 1216 on spyglass

**Comment by hackajesse** [comment]
@jduffy2001 How do you feel about [this example page](https://edit.boston.gov/public-notices/13096)?

**Comment by reillyzlab** [comment]
spyglass 1216 may give some insight on how to resolve

**Comment by jduffy2001** [comment]
This issue is only appearing in the "description" section of "discussion topics" in public notices:

![image](https://cloud.githubusercontent.com/assets/7929556/26374699/3e6b712e-3fd4-11e7-99f0-78413b670346.png)

Here's a link for a test notice on production:

https://edit.boston.gov/public-notices/25781

Here's a link on staging:

https://edit-stg.boston.gov/public-notices/25901

**Comment by jimafisk** [comment]
Made the selector more specific so it only styles list items that are direct children of an ordered list. This should allow bullets in a Discussion Topic as well as nested ordered lists:

![updated_discussion_topics](https://user-images.githubusercontent.com/5913244/26947789-f0b1bec6-4c61-11e7-9ed6-9858fdf58a52.png)

**Comment by jimafisk** [comment]
This needs some work: https://github.com/CityOfBoston/boston.gov/pull/717#issuecomment-307455414

**Comment by reillyzlab** [comment]
The indention/sub-numbering works, but restarting number still doesn't work.

https://edit-stg.boston.gov/public-notices/26896

![screen shot 2017-06-14 at 10 05 25 am](https://user-images.githubusercontent.com/20731897/27136343-16cf991c-50e9-11e7-925b-73b9fad6d7c3.png)

![screen shot 2017-06-14 at 10 05 38 am](https://user-images.githubusercontent.com/20731897/27136351-1cb7d2d6-50e9-11e7-847e-52e14b4cdedf.png)
