### ISSUE TITLE
Ensure User Profile Created When Hired

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#269]
**Goal:** As a user I want to be able to sign into the Hub on the first day of work.

**Acceptance Criteria:** As part of our user feed, we need to ensure that users (full-time employees) have a Hub profile set up on the first day that they start.

**Success Metric:** Zero full-time employees report issues with logging into the Hub due to a lack of a profile.

**Comment by matthewcrist** [comment]
@reillyzlab please test this. the HCM job had gotten stuck.

**Comment by reillyzlab** [comment]
Closing b/c resolved. Thank you!
