### ISSUE TITLE
The home nav option on mobile should be up at the top.

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#27]
Deciding whether to keep or ditch still. http://www.webdesignerdepot.com/2015/08/the-ux-case-against-the-home-button/

![mobile-nav](https://cloud.githubusercontent.com/assets/3886936/19360849/39880792-914e-11e6-98d4-91875341069d.PNG)

**Comment by hackajesse** [comment]
Related to #155 - hoping to alleviate this issue completely with a different nav.

**Comment by matthewcrist** [comment]
Closing since home is now closer to the top and the B is home tappable as well.
