### ISSUE TITLE
Add content types to Hub for emergency alert

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#274]
**Goal:** As a site administrator and emergency alert author I would like the ability to add status items and the emergency alert to the Hub.

**Acceptance Criteria:**

1. Status item content type is added to the Hub.
2. Emergency alert content type is added to the Hub.
3. Emergency alert can be added to the Hub on corresponding page types to boston.gov.

**Success Metrics:** Emergency alert used to notify employees of emergency announcements for all of the emergencies in 2017, with a priority on snow emergency announcements.

**Comment by matthewcrist** [comment]
Estimated 3 for getting content type over and 8 for styling

**Comment by reillyzlab** [comment]
Passed
