### ISSUE TITLE
Revise OAM Redirect for Hub - From My Profile to Homepage

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#282]
**Goal:** As a authenticated user, I would like to be redirected to the Hub homepage [not My Profile] after I log in.

**Acceptance Criteria:** When an authenticated user logs into the Hub they are redirected to the Hub homepage rather than the My Profile page.

**Success Metric:** All authenticated traffic gets redirected to the Hub homepage rather than the My Profile page when they log into the Hub.

**Additional Implementation Info:** See spyglass #﻿1526

**Comment by reillyzlab** [comment]
@matthewcrist https://www.drupal.org/project/logintoboggan

**Comment by reillyzlab** [comment]
Other potential work arounds via christina: 

However, that might be overkill for this purpose; you should also check out Login Destination: https://www.drupal.org/project/login_destination . This could also be accomplished through a small code snippet if you're comfortable with that: http://www.jeffgeerling.com/blogs/jeff-geerling/how-redirect-user-after-login . You'd probably want to check out the modules above first, though.

**Comment by matthewcrist** [comment]
This is blocked by being unable to login locally.
