### ISSUE TITLE
As a content author, I want to be able to add related departments to public notices

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#287]
## Acceptance Criteria

\* Content author can add related departments to public notices  
\* Note that these departments are not the primary contact department

\* This should not be a required field

\* Allows for more than one department to be entered

**Comment by asalsman** [comment]
Department field exists. But it is currently a required field. That may be a requirement based on how it was constructed? Before nixxing that part (the required), I want to talk to @matthewcrist

**Comment by asalsman** [comment]
After talking with @hackajesse, we're just going to leave it as is for now.

**Comment by hackajesse** [comment]
Assuming the Department field on the Basic Information tab is able to act as a related content field...
Copy change for this related content item:
"Departments" becomes "Other related departments" (note lower case). 
Help text copy change:
"Which other departments are relevant for this public notice?"
**The field should not be required.**

If the Department field on the Basic Information tab **_cannot_** act as a related content field...
Copy change for this related content item:
"Departments" becomes "All related departments" (note lower case). 
Help text copy change:
"List all departments related to this public notice."
**Make the field required.**

**Comment by reillyzlab** [comment]
Working

**Comment by hackajesse** [comment]
Works on Boston.gov. Closing.
