### ISSUE TITLE
As a content author, I want to be able to add related neighborhoods to public notices.

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#288]
## Acceptance Criteria

\* Content author can add related neighborhoods to public notices  
\* Neighborhoods should be listed as checkboxes

\* Checkboxes should be in two-columns (confirm this is possible)

\* Allows for more than one neighborhood to be entered

**Comment by asalsman** [comment]
We need to talk with @jimafisk and @matthewcrist. I can switch this to places, as we discussed doing across the board, but that will still involve the breakout work that we discussed last week and how to map old data to new data.

**Comment by hackajesse** [comment]
Would like this to be a broken out version of places and neighborhoods, all ultimately being a Places related content. 

Copy for this related content item:
"Related neighborhoods" (note lower case).
Help text copy change:
"Which neighborhoods are relevant for this public notice?"

Can the checkboxes be listed in two columns, alphabetical order descending, top to bottom, left column to right column?

REQUIRED FIELD.

**Comment by jimafisk** [comment]
Related PR: https://github.com/CityOfBoston/boston.gov/pull/392

* Only works for events, need to abstract to Public Notices
* Field label change from "Neighborhoods" to Related neighborhoods"
* Require at least one neighborhood is checked off

**Comment by matthewcrist** [comment]
@asalsman & @jimafisk this should be the same field as events

**Comment by asalsman** [comment]
**Important note:** As this goes to production, Each place that is a neighborhood will need to have the "Is a Neighborhood?" box checked and published.

This box can be found at the bottom of the basic information tab on place profiles.

**Comment by asalsman** [comment]
Because of the current loss of data we'd get out of killing field_multiple_neighborhoods, we are *NOT* moving Public Notices (yet) over to the jim-created places/neighborhood breakout.

**Comment by reillyzlab** [comment]
Can't test this one b/c lack of functionality on Hub

**Comment by hackajesse** [comment]
@jimafisk @asalsman I tested this and it didn't work. That may be expected, but the issue is in Acceptance QA. Should it be? 
cc @matthewcrist
