### ISSUE TITLE
As a content author, I want to be able to add "other related content" to public notices

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#289]
## Acceptance Criteria

\* Content author can add related content that isn't covered in other related content fields to public notices

\* Allows for more than one relation to be entered

\* ~~Do not include How To content type~~

**Comment by hackajesse** [comment]
Copy change for this related content item:
"Related Content" becomes "Other related content" (note lower case).
Help text copy change:
"Which articles, how tos, and / or other content are relevant for this public notice?"

Content types available for this field should only include: Article, How Tos (now included!), Landing Page, and Script Page.

Not required.

**Comment by reillyzlab** [comment]
Working.

Same red text issue as posts 'other related notice' - creating a separate ticket for red text appearing on both

**Comment by hackajesse** [comment]
Works well. Closing.
