### ISSUE TITLE
As a content author, I want to be able to add related guides to public notices

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#290]
## Acceptance Criteria

\* Content author can add related guides to public notices

\* Allows for more than one guide to be entered

**Comment by hackajesse** [comment]
Copy change for this related content item:
"Guides" becomes "Related guides" (note lower case).
Help text copy change:
"Which guides are relevant for this public notice?"
Not required.

**Comment by matthewcrist** [comment]
@asalsman i'm not seeing related guides in staging

**Comment by hackajesse** [comment]
Looks good. Closing.
