### ISSUE TITLE
As a content author, I want to be able to add related programs / initiatives to public notices

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#291]
## Acceptance Criteria

\* Content author can add related programs / initiatives to public notices

\* Allows for more than one program / initiative to be entered

**Comment by hackajesse** [comment]
Copy change for this related content item:
"Programs/Initiatives" becomes "Related programs / initiatives" (note lower case and spacing).
Help text copy change:
"Which programs or initiatives are relevant for this public notice?"
Not required.

**Comment by reillyzlab** [comment]
@hackajesse @matthewcrist can't test because doesn't exist on Hub

**Comment by hackajesse** [comment]
Works well on Boston.gov. Closing.
