### ISSUE TITLE
As a content author, I want to be able to add related posts to public notices

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#292]
## Acceptance Criteria

\* Content author can add related posts to public notices

\* Allows for more than one post to be entered

**Comment by hackajesse** [comment]
Copy change for this related content item:
"Posts" becomes "Related posts" (note lower case).
Help text copy change:
"Which press releases or blog posts are relevant for this public notice?"
Not required.

**Comment by reillyzlab** [comment]
Working

**Comment by hackajesse** [comment]
Looks good on Boston.gov. Closing.
