### ISSUE TITLE
As a content author, I want to be able to add related events or public notices to public notices

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#293]
## Acceptance Criteria

\* Content author can add related events and public notices to public notices  
 \* Both should be add-able from the same field

\* Allows for more than one event and / or public notice to be entered

**Comment by hackajesse** [comment]
Copy change for this related content item:
"Events/Public Notices" becomes "Related events / public notices" (note lower case and spacing).
Help text copy change:
"Which other events or public notices are relevant for this public notice?"
Not required.

**Comment by reillyzlab** [comment]
Events portion is working on Hub but can't test public notice portion

**Comment by hackajesse** [comment]
Both public notices and events work well. Closing.
