### ISSUE TITLE
As a content author, I want to be able to add related places to public notices

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#294]
## Acceptance Criteria

\* Content author can add related places to public notices  
 \* Places only include cemeteries, parks, historic districts, and community centers

\* Allows for more than one place to be entered

**Comment by hackajesse** [comment]
Copy change for this related content item:
"Place" becomes "Related places" (note lower case and plural).
Help text copy change:
"Are any cemeteries, parks, historic districts, or community centers relevant for this public notice?"
Not required.

**Comment by reillyzlab** [comment]
Cosmetically looks updated. Can't test functionality because Hub doesn't have 'places'

**Comment by hackajesse** [comment]
Places (BCYF Charlestown) look good. Couldn't get neighborhoods to work. Separate ticket, though. Closing this issue.
