### ISSUE TITLE
As a content author, I want to be able to add related people to public notices

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#295]
## Acceptance Criteria

\* Content editor can add related people to public notices

\* Allows for more than one person to be entered

**Comment by hackajesse** [comment]
Copy change for this related content item:
"People" becomes "Related people" (note lower case).
Help text copy change:
"Which people are relevant for this public notice?"
Not a required field.

**Comment by reillyzlab** [comment]
@matthewcrist @hackajesse can't fully test functionality on Hub since don't have people profiles, but seems to have cosmetic updates.

**Comment by matthewcrist** [comment]
@reillyzlab can you create a new ticket for the red text and assign to @asalsman?

**Comment by reillyzlab** [comment]
Will do


[image: COB_B_Blue_square-01.png]

Reilly Zlab

Employee Website <http://hub.boston.gov> Product Manager

Department of Innovation & Technology

City of Boston | City Hall Room 703

617-635-0057 (w) | reilly.zlab@boston.gov

**Comment by hackajesse** [comment]
Looks good on Boston.gov. Closing.
