### ISSUE TITLE
Have uploaded images default to "Display as WYSIWYG" when adding them to text component, body

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#3]
The reason is that the "WYSIWYG" option allows a user to add a hyperlink to the image. The default option doesn't allow a user to do that.

Right now, when you add a new image or an image from the library, the "display as" option defaults to "default":
![](https://cloud.githubusercontent.com/assets/7929556/19271217/9c8c8548-8f91-11e6-9ab1-f951d667c925.PNG)

Users should instead have the "display as" default to "WYSIWYG":
![](https://cloud.githubusercontent.com/assets/7929556/19271242/bef7ad1a-8f91-11e6-8e8c-ef273942520d.PNG)

**Comment by matthewcrist** [comment]
@jduffy2001 is this worthwhile? if not, can we close?
