### ISSUE TITLE
Admin portal: Titles of component should always display if available

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#30]
If a title is entered in a component, this title sometimes appears below 'component type' when the component is closed. However, at other times the title does not appear when the component is closed.

The title should appear for components that have a title listed.

![title example](https://cloud.githubusercontent.com/assets/20731897/18678364/c861b562-7f29-11e6-99f7-638a3e9ed67d.PNG)

Components where title does not appear and should:
1. Video
2. FYI
3. Hero Image
4. User Action
5. Cabinet
6. Transaction grid

**Comment by asalsman** [comment]
The issue here is that some components (the ones listed) are pulling from field_title to populate the title field.

The ones not listed are pulling from field_component_title. The admin view rendering pulls from field_component_title to make this visible.

Will do some testing to see what can be done without losing data.

**Comment by asalsman** [comment]
When this gets picked back up/prioritized, my assessment is that field_component_title should be set to field_title if field_component_title doesn't exist in docroot/sites/all/themes/custom/boston/template.php -> boston_preprocess_paragraphs_item_video

That way we don't break the ones that have it being done "correctly" and we don't force users to double input title on the ones that aren't configured properly. All while being transparent to the users.

**Comment by reillyzlab** [comment]
Would like to look at this again, but disregard if high LOE

**Comment by reillyzlab** [comment]
Good on boston.gov.

Moving to test on Hub
