### ISSUE TITLE
As a content author, I want to be able to add related departments to posts

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#305]
## Acceptance Criteria

\* Content author can add related departments to posts  
\* Note that these departments are not the primary contact department

\* This should not be a required field

\* Allows for more than one department to be entered

**Comment by hackajesse** [comment]
Assuming the Contact field on the Basic Information tab is able to act as a related content field...
Copy change for this related content item:
"Departments" becomes "Other related departments" (note lower case).
Help text copy change:
"Which other departments are relevant for this post?"
**The field should not be required.**

If the Contact field on the Basic Information tab **_cannot_** act as a related content field...
Copy change for this related content item:
"Departments" becomes "All related departments" (note lower case).
Help text copy change:
"List all departments related to this post."
**Make the field required.**

**Comment by reillyzlab** [comment]
@matthewcrist @hackajesse 

Two issues (described below and in seen in added image):

1. Adds a white line break 
2. Puts 'TBD:' as the title (which gets auto added in via code and cannot be manually change). Should say 'Who's Involved'

![testing 305](https://cloud.githubusercontent.com/assets/20731897/22519589/d28b6f1a-e87e-11e6-9041-1bfd6e15625b.PNG)

See example on: https://hub.boston.gov/node/3426/draft

**Comment by hackajesse** [comment]
@asalsman I get the TBD on Boston.gov, too.
I don't get the line break, however.
Keeping this open for the moment.

**Comment by hackajesse** [comment]
The related part of this ticket works well, though. Ref #436 for the hotfix. Closing. @reillyzlab will you add the line break ticket?
