### ISSUE TITLE
As a content author, I want to be able to add related guides to posts

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#308]
## Acceptance Criteria

\* Content author can add related guides to posts

\* Allows for more than one guide to be entered

**Comment by hackajesse** [comment]
Copy change for this related content item:
"Guides" becomes "Related guides" (note lower case).
Help text copy change:
"Which guides are relevant for this post?"
Not required.

**Comment by matthewcrist** [comment]
@asalsman i'm not seeing related guides on posts

**Comment by reillyzlab** [comment]
Appears to be working for me

**Comment by hackajesse** [comment]
Works for me! Closing.
