### ISSUE TITLE
As a content author, I want to be able to add related posts to posts

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#310]
## Acceptance Criteria

\* Content author can add related posts to posts

\* Allows for more than one post to be entered

**Comment by hackajesse** [comment]
Copy change for this related content item:
"Posts" becomes "Related posts" (note lower case).
Help text copy change:
"Which other press releases or blog posts are relevant for this post?"
Not required.

**Comment by reillyzlab** [comment]
Working on Hub

**Comment by hackajesse** [comment]
Works on Boston.gov. Closing.
