### ISSUE TITLE
As a content author, I want to be able to add related events or public notices to posts

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#311]
## Acceptance Criteria

\* Content author can add related events and public notices to posts  
 \* Both should be add-able from the same field

\* Allows for more than one event and / or public notice to be entered

**Comment by hackajesse** [comment]
Copy change for this related content item:
"Events/Public Notices" becomes "Related events / public notices" (note lower case and spacing).
Help text copy change:
"Which other events or public notices are relevant for this post?"
Not required.

**Comment by reillyzlab** [comment]
@matthewcrist @hackajesse Appears to be working but can't fully test because don't have public notice

**Comment by hackajesse** [comment]
Works on boston.gov. Closing.
