### ISSUE TITLE
As a content author, I want to be able to add related places to posts

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#312]
## Acceptance Criteria

\* Content author can add related places to posts  
 \* Places only include cemeteries, parks, historic districts, and community centers

\* Allows for more than one place to be entered

**Comment by hackajesse** [comment]
Copy change for this related content item:
"Places" becomes "Related places" (note lower case).
Help text copy change:
"Are any cemeteries, parks, historic districts, or community centers relevant for this post?"
Not required.

**Comment by matthewcrist** [comment]
@asalsman this should use the places / neighborhoods field from @jimafisk

**Comment by asalsman** [comment]
Important note: As this goes to production, Each place that is a neighborhood will need to have the "Is a Neighborhood?" box checked and published.

This box can be found at the bottom of the basic information tab on place profiles.

**Comment by hackajesse** [comment]
Looks good. Closing.
