### ISSUE TITLE
As a content author, I want to be able to add related people to posts

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#313]
## Acceptance Criteria

\* Content editor can add related people to events

\* Allows for more than one person to be entered

**Comment by hackajesse** [comment]
Copy change for this related content item:
"People" becomes "Related people" (note lower case).
Help text copy change:
"Which people are relevant for this post?"
Not a required field.

**Comment by reillyzlab** [comment]
can't test because people profile doesn't exist on Hub

**Comment by hackajesse** [comment]
Looks good on Boston.gov. Closing.
