### ISSUE TITLE
As a website viewer, I want to be able to see public notices related to specific content in that content's Upcoming Events component.

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#315]
Acceptance Criteria:

- When I tag a field in Related Content on a public notice or event content type, it should display in the {UPCOMING\_EVENTS} component of the associated node, assuming a content creator has already created such a component on that node.
- Cards are mobile responsive
- It's possible for a featured item to be either a public notice or an event
- If a featured item is a public notice, the call to action button should read "Notice details"
- If a featured item is an event, the call to action button should read "Event details"
- Featured items should not appear among the smaller cards (ref #117)
- Small cards should order date descending. Meaning a set of events / public notices happening December 8, 13, 20, and 30 should order: Top Left (TL) = 8; TR = 13; BL = 20; BR = 30.
- Public notices and events should have the same hover-over states as the existing events component (different colors for Hub vs Boston.gov - keep consistent within each brand). 
- Public notices should automatically display the icon Sebastian attached in a comment below.
- The "See all" button generates from the events component and is user-defined. Don't modify.

Comp for how this looks in an events component. Note the small card and the featured card show two different instances of a public notice card in the events component.

![public notices hero](https://cloud.githubusercontent.com/assets/20642299/20630836/76830672-b301-11e6-9517-1cb2783210a5.png)

**Comment by sebastianebarb** [comment]
https://drive.google.com/open?id=0B0RwQU94BhGeU3BOUVE3UEtibk0 @hackajesse

**Comment by hackajesse** [comment]
Duplicate of #334. Closing.
