### ISSUE TITLE
Secondary navigation on initiative/profile pages and department pages

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#322]
We need secondary navigation on initiative/profile and department page content types. Ideally, they'd mirror what [we did for article pages](boston.gov/cold). We also have secondary navigation [on our guide pages](https://www.boston.gov/guides).

**Comment by jduffy2001** [comment]
Could also see this being useful on posts.

**Comment by reillyzlab** [comment]
Program/initiative page, secondary navigation doesn't show up accurately as user scrolls down page. See here:

![screen shot 2017-02-15 at 11 51 21 pm](https://cloud.githubusercontent.com/assets/20731897/23008033/a8be2f08-f3da-11e6-8d57-dc03b1acd879.png)

![screen shot 2017-02-15 at 11 51 30 pm](https://cloud.githubusercontent.com/assets/20731897/23008036/b3c1ec64-f3da-11e6-98b7-7392f9d24f97.png)

https://edit-stg.boston.gov/innovation-and-technology/2017-analytics-summer-fellowships#frequently-asked-questions

**Comment by matthewcrist** [comment]
This is a logged in header issue.
