### ISSUE TITLE
Be able to change background color on components

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#33]
And have all other styles in that component adjust accordingly when background color is changed.

@sebastianebarb:
- What should the color / style combos be for each background color option?
- Which components can be which colors. Should every component be able to have any theme?

Also, the sooner the better on getting this issue ready, so @matthewcrist can work it in with the other component changes. 

Due by end of October reasonable?

**Comment by sebastianebarb** [comment]
@hackajesse Color combos can be pulled from current components. (see attachments)

- Text, right now, events and gird of people components should always be white or light grey background 
- News, Transaction grig, Grid of links, Grid of quotes, grid of departments should be able to have dark blue, white or light grey background.

![grid-of-topics-1440](https://cloud.githubusercontent.com/assets/20642299/20534495/6953c422-b0af-11e6-9184-441033a649a6.png)
![grid-of-links-a-1440](https://cloud.githubusercontent.com/assets/20642299/20534494/6952b276-b0af-11e6-9b25-4887bd9c4a86.png)
![grid-of-quotes-1440](https://cloud.githubusercontent.com/assets/20642299/20534496/6954e186-b0af-11e6-917f-08354e1edf54.png)

**Comment by reillyzlab** [comment]
Working on as one-one-one/systematically as we re-factor components.

Will work on separating into individual tickets by component.
