### ISSUE TITLE
Live stream video doesn't count down

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#332]
Video live stream components do not show the countdown to the live stream event start time. They only show the Play button, which doesn't (and shouldn't) function prior to the live stream start time.

**Comment by asalsman** [comment]
I see this properly on edit-stg. Passing to @hackajesse

**Comment by hackajesse** [comment]
Looks good. Cleared for production.

**Comment by hackajesse** [comment]
@matthewcrist this is good on staging. Assigning to you for the prod push.
