### ISSUE TITLE
Be able to see "related" or "more" posts at the bottom of a post.

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#35]
@sebastianebarb I'd like to have these comps queued up before the end of November. Happy to discuss beforehand and include @jduffy2001. 

From a constituent: "I mean like, "Next up: Mayor Walsh Pets Kittens at the Angel MSPCA". I'd click the hell out of that."

Comments:
@sebastianebarb What should this look like? Happy to chat, but this one will need a comp for desktop, tablet, and mobile.

@hackajesse I wonder if a better idea would be an infinite scroll for posts. Fusion.net just keeps going with related content so you don't need to click. It makes me want to read the next article, I often do.
http://fusion.net/story/340171/how-nextdoor-reduced-racial-profiling/

@sebastianebarb while super cool (nice link!), we're going to skip infinite scroll at this point b/c of accessibility / usability for some folks. [Read why](http://www.webaxe.org/infinite-scrolling-and-accessibility/)

Ideas for a "next post" or "related posts" concept to give people relevant content? Perhaps along the lines of a click-bait site like [this one](http://womens24x7.com/top-10-celebrities-that-married-ordinary-people/)?

**Comment by sebastianebarb** [comment]
https://drive.google.com/open?id=0B0RwQU94BhGeNGVNNDREVEVZMnc
![upnext](https://cloud.githubusercontent.com/assets/20642299/20500788/ed119e20-b004-11e6-9884-b065f150db00.png)

**Comment by hackajesse** [comment]
"Up Next" might be generated by the "news tags" in the CMS. Ref #220
