### ISSUE TITLE
Users with Google Image Don't Have Image or Avatar Appear

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#353]
**Goal:**

As an authenticated user, I want to see my Google image appear if I have one entered into Google. If I do not have a Google image, then the general avatar should appaer.

**Background:**

There is a bug so that some people who do have a Google image don't see their image come through. However, when this happens the general avatar does not appear and the area where the user image/avatar should be is blank making it hard to locate where 'sign out' link is located.

Different specific scenarios:

- Fixed for user 099497 by refreshing heroku
- Could not resolve by refreshing heroku for user 050324
- User 142208 has a Google image but within accompanying herkou URL unique identifier for image the field is blank. Because the field is blank the general avatar is still appearing.

**Metrics for success:**

No users report not being able to find the sign out button because of a missing icon.

**Comment by matthewcrist** [comment]
@reillyzlab assuming we can close this now?
