### ISSUE TITLE
Make featured public notices disappear after they happen (on events component)

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#361]
As a website viewer, I shouldn't see a featured public notice on an events component duplicated among the non-featured event cards. 

As a website viewer, I shouldn't see a featured public notice in the events component if the day of that event has passed.

- [ ] A content author can make a public notice featured on an Events component
- [ ] A content author can remove a public notice from being featured on an Events component
- [ ] A website viewer can see a public notice as "featured" (large format card) on an Events component
- [ ] A website viewer only sees a public notice shown once in an Events component, even if that public notice is featured.
- [ ] A featured public notice automatically disappears 6 hours after it starts.

**Comment by hackajesse** [comment]
Need to add when the card disappears.

**Comment by asalsman** [comment]
BTW: Once issue #334, the deduping functionality will be available.

**Comment by asalsman** [comment]
Just finished testing. Everything works as expected, based on reqs in this issue.

**Comment by hackajesse** [comment]
This works, but there may be a bug. Hondo is investigating before we move forward.

**Comment by hackajesse** [comment]
Looks good - @matthewcrist spent some time investigating and decided whatever's happening isn't clear enough to postpone the build. Moving forward and closing this issue.
