### ISSUE TITLE
iframe failure error message

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#375]
I am a user and would like to see an error message if an iframed form is down to help me know what is going on.

Earlier this week SeamlessDocs went down, and all of our forms site-wide broke. This left a bunch of pages with just a header. It would be great if we could have an automatically generated error message when this happens. As we embed other things, like Salesforce, directly into the site we should also consider broken states for those as well. 

Here's an example script page -- I can ask SeamlessDocs to break it intentionally if that would help. 

https://www.boston.gov/appeal-green-ticket-requesting-hearing

**Comment by reillyzlab** [comment]
@jduffy2001 can you help craft/draft a message for this?

**Comment by jduffy2001** [comment]
We're having trouble with our forms at this time, so we can't process your request. We're working to address the issue, though, and will update this page as soon as we have a fix.

If you have any questions or concerns, please email feedback@boston.gov.

**Comment by jduffy2001** [comment]
@joshuagee @reillyzlab See the sample text above. Not sure what the length should be, but I think that works.

**Comment by matthewcrist** [comment]
Put in a ticket for Sebastian to come up with a style for in place errors. It's this issue: 

https://github.com/CityOfBoston/design-team-workflow/issues/262

**Comment by matthewcrist** [comment]
This is on production.
