### ISSUE TITLE
Create grid of cards component

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/boston.gov#381]
Content creators need to be able to create a grid of cards component. This component should be based off of the current grid of places component. 

- [x] Content creators can add grid of cards component to any content type that accepts components
- [x] Content creator can add any number of cards to the component
- [x] Content creator can add title (optional), short title (required), and contact (optional) to component
- [x] Each card should consist of a title, image, description, and a link (internal, external, document)
- [x] This component is enabled on Hub and Boston.gov
- [x] Card design should follow the design of programs / initiatives here: 

<img width="412" alt="screen shot 2017-01-18 at 10 00 55 am" src="https://cloud.githubusercontent.com/assets/9234/22069046/17d12abc-dd65-11e6-8cf4-0d0236590107.png">

## Acceptance Criteria

 * Content creators can create a grid of cards
 * Users can view published grid of cards

**Comment by hackajesse** [comment]
Closing. Replaced by #396
