### ISSUE TITLE
Events Disappear on Events Component Upon Start of Event Date/Time

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#391]
**Goal:** As an anonymous user, I would like to view events that are upcoming or have just recently started.

**Acceptance Criteria:** Logic that exists for public notices is replicated so that display timing for events on events component stay present for a short while after the begin.

**Background:** Non-featured events disappear from the events component as soon as the event date/time begins.

**Metrics for Success:** Events don't disappear from the events component until specified time passes.

**Comment by reillyzlab** [comment]
@matthewcrist james mentioned that you all implemented something along the lines for this for public notices so that's why the above is written how it is written. Tried searching for a previous ticket to create a better informed ticket from the onset but couldn't find. Happy to edit the ticket if you can direct me to a relevant ticket, or if you can just provide more info in general.

**Comment by asalsman** [comment]
Public Notices are currently staying around for 3hrs past start time, so I will make Events do the same.
