### ISSUE TITLE
Bring tabbed-content content type over from Hub

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#395]
Content creators should be able to create tabbed content pages. This should work just like tabbed content pages in The Hub.

- [x] Use Boston.gov How To content type coloring
    Instead of the existing Hub coloring
    
- [x] Content type should be able to have any type of component added to it
- [x] Content type should not have a related content field
- [x] Content type should have the same sidebar components options as the existing How To content type
    Note that this is just the left nav tab called Sidebar Components, not Sidebar Info.
    
- [x] Left nav tab called "Tabs" should be required
- [x] In each Tab under "Tabs" in the left nav, make Title required

**Comment by hackajesse** [comment]
@jimafisk let's talk about this with @matthewcrist next time you're in

**Comment by matthewcrist** [comment]
Do we still want this? For now, @jimafisk should probably back out the change and we move this to the backlog.

**Comment by matthewcrist** [comment]
Talked to @hackajesse. We're just closing this.
