### ISSUE TITLE
Create "Grid of Cards" component

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#396]
As a content creator, I want to have a component that displays an image and summary content and links off to other pages.

Tip: Use the "group of links - grid" component as a model for a component that doesn't use views.

Acceptance criteria are the checkbox requirements below:

- [x] Content creators can add grid of cards component to any content type that accepts components
- [x] Content creator can add any number of cards to the component
- [ ] Content creator can add title (required), hide title field, short title, and contact (optional) to component. (Edit the paragraph bundle fields to mimic the component "Text component" under the section called "text information". Do not include the background image.) 
- [ ] Each card should consist of a title (required), image (required), description (required), and (required) an internal, external, or document link. (Internal/external/document linking is the same as a "grid link" in a "group of links - grid" component.)
- [ ] This component is enabled on Hub and Boston.gov
- [ ] Component / Card design is themed to follow the design of programs / initiatives
    [https://drive.google.com/open?id=0B0RwQU94BhGeT2NuSlUzTWt2cFE](https://drive.google.com/open?id=0B0RwQU94BhGeT2NuSlUzTWt2cFE)
    
- [ ] On mouse-over, each card changes color just like current programs / initiatives cards
- [ ] Website viewers can view and click on a published grid of cards

**Comment by reillyzlab** [comment]
This is the only 'short title' that is required across the site. Is there a reason this is required?

**Comment by hackajesse** [comment]
Revision - confirming short title not required.

**Comment by matthewcrist** [comment]
Moving to the backlog for now.

**Comment by hackajesse** [comment]
@matthewcrist added this to "ready" for today's PM sync.

**Comment by matthewcrist** [comment]
## Testing steps

- Add grid of card to an article (currently only enabled on articles. #585 should fix that)
- Verify that component displays properly
- Go to places listing
- Verify that cards display properly
- Go to programs listing
- Verify that cards display properly
- Add grid of places to any page
- Verify that component displays properly
- Add grid of programs to any page
- Verify that component displays properly

**Comment by reillyzlab** [comment]
@jduffy2001 can you check this on 4/24 to test usage of the component before it goes to production?

**Comment by reillyzlab** [comment]
Few issues on boston.gov:

1. https://github.com/CityOfBoston/boston.gov/issues/591

and 

2. https://github.com/CityOfBoston/boston.gov/issues/592

--
Not showing up as available component [event on article pages] on Hub

**Comment by jduffy2001** [comment]
I noticed a few things, [tested on this page](https://edit-stg.boston.gov/departments/public-works/my-article-page):

1. The short title field for "grid of cards" doesn't create secondary navigation at the top of the page.

2. Feels like we should offer guidance on what size the image will appear. Like, "This image will appear as a 350 x 190 pixel banner."

3. Can we have the cut off for the text be the same as where it will cut off live on the site? It looks like the "short description" is off:
![image](https://cloud.githubusercontent.com/assets/7929556/25390077/7a669a68-29a0-11e7-995f-8980f6371f65.png)
![image](https://cloud.githubusercontent.com/assets/7929556/25390113/91ec570e-29a0-11e7-9968-08df3c25d0de.png)

4. Should the sub-title for "grid of places" mirror what we're doing for "grid of cards", with the capitalized, montserrat font?
![image](https://cloud.githubusercontent.com/assets/7929556/25390396/6e1ca8a0-29a1-11e7-866a-af6beee45b07.png)
![image](https://cloud.githubusercontent.com/assets/7929556/25390435/82e86c10-29a1-11e7-9ae3-b9a1d0cf2c8e.png)

**Comment by matthewcrist** [comment]
Closing this as it's on production. Please log any new issues as separate issues.
