### ISSUE TITLE
Character limit title and intro text on posts and events content types

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#4]
As a CMS user, I shouldn't be able to make my title or intro copy look bad. 

Accordingly, we're going to try a character limit in the CMS to see the reaction and whether people are able to adapt to the new limits.

Status quo:
The title and the intro text both get cut off on the news page. The title and intro text gets cut off on an event only in the upcoming events component.

On staging, it looks like 93 characters are available in the title before getting cut off; 100 characters in the intro text. 

What are the options for a UI for limiting characters? Red outline highlight overlay in the WYSIWYG field? Inability to type any more characters with an error validation?

**Comment by hackajesse** [comment]
@matthewcrist that looks great, actually. Moving to ready. Would apply to events and posts content types since those have truncated components showcasing cards of information. 

@jduffy2001:
Do you think we can restrict title / intro length for public notices?
Should this restriction of title / intro content apply to articles or other content types?

**Comment by reillyzlab** [comment]
@hackajesse do you have an example of where this is happening that we can quickly reference?

**Comment by reillyzlab** [comment]
Closely to potentially revisit later
