### ISSUE TITLE
Spacing issue on smaller mobile devices for public notices

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#403]
We noticed an issue where the title of the fields is hovering over the text on the [public notices page](https://www.boston.gov/public-notices).

![image](https://cloud.githubusercontent.com/assets/7929556/22253170/8ffd97e2-e21e-11e6-956d-be9c004bcba6.png)

The screen shot is from an iPhone SE device. Screen size for this device is 1136 x 640.

**Comment by matthewcrist** [comment]
This is fixed on production.
