### ISSUE TITLE
Public testimony getting automatically pulled onto Digital Board

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#424]
It appears that the public testimony info is getting pulled over to the board on the first floor at City Hall even when the box isn't checked. The three events here all don't have the public testimony option checked:

![image](https://cloud.githubusercontent.com/assets/7929556/22388627/5fb89738-e4af-11e6-977a-58e5d15801fe.png)

Here are the corresponding notices:

https://www.boston.gov/public-notices/15066 
https://www.boston.gov/public-notices/14971
https://www.boston.gov/public-notices/15091

I assume whatever default time is showing up in the public testimony section is what's appearing in the Digital Board.

**Comment by matthewcrist** [comment]
This is fixed. When the board restarts, it'll update.
