### ISSUE TITLE
Add click to call feature for contact information

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#426]
By default, the phone numbers added to contact fields should be click to call on mobile devices. It would be great if any number we add to the website automatically becomes click to call.

Currrently looks like this on mobile devices:

![image](https://cloud.githubusercontent.com/assets/7929556/22434288/72327fb4-e6e9-11e6-9204-d5c02e82d368.png)

**Comment by reillyzlab** [comment]
All set on the Hub.

**Comment by hackajesse** [comment]
Works on Boston.gov. Closing.
