### ISSUE TITLE
"Posts" view for Upcoming Events mislabelled as "Events"

### ISSUE THREAD

**Issue by asalsman** [CityOfBoston/boston.gov#437]
Post-launch bug, but the view for upcoming events "Posts" says "events" instead. Quick fix.

**Comment by hackajesse** [comment]
@matthewcrist I don't see this on staging. Looked at the views on an upcoming events component and still see two views labeled "upcoming_events - Events". Moving back to In Progress.

**Comment by jimafisk** [comment]
This should be all set with the changes introduced in PR #609. We removed all these displays and created a new View called Related Events.

**Comment by matthewcrist** [comment]
All set.
