### ISSUE TITLE
Drop down words on updated 'other related content' are red

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#438]
Background: All drop down words on the updated 'other related content' are red on posts, public notices, and events.

Goal: To match the coloring of the other drop downs, which are black

Acceptance Criteria:

- All of the red words are converted to black.
- We have ensured that the red words appearing not mean an error or bug of sorts.

**Comment by reillyzlab** [comment]
![testing 305](https://cloud.githubusercontent.com/assets/20731897/22530437/7c1ebf1c-e8a9-11e6-8f1c-8283e6bfac12.PNG)

**Comment by reillyzlab** [comment]
![img_5840](https://cloud.githubusercontent.com/assets/20731897/22530442/822c5fe0-e8a9-11e6-8306-58cf7c243d79.JPG)

**Comment by asalsman** [comment]
Addressed in PR #414

**Comment by hackajesse** [comment]
Looks good on Boston.gov.

**Comment by reillyzlab** [comment]
All set on Hub too. Closing.
