### ISSUE TITLE
Components should all have a short title field

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#439]
**Goal:** To support secondary navigation by ensuring that all components include a 'short title' field.

**Acceptance Criteria:**

- Secondary title field needs to be added to the following components:
  - [ ] Featured Guides
  - [ ] FYI
  - [ ] User Action
  - [ ] Hero Image
  - [ ] iFrame
  - [ ] News and Announcements
  - [ ] Upcoming Events

- The following helper text about short title should be added to all of the following components: "The short title is used to populate the in-page navigation. Please keep it short: one to three words is ideal. Example can be found on boston.gov/winter/."
  - Components that are getting short title for the first time:
    - [ ] Featured Guides
    - [ ] FYI
    - [ ] User Action
    - [ ] Hero Image
    - [ ] iFrame
    - [ ] News and Announcements
    - [ ] Upcoming Events

  - Components that already have a short title, but need the helper text:
    - [ ] Three Column
    - [ ] Drawers
    - [ ] Grid of Guides
    - [ ] Group of Links - Grid
    - [ ] Grid of Quotes
    - [ ] Group of Links - List
    - [ ] Group of Links - Mini Grid
    - [ ] List
    - [ ] Photo
    - [ ] Text
    - [ ] Transaction Grid
    - [ ] Video
    - [ ] Grid of Cards

- Short title should never be required.

**Metric for Success:** Content contributors can efficiently use the secondary navigation on boston.gov and the Hub.

**Additional Work Involved (non-dev.):** Edit the content author and site administrator handbooks.

**Comment by reillyzlab** [comment]
@matthewcrist @hackajesse @jduffy2001 Questions I still have:

1. @jduffy2001 can you advise on helper/descriptive text? (none of the short titles have and probably should)
2. Should this be on every component? (I don't see why not but happy to talk it through)
3. Should this be required? I lean towards no, but see that it is for grid of cards [new] and am wondering why?

**Comment by reillyzlab** [comment]
Should think through better title in general

**Comment by matthewcrist** [comment]
Since this involves all components, there will be a lot of regression testing needed.

**Comment by matthewcrist** [comment]
Ready on staging.

**Comment by jduffy2001** [comment]
FYI Component
hero image
Video component

**Comment by reillyzlab** [comment]
Few issues:

- [ ] https://github.com/CityOfBoston/boston.gov/issues/634

- [ ] https://github.com/CityOfBoston/boston.gov/issues/635

We may want to hold off on pushing to production until resolved. James and I are on board to do this.

**Comment by matthewcrist** [comment]
@reillyzlab #635 is still open, but this can be closed.
