### ISSUE TITLE
Hide 'public notice' content type from Hub

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#440]
Please remove public notice content type from Hub, because there is not a use case for the Hub and don't want to: 

1. Confuse content contributors

2. Cause issues with related content/required fields and inability to save on Hub

**Comment by matthewcrist** [comment]
We shouldn't remove it, but rather just change the permissions for content creators to not see it. Removing causes extra complexities that we don't need.

**Comment by hackajesse** [comment]
@matthewcrist Public notices don't show up on Boston.gov staging anymore... moving this back to In Progress.

**Comment by matthewcrist** [comment]
@hackajesse they're there for me.

**Comment by hackajesse** [comment]
Weird @matthewcrist - they're there for me now. All good then. Closing.
