### ISSUE TITLE
Related content "Neighborhoods" field and checkboxes appear in Posts

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#442]
Only the checkboxes for neighborhoods should appear, not the neighborhoods field. The screenshot below shows that both are present. Ref  #306 and #392 

Example node on staging: 11561

![neighborhoods-posts](https://cloud.githubusercontent.com/assets/3886936/22554356/bf01757a-e92d-11e6-9f09-294f5900847f.PNG)

**Comment by asalsman** [comment]
Addressed in PR #414

**Comment by hackajesse** [comment]
Not quite right. Neighborhoods as a related content field now appears above the sidebar tabs (per the screenshot below) when creating a post. It shouldn't be present at all. Moving back to In Progress.

![post-neighborhoods-related-content](https://cloud.githubusercontent.com/assets/3886936/22695126/a3cd561e-ed17-11e6-94b2-80e56f2bc26e.PNG)

**Comment by matthewcrist** [comment]
## Testing steps

- Goto post
- Verify that neighborhoods doesn't appear out of place

**Comment by reillyzlab** [comment]
Still showing up on Hub. Okay on boston.gov

**Comment by matthewcrist** [comment]
Helps if I actually deploy The Hub @reillyzlab. Try now.

**Comment by reillyzlab** [comment]
@matthewcrist still on staging on Hub

**Comment by matthewcrist** [comment]
This is gone on prod @reillyzlab.

**Comment by reillyzlab** [comment]
Showing up on prod. on Hub again.

**Comment by jimafisk** [comment]
I cannot reproduce this issue locally or on stg for Boston or Hub. @reillyzlab was this taken care of?

**Comment by matthewcrist** [comment]
This is fixed.
