### ISSUE TITLE
Calendar thumbnail image icon not appearing on events

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#457]
Calendar thumbnail image not appearing when no thumbnail image is used in an event on the Hub.

James reports not seeing this issue on boston.gov.

Please ensure the attached file shows up on thumbnail for events when no thumbnail entered.

**Comment by reillyzlab** [comment]
@sebastianebarb is providing icon to input.

**Comment by reillyzlab** [comment]
New icon to use: 
![experiential icons 3_calendar_aqua](https://cloud.githubusercontent.com/assets/20731897/22655870/88af610a-ec5f-11e6-8509-d216ea0ef912.png)

**Comment by jimafisk** [comment]
CI is still failing, but PR #629 should fix this issue. Screenshot from local build:

![fixed_default_images](https://cloud.githubusercontent.com/assets/5913244/25674635/9355a414-3009-11e7-9c8d-9f4d5e9af401.png)

**Comment by reillyzlab** [comment]
Blocked from testing until this is resolved:

https://github.com/CityOfBoston/boston.gov/issues/526

**Comment by matthewcrist** [comment]
@jimafisk this is using the wrong image. it should match the optimistic-blue of the hub.

**Comment by jimafisk** [comment]
New Image:
![88af610a-ec5f-11e6-8509-d216ea0ef912_new](https://cloud.githubusercontent.com/assets/5913244/26213111/d6e86514-3bc5-11e7-9ee0-b63644c12d36.png)

Old Image:
![88af610a-ec5f-11e6-8509-d216ea0ef912](https://cloud.githubusercontent.com/assets/5913244/26213119/ddc13014-3bc5-11e7-94db-4607c10456c3.png)

Based on Optimistic Blue:
![optimistic_blue](https://cloud.githubusercontent.com/assets/5913244/26213133/eaa4bc4c-3bc5-11e7-9eba-f1571205638d.png)

Updated on PR #683
