### ISSUE TITLE
TBD: appears as title for 'related depts.' on posts

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#458]
TBD: appearing as the title of 'related departments' on posts on boston Hub and boston.gov.

Believe this is hard coded and needs to be changed by developer.

TBD: should read the following instead: Who's Involved:

See here: https://www.boston.gov/news/mayor-walsh-announces-2017-love-your-block-initiative

**Comment by reillyzlab** [comment]
![tbd on posts](https://cloud.githubusercontent.com/assets/20731897/22655948/c7bbf1ec-ec5f-11e6-8f83-03f807f6b949.PNG)

**Comment by hackajesse** [comment]
This may be a dupe of #436 . @matthewcrist ? If so, label duplicate and close please.
