### ISSUE TITLE
Breadcrumbs should look like links

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#461]
## User story

Breadcrumbs are a way for people to figure out where they are in relation to the rest of the content on the website. However, our breadcrumbs don't look like the rest of the links on the site (aka they're not blue). We should be consistent with how we designate a hyperlink so people can know what is clickable and what isn't. See the comp below for how breadcrumbs should appear.

## Acceptance criteria

1. Breadcrumbs designating a page other than the current page should be optimistic blue.  
2. Breadcrumbs designating the current page should be freedom trail red.  
3. On hover-over, a breadcrumb hyperlink should become underlined. 
4. On hover-over, an optimistic blue hyperlink should turn to freedom trail red. The freedom trail red hyperlink should not change color.
5. All breadcrumbs should be clickable (maintain status quo).

## Success metric

- people click the breadcrumbs to navigate away from a page more frequently than the top or hidden navigation

![breadcrumbs-re-coloring](https://cloud.githubusercontent.com/assets/3886936/22674502/32383d34-ecae-11e6-9534-5a92c0f63072.png)

**Comment by reillyzlab** [comment]
Or aqua for Hub where optimistic blue is mentioned above.

**Comment by reillyzlab** [comment]
@hackajesse Is there a reason we're adding an underline on hover state to these links when none of our other links get underlines on hover state (if we're trying to be consistent with what links/hover state look like)?

**Comment by matthewcrist** [comment]
This is ready on stage. I've not added the underline for consistency.
