### ISSUE TITLE
Connect Swiftype to Google Analytics

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#462]
Instructions: 

[https://swiftype.com/documentation/tutorials/ga](https://swiftype.com/documentation/tutorials/ga)

**Comment by matthewcrist** [comment]
This data is appearing in GA now.

**Comment by reillyzlab** [comment]
@matthewcrist where is this showing? I'm not seeing anything in site search.

**Comment by matthewcrist** [comment]
https://analytics.google.com/analytics/web/#report/content-pages/a2187282w108307691p112911200/%3Fexplorer-table.filter%3Dquery%26explorer-table.plotKeys%3D%5B%5D/

**Comment by matthewcrist** [comment]
@reillyzlab I setup Search.Boston.Gov as it's own property and hooked up the site search feature. It should start to show up in a couple days.
