### ISSUE TITLE
Public notices screen: canceled throws in 'undefined' text

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#464]
On the public notices screen on the first floor of City Hall, when an event is cancelled the screen shows the words 'undefinedcanceled'. The screen should only show 'canceled'.

Doesn't appear to be an issues on boston.gov website

**Comment by reillyzlab** [comment]
![image uploaded from ios](https://cloud.githubusercontent.com/assets/20731897/22762926/ec95cb2e-ee2f-11e6-85a8-b2336f1d83e6.jpg)

**Comment by matthewcrist** [comment]
@reillyzlab can you move this to the @CityOfBoston/notice-signage repo?

**Comment by reillyzlab** [comment]
Yep - on it
