### ISSUE TITLE
Event cost field needs validation

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#467]
Per #183 

##User story

It's great that when an event creator enters an event price into the Cost field on the Event content type, the numbers display. If they don't enter anything, the price defaults to "Free". However, if the event creator doesn't use ```$```, the number shows up as entered. Aka if you type 9,000 instead of $9,000, you get 9,000. 

##Acceptance criteria

 - [ ] If an event creator enters a number into the cost field on an event content type, that number displays with a single dollar sign ($) before the number.
 - [ ] If an event creator enters a number 1,000 or greater into the cost field on an event content type, that number adds a comma at every 3 digit interval to the left of the decimal. (aka 1,000  10,000 or 100,000)
 - [ ] If an event creator enters a number with a decimal place into the cost field on an event content type, that number displays up to two decimal places. Event creators should not be allowed to add more than two decimal places.

For discussion during PM sync:
 - If an event creator enters plain text into the cost field on an event content type, the field displays the exact plain text without alteration.
**Examples:** "Free" vs. "Free to all"; "Kids are $7 and adults are $10" - what to do here?
I'm inclined to keep it cut and dry for v1 - either there's a cost or not.

~~@ reillyzlab re: ^^ - I'm hesitant to allow any plain text for this field because of unnecessary dev difficulty. Your thoughts on either a clear numerical price or nothing?~~

**Comment by matthewcrist** [comment]
We don't currently have any support for field validation in the Drupal admin. This would require us to add it, and then we'd need to regression test all fields. This seems like an overly complex solution to a minor problem. Maybe editing the help text would be helpful and cheaper?

**Comment by matthewcrist** [comment]
@jimafisk for this one, just edit the help text to:

> Enter cost as dollars. For example $55.00. Leave blank if event is free.

**Comment by jimafisk** [comment]
Replaced help text that previously existed "Enter the cost, with a $ or FREE" with "Enter cost as dollars. For example $55.00. Leave blank if event is free."

Updated bos_content_type_event feature.

**Comment by matthewcrist** [comment]
On production.
