### ISSUE TITLE
Create Global FYI

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#470]
**Goal:** To communicate a global message to 'anonymous' users in an efficient manner.

**Acceptance Criteria:**

- Create a 'FYI' piece of content that can be quickly added to all Web pages.
- Only allow users with an administrator role or greater to be able to 'enable' this content.
- A content type would be created to accommodate the following:
  - A content type would be created that when it was enabled the content would appear on every page throughout the site.  

  - Content would appear at the top of every page right below the header.
  - The content would be enabled via a checkbox somewhere in the administrative menu [location to be determined by @matthewcrist during development stage].
  - Built in a way to potentially expand this feature in the future to only include select pages by using a list component or something of the like.  

- The content type should look like the current FYI component. But, since the component will get added to the top of the page it will collide/get disrupted by the City seal. Matt/Sebastian will work together on a styling adjustment. Don't need comp.; they will iterate in real time to find a good solution. Few ideas include:
  - Shrink seal when this content type is present.
  - Increase padding on the FYI component when the 'global'/'selective-global' item is used.

- Site administrator should be able to schedule this content by date and time.  

- Assurance that all cache is purged when it is published so that we know it is appearing for users without them needing to re-load their page or clear their cache in order to see the content.

**Dev tasks**

 - [ ] Create global alert content type (fields to match FYI component)
 - [ ] Set permissions on global alert to be admin only
 - [ ] Set content type to use workbench scheduler
 - [ ] Make content available via api URL (/api/v1/alerts/global)
 - [ ] Display alert on all pages
 - [ ] Create javascript to update alert

**Success Metrics:** 

- Site administrators are able to decrease time that it takes to set up global alerts.
- Site administrators report that the feel that the process is easier to share global alerts on the website.
- Site visitors use the website a resource of information during emergencies and major events, such as parades, marathons/walks, and celebrations.
- Site visitors use this content type as a means to getting to more information (example: global FYI about snow that leads to snow page with Web traffic showing that people's entry point to snow page was this content type).

**Comment by reillyzlab** [comment]
@matthewcrist @jduffy2001 @hackajesse can you review to see if everything is covered?

**Comment by reillyzlab** [comment]
Goal is to have this complete and on production for use by the Boston Marathon (4-17-17)

**Comment by matthewcrist** [comment]
For Boston.gov, this is at:

https://edit-dev.boston.gov (blue bar, no exclusions)
https://edit-uat.boston.gov (red bar, excluded from home page and winter is coming)

You need to be an admin to view in the CMS, so use Drush to login. Hub support coming soon.

**Comment by matthewcrist** [comment]
Hub is up at: https://hub-dev.boston.gov

**Comment by reillyzlab** [comment]
Seems like gray should go all the way up to the FYI:

![screen shot 2017-03-27 at 9 36 04 pm](https://cloud.githubusercontent.com/assets/20731897/24385062/ed3c9992-1335-11e7-9bff-af6c8fa4d9f0.png)

**Comment by reillyzlab** [comment]
Anytime I try to enter an 'internal link'/searchable node I get the following error messages:

![screen shot 2017-03-27 at 9 42 43 pm](https://cloud.githubusercontent.com/assets/20731897/24385201/aa32064a-1336-11e7-8ffc-884c8d0fcd60.png)

**Comment by reillyzlab** [comment]
When I try to add an image by going into 'boston media' and selecting an image I get the following error message even though I've selected an image: 

![screen shot 2017-03-27 at 9 47 18 pm](https://cloud.githubusercontent.com/assets/20731897/24385255/1f0d1234-1337-11e7-8143-f27b659c01d5.png)

**Comment by reillyzlab** [comment]
When I upload a new image the image uploads and saves but the upload screen doesn't close so it's unclear as to whether it actually saves until you manually close the media screen.

**Comment by matthewcrist** [comment]
@reillyzlab there's a bug with the module update ticket and media stuff. I just need to deploy to dev again.

**Comment by matthewcrist** [comment]
@reillyzlab 
<img width="1680" alt="screen shot 2017-03-27 at 9 45 16 pm" src="https://cloud.githubusercontent.com/assets/9234/24385400/e18f860c-1337-11e7-9e3a-7374474bc0fa.png">

The whitespace is a pre-existing issue.

**Comment by reillyzlab** [comment]
Doesn't work on pages with hero image at the top.

See examples:
/cabinet-directory

/test-landing-page-global-fyi

**Comment by reillyzlab** [comment]
Tabbed page, pushes the header down so that the space above and below the header content is uneven.

![screen shot 2017-03-27 at 10 06 30 pm](https://cloud.githubusercontent.com/assets/20731897/24385727/b5d5bc1e-1339-11e7-9d76-6e6f61bdb762.png)

/how-budget-works

**Comment by Hondo** [comment]
Hello,

this emails are wrong, they don’t belong to me.

Don’t know why I get them – maybe I’m also called Hondo on several sites.

So please delete me from the mailing list.

 

Regards

Andreas Vogt

(Hondo)

 

 

Von: reillyzlab [mailto:notifications@github.com] 
Gesendet: Dienstag, 28. März 2017 04:07
An: CityOfBoston/boston.gov
Cc: Hondo; Mention
Betreff: Re: [CityOfBoston/boston.gov] Create Global FYI (#470)

 

Tabbed page, pushes the header down so that the space above and below the header content is uneven.

 <https://cloud.githubusercontent.com/assets/20731897/24385727/b5d5bc1e-1339-11e7-9d76-6e6f61bdb762.png> Das Bild wurde vom Absender entfernt. screen shot 2017-03-27 at 10 06 30 pm

/how-budget-works

**Comment by matthewcrist** [comment]
@reillyzlab media issue is fixed, and the ajax error  was the same issue James saw. Unfortunately, it's gone again.

**Comment by reillyzlab** [comment]
Landing page menu overlap - happens on non-homepage landing pages (Hub), only happens on desktop

![landing page menu bar](https://cloud.githubusercontent.com/assets/20731897/24418402/eee9ace2-13b9-11e7-8e6f-dc09092686fb.PNG)

**Comment by reillyzlab** [comment]
Not as pressing but not ideal spacing at top of employee directory

![employee directory](https://cloud.githubusercontent.com/assets/20731897/24418437/000d585c-13ba-11e7-9a4d-a65ed897f005.PNG)

**Comment by reillyzlab** [comment]
Broken on 'my profile' on desktop and mobile

![hub my profile](https://cloud.githubusercontent.com/assets/20731897/24418451/0bd1aff8-13ba-11e7-8231-368e6a549742.PNG)

![img_6106](https://cloud.githubusercontent.com/assets/20731897/24418587/69feffc2-13ba-11e7-95d0-f8b09cb6ceb4.PNG)

**Comment by jduffy2001** [comment]
Minor thing, do we underline these links by default in the FYI?

![image](https://cloud.githubusercontent.com/assets/7929556/24422915/3221e43e-13c9-11e7-94e0-5636f0ec2ccf.png)

**Comment by reillyzlab** [comment]
Closing this ticket b/c have one more fix in #544
