### ISSUE TITLE
Allow icon in top of hamburger menu to be clickable

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#478]
**Goal:** To increase streamlined navigation throughout the site(s).

**Acceptance Criteria:**

- When the hamburger menu is open, make the icon at the top of the header clickable. 
- When the icon is clicked it should take users to the site homepage.
- Add hover text to the icon that says 'Go to homepage'.

**Success Metrics:**

- The link in the menu works.
- Constituents happy that we added this, because the request came from public.

**Comment by matthewcrist** [comment]
Ready on staging.
