### ISSUE TITLE
Change an event to a canceled event via the CMS

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#48]
Reference #49 for what happens on Boston.gov
Set cancellation reason character limit to whatever the character limit is for the intro text section (adding this because character limits on that section may or may not change in the near term.

![canceled-event-cms](https://cloud.githubusercontent.com/assets/3886936/19398515/fef5ab16-921a-11e6-9f68-d153ef25eb8f.PNG)

**Comment by sebastianebarb** [comment]
[Basic.pdf](https://github.com/CityOfBoston/boston.gov/files/2072873/Basic.pdf)
![public notices page](https://user-images.githubusercontent.com/20642299/40984246-693f830e-68af-11e8-8a41-70f08c0e2a5c.png)

**Comment by BrutiAnteneh** [comment]
Add a cancellation functionality and a character limit for that new functionality.

**Desired Outcome:** 

- [ ] "Canceled"appended to the Event Title in all places it is referenced. 
- [ ] Description with character limit added for why it was canceled. 
- [ ] Canceled event should still appear in the all events list

This option does not currently exist. Right now we have to edit the current event and do this manually.

Follow model used for Public Notices (see screenshot above)
