### ISSUE TITLE
Public Notice Post/Publish Date

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#480]
**Goal:** To ensure that public notices are being filled out and displaying accurately.

 

**Acceptance Criteria:**

 

- Posted date field on administrative view should only be exposed to site administrator and greater roles.
- 
The "posted" date that shows on boston.gov should be the date when the notice is published - not the date that first draft was saved [current state].

- 
The "posted date" on the administrative view should be 'locked' and uneditable to all users except site administrators.  
  
  

- 
**Success Metric: ** Public notices work as described in the above and James/other content contributors are happy with the displays of 'posted' on public notices.

**Comment by matthewcrist** [comment]
## Primary testing steps

 * Log in as user that is not admin
 * Create public notice
 * Publish public notice
 * Wait a few minutes
 * **Verify that Posted Date matches publish time**
 * Unpublish public notice
 * Wait a few minutes
 * Republish public notice
 * **Verify that Posted Date matches original publish time**
 * Go to moderation tab of public notice
 * **Verify that each step is logged**
 * Log out
 * Login as Admin
 * Go to edit public notice
 * **Verify that publication date field is available under Publishing Options**

## Potential regression testing steps

 * **Verify that other content types can be saved and published**
 * **Verify that publication date is appropriately filled out for each**

## Future enhancements

 * Move other content types to use publication date, versus the current published date field

**Comment by reillyzlab** [comment]
@matthewcrist couldn't test the last step but good on all other accounts.
