### ISSUE TITLE
Fix break points on new tab design on how to and tabbed content

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#481]
**Goal:** To ensure that new tab design looks visually appearing on any device.

**Acceptance Criteria:** The tab design is adjusted to appear as it's supposed to at all breakpoints. Right now, it breaks when you split screen on macbook 15". (Don't know which break point that is.

See any how to or tabbed page, but quick reference page: /departments/parking-clerk/how-pay-parking-ticket

**Comment by matthewcrist** [comment]
Ready on staging
