### ISSUE TITLE
Logo cut off on all Program and Initiative Pages

### ISSUE THREAD

**Issue by shanaberry13** [CityOfBoston/boston.gov#487]
To Whom It May Concern, 

The logos on both the Metrolist and Boston Home Center landing page: boston.gov/metrolist; boston.gov/boston-home-center are cut off. I noticed this on Friday, February 17 but I thought it would resolve itself. But it seems to still be an issue.
 

Screenshot are attached.

Thanks,

Shana

![image](https://cloud.githubusercontent.com/assets/25773519/23186321/b72e9054-f854-11e6-80dd-8f82685845bb.png)

![image](https://cloud.githubusercontent.com/assets/25773519/23186391/fce96fa6-f854-11e6-9c75-a8e1aa3c5912.png)

**Comment by reillyzlab** [comment]
Thanks @shanaberry13 for submitting this. This is a bug that we're working on resolving.

@matthewcrist , Shana provided a few examples above but for additional URLs see here:

https://www.boston.gov/health-and-human-services/bcyf-family-gym
https://www.boston.gov/innovation-and-technology/autonomous-vehicles-bostons-approach
https://www.boston.gov/health-and-human-services/boston-bounty-bucks

This occurred after we made the secondary navigation changes, but verified that sidebar on both department pages and posts are okay.

**Comment by matthewcrist** [comment]
This should be resolved on staging.

**Comment by shanaberry13** [comment]
Hi Matt,

Great! Thank you for the update!! I checked in with James yesterday and he
mentioned that it will be fixed this week.

I hope you had a wonderful vacation!

Thanks,


*Shana Berry, CSM, CSPO *
Business Analyst and Product Owner of Innovation & Technology
Department of Neighborhood Development (DND)
City of Boston| 26 Court Street| Boston, MA 02108
*Cell: *954.826.9670 |*Office:* 617.635.0288

**Comment by shanaberry13** [comment]
Great! Thanks Reilly!!


*Shana Berry, CSM, CSPO *
Business Analyst and Product Owner of Innovation & Technology
Department of Neighborhood Development (DND)
City of Boston| 26 Court Street| Boston, MA 02108
*Cell: *954.826.9670 |*Office:* 617.635.0288
