### ISSUE TITLE
Clearly canceled events show on Boston.gov

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#49]
When a CMS user cancels an event, this describes what happens on Boston.gov. Reference #48 

On the list of events on /events:
- Add "Canceled: " in the same event title font, but colored freedom trail red _before_ the event title. No strikethru on this part of the event title.
- Change existing event title to charles river blue and use strikethru
  - On click, event title, including Canceled:, turns freedom trail red (aka stays exactly the same as current functionality).
- On click, event dropdown appears. Canceled reason from the CMS appears in the same event intro section font / style, but colored freedom trail red _in place of_ the normal intro text. Intro text no longer appears on the page, but still exists inside the CMS.

On an event page:
-  Add "Canceled: " in the same event title font, but colored freedom trail red _before_ the event title.
- Keep event title font/style
- Canceled reason from the CMS appears in the same event intro section font / style, but colored freedom trail red _in place of_ the normal intro text. Intro text no longer appears on the page, but still exists inside the CMS.

**Comment by hackajesse** [comment]
Need to update Events component like we did for Public Notices.

**Comment by matthewcrist** [comment]
On public notices, we replace the notice date with cancelled. On events, we should do something similar.
