### ISSUE TITLE
Provide a feed of events for City Hall events

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/boston.gov#495]
In order to provide a feed of events that are only located at City Hall, we should:

- [x] Add a checkbox to Events and Public Notices to indicate that event is located at City Hall, or on the plaza (default is unchecked)
- [x] Add a checkbox to Events and Public Notice to indicate if the event is a City sponsored event (default is checked)
- [x] Update upcoming and related events views to only display City sponsored events and notices
- [ ] Update upcoming events feed to allow users to filter based on City Hall checkbox

## Acceptance criteria

 * Content editors can mark events and public notices as happening at City Hall
 * Content editors can mark events and public notices as being sponsored by the City
 * Visitors to the calendar only see City sponsored events
 * Visitors to Boston.gov only see City sponsored events and public notices in related events and upcoming events component
 * A filterable feed of upcoming events is available for consumption

**Comment by lflockwood** [comment]
We may want to provide some help text around the City sponsored event checkbox to give people a sense for what that is.

**Comment by matthewcrist** [comment]
This is on staging. 

For events at City Hall:
https://edit-stg.boston.gov/api/v1/events?city-hall=1

For all events:
https://edit-stg.boston.gov/api/v1/events
