### ISSUE TITLE
Feeds for Third Floor City Hall Screens Enhancements

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#497]
Under consideration:

Events:

- zones for things [e.g. plaza, mezzanine, flag pole, etc.

- incorporating property management forms/process

- updating our calendar and public to include a feature to filter by 'at city hall or by zone'

Departments:

- Add in department/commission head info

**Comment by matthewcrist** [comment]
Closing since this is live on the third floor.
