### ISSUE TITLE
Fix hover state on emergency alert (red version) - text color

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#501]
Hover state on call to action on red version of emergency alert has correct hover button color, but has incorrect hover text color.

This should be changed to: When a user hovers over the call to action, the type turns white.

**Comment by matthewcrist** [comment]
Ready on staging.

**Comment by reillyzlab** [comment]
Will test with drush once at home later tonight.

**Comment by matthewcrist** [comment]
Verified on stage
