### ISSUE TITLE
Issues with admin bar (hide on tablet/mobile)

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#503]
Admin bar on hub and on edit.boston.gov slightly appears and should not - please hide.

Admin bar is unusable on tablet/mobile, but causes issues with the page header and layout (pushes items down).

Down the road we may potentially discuss editing on tablet/mobile.

**Comment by reillyzlab** [comment]
![image1](https://cloud.githubusercontent.com/assets/20731897/23707361/07ef3e12-03e0-11e7-9efd-3df09d402e09.PNG)

**Comment by jimafisk** [comment]
Related PR: #506

**Comment by jimafisk** [comment]
PR #711 fixes related menu display issues in Firefox.

With gap:

![gap](https://user-images.githubusercontent.com/5913244/26899252-91cdb128-4b9c-11e7-9ee0-c6aab1bfded6.png)

With gap fixed:

![no_gap](https://user-images.githubusercontent.com/5913244/26899262-9b5452ba-4b9c-11e7-9aae-0e8e58329c41.png)
