### ISSUE TITLE
Acquia Remote Administration Updates: AcquiaRA-2017-03-02-10-42-4

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#508]
1. Check and implement the Remote Administration updates from Acquia that Matt is comfortable with. Acquia ticket 361440

#### Module Updates

The following updates were made to Drupal contributed modules:

- [x] **Better\_exposed\_filters** updated to 7.x-3.4 from 7.x-3.2, located at sites/all/modules/contrib/better\_exposed\_filters
- [x] **Metatag** updated to 7.x-1.21 from 7.x-1.7, located at sites/all/modules/contrib/metatag
- [x] **Paragraphs** updated to 7.x-1.0-rc5 from 7.x-1.0-rc4, located at sites/all/modules/contrib/paragraphs
- [x] **Title** updated to 7.x-1.0-alpha9 from 7.x-1.0-alpha7, located at sites/all/modules/contrib/title
- [x] **Views** updated to 7.x-3.15 from 7.x-3.14, located at sites/all/modules/contrib/views
- [x] **Acquia\_connector** updated to 7.x-2.17 from 7.x-2.16, located at sites/all/modules/contrib/acquia\_connector

2. Check that site is working before 100% committing changes (Matt/Reilly/James test)
3. Resolve Acquia ticket

**Comment by matthewcrist** [comment]
These are all in. Please test that content can be created.

**Comment by reillyzlab** [comment]
What happens to public notice landing page (probably due to Better_exposed_filters):

![public notice post better exposed filters update](https://cloud.githubusercontent.com/assets/20731897/24422989/7cb0fe22-13c9-11e7-8891-baeef76a9286.PNG)

**Comment by reillyzlab** [comment]
Closing this ticket b/c creating separate ticket for this issue.

https://github.com/CityOfBoston/boston.gov/issues/543
