### ISSUE TITLE
Search doesn't index any documents within drawers

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#513]
**Background:** Search [swiftype] isn't indexing any documents that are sitting inside of [closed] drawers. This also means that no documents sitting within drawers are surfacing/appearing in search results at search.boston.gov.

**_Examples:_**

Assessing > More resources > https://www.boston.gov/departments/assessing

Elections > Forms and Information > [https://www.boston.gov/departments/elections](https://www.boston.gov/departments/elections)

Election Results > Any election results > https://www.boston.gov/departments/elections/results

Budget > Past budgets > https://www.boston.gov/departments/budget#past-budgets

**Goals:**

- To ensure that all content on website is searchable. 
- To ensure that all content can be easily found, with one avenue of getting to content being via search.

**Acceptance Criteria:** Any content on boston.gov is indexed and searchable.

**Success Metric:** No feedback is given that user can't find item in search.

**Comment by reillyzlab** [comment]
Items not indexing are being marked as 'no follow'.

Matt will see if we can programmatically change these links. Otherwise, we will have to manually adjust them all. May be able to use siteimprove to detect all instances.

**Comment by matthewcrist** [comment]
The drawers didn't have anything to do with this. It was caused by nofollow being added to all links being put into the WYSISWYG. Now, any relative link or link to boston.gov or cityofboston.gov will not have nofollows.

**Comment by reillyzlab** [comment]
Passing for now, but want to re-check once on production.

**Comment by reillyzlab** [comment]
@matthewcrist some stuff still isn't indexing

FY 2018 38D ONLINE PROPERTY TAX RETURN: FORM RC - RESIDENTIAL/COMMERCIAL (https://assessppof.cityofboston.gov/bostononline38d/Accounts/Login.aspx) is indexing but all of the other items under https://www.boston.gov/departments/assessing > more resources > taxpayer forms still aren't indexing

Checked on boston.gov and on swiftype directly

**Comment by matthewcrist** [comment]
Looks like indexed count has gone from 14000 to 18000 and the nofollows are gone from the markup.
