### ISSUE TITLE
Add Person Profile to Hub

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#516]
Background: Employees would like to know/learn more about their colleagues (city-wide), both about them personally and about their duties within the City.

Goal: To feature City employees on the Hub.

Implementation details:

- Add person profile content type to the Hub.
- Ensure that content author, content editor, and site administrator can add/edit person profiles on the Hub.

Success Metrics:

- Employees give feedback that they like learning about their colleagues.
- Person profile on Hub gets Web traffic. Never been done before.

**Comment by jimafisk** [comment]
@reillyzlab should I use the same permissions as implemented on boston?
- Site Administrator can:
  - create person_profile content
  - delete any person_profile content
  - delete own person_profile content 
  - edit any person_profile content
  - edit own person_profile content
- Content Editor can:
  - create person_profile content
  - edit any person_profile content
  - edit own person_profile content
- Content Author can:
  - create person_profile content
  - edit any person_profile content
  - edit own person_profile content
- Developer can:
  - create person_profile content
  - edit any person_profile content
  - edit own person_profile content

**Comment by reillyzlab** [comment]
@jimafisk yes please re: roles

**Comment by jimafisk** [comment]
Seems to be working when I build locally with latest develop.

![person_profile](https://cloud.githubusercontent.com/assets/5913244/26011271/6bd3de12-371e-11e7-8508-27106cc44a42.png)

![person-test](https://cloud.githubusercontent.com/assets/5913244/26011281/72337920-371e-11e7-9564-339b70875869.png)
