### ISSUE TITLE
Build an integrated map [via map component]

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#519]
_Goal:_ To allow users to experience an integrated visual experience with geolocation incorporated.

_Requirements:_ Create a maps component that can be added to any page by any Drupal admin.

Build an integrated map that geolocates users and starts zoomed to their current location [if possible]. If can't detect their location, then start zoomed out.

The component fields available should be:
- Title [required]
     - Checkbox to be able to hide title bar (like on text box)
- Short title [not required]
- Contact
- Dropdown with available taxonomies labeled 'Map'
- Checkbox for whether the map is zoomable or scrollable or not. By default, the checkbox should be checked.

Dropdown selections are created via taxonomy. Taxonomy fields should be:
- Name [required]
- Description [required]
- Type (e.g. style templates) [required]; By default, map type should be 'points on a map', but user can override based on whatever feed they select.
- ESRI feed (URL) [required]
- Ability to add additional points on a map with latitude and longitude (optional) with help text that reads: You can include a point of interest via exact latitude and longitude. You can find latitude and longitude from this website [developer recommend and add in website].

Map styling templates:
We will have at least three different styling templates for maps, which currently being created by GIS/Data team: cluster, points on a map, and highlighted streets. We will have to help implement these in Drupal.

Mobile considerations:
If content contributor has chosen to enable zooming and scrolling, then zooming and scrolling should be enabled on desktop and mobile. However, to make experience better when zooming and scrolling is enabled, then we should have a modal on top of the map that says 'interact with this map', so that users don't get stuck in scrolling of the map when they are trying to instead scroll down the page.

Accessibility considerations:
Map needs to be accessible. Can potentially do this via hidden table, but will leave to your discretion of whether there is a better way to do this.

Testing:
Test with food trucks schedule [without filters]: https://www.boston.gov/departments/small-business-development/city-boston-food-trucks-schedule

_Success Metrics:_
- Content contributors are able to add a map to Drupal within less than five minutes if they have a ARCGIS feed available.
- Constituents report having a positive experience with maps on boston.gov.

**Comment by jimafisk** [comment]
@reillyzlab - Should the "add points to map" functionality send data back to the ESRI database, or is it simply used to identify points unrelated to the underlying data set? For example, on a food truck map would admins be plotting additional food trucks? If so, should that data get saved back to the database that contains the true source of this information? If the additional points are just contextual based on info from the page being created, then I wouldn't think it'd be necessary to post the data back to source. 

For my reference this is how the food truck map is created: https://github.com/CityOfBoston/cob-maps/blob/master/public/food_trucks.html

**Comment by jimafisk** [comment]
Confirmed with @reillyzlab on 6/9/17 that component does not need to send data back to maps database outside of Drupal.

It would seem to me that the "Type" and "Add points" fields should be at the Paragraph (component) level, not the Taxonomy level. That would allow content editors to set these values when adding a map component, rather than having those values predefined by a item in a select list. @reillyzlab does that sound right to you? 

I believe the checkbox for whether the map is zoomable or scrollable can only have a single value. For example a map would be zoomable or scrollable (or none), it would never be zoomable and scrollable. @reillyzlab can you confirm?

**Comment by jimafisk** [comment]
Here's how I'm interpreting the reqs:

![map_component](https://user-images.githubusercontent.com/5913244/27041423-f0133f50-4f61-11e7-84a6-6f08a93ece82.png)

The "Map" and "Type" fields are independent taxonomies for ESRI Feed and Mapbox Basemap respectively. This way no specific feed is tied to a specific type. It also should allow admins to add options in the future without further coding.

**Comment by jimafisk** [comment]
It looks like Mapbox takes several parameters to set the map canvas that is initially loaded:

"The {z}/{x}/{y} parameters are the tile coordinates as described in the Slippy Map Tilenames (http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames) specification: they specify the tile's zoom level {z} and column {x} and row {y}." 
source: https://www.mapbox.com/api-documentation/#maps

Is this something we want to hardcode or do we want the content author creating the component to set these?

Here's a helpful resource for understanding these values: https://www.mapbox.com/help/how-web-maps-work/

**Comment by jimafisk** [comment]
Quick how-to on using some of the features added via PR #732:

<details>
<summary>Add new ESRI Feed:</summary>
![add_esri_feed](https://user-images.githubusercontent.com/5913244/27396803-40a02010-5682-11e7-98ae-a23aa9c87269.gif)
</details>
<details>
<summary>Add new Basmap:</summary>
![add_basemap](https://user-images.githubusercontent.com/5913244/27396814-476f99b6-5682-11e7-8b5e-4521b2654d01.gif)
</details>
<details>
<summary>Disable zoom scrolling:</summary>
![make_static](https://user-images.githubusercontent.com/5913244/27396833-55563940-5682-11e7-8a37-d6fdc03f6cec.gif)
</details>
<details>
<summary>Add a custom map pin:</summary>
![add_custom_pin](https://user-images.githubusercontent.com/5913244/27396850-60c87694-5682-11e7-8d28-a2e25f7c1e76.gif)
</details>
<details>
<summary>Override ESRI coordinate defaults:</summary>
![override_esri_default_coordinates](https://user-images.githubusercontent.com/5913244/27396861-6af57658-5682-11e7-9c27-664ebaa40cbb.gif)
</details>
<details>
<summary>Help text if javascript is disabled in browser:</summary>
![enable_disable_js](https://user-images.githubusercontent.com/5913244/27396872-773406e6-5682-11e7-9357-d04933b7cf93.gif)
</details>
<details>
<summary>Enable/disable zoom for screens smaller than 960px:</summary>
![enable_disable_zoom](https://user-images.githubusercontent.com/5913244/27396889-7fc0ccae-5682-11e7-9876-f121d5427d0f.gif)
</details>
<details>
<summary>Hide map title bar:</summary>
![hide_titlebar](https://user-images.githubusercontent.com/5913244/27396897-8821a3be-5682-11e7-8e45-30396a71b4a4.gif)
</details>

**Comment by matthewcrist** [comment]
This is on staging: https://edit-stg.boston.gov/departments/digital-team/test-page

**Comment by jduffy2001** [comment]
1. Just testing out the food trucks zoomable map. It doesn't look like any of the locations are clickable. Meaning, when a user clicks on one of the truck locations, there should be a pop up with truck information. Instead, when I click nothing happens. Is this something that will be added in the future?

2. For the static maps, do we have the ability to make the title appear somewhere, even if it's just like a normal title on a component? We might also want to include a spot for the description.

3. Not sure if this is a bug, but I was playing around with the maps component on this page, and now I can't get a map to appear: https://edit-stg.boston.gov/duffy-test-page

**Comment by matthewcrist** [comment]
The food truck maps are clickable now. 

James and I talked about static maps. Will leave as is for now, and enhance them in the future if needed. 

Logged a bug for #3.

**Comment by jimafisk** [comment]
bug related to item 3 above: #795
