### ISSUE TITLE
Metrolist Content Author

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/boston.gov#534]
The metrolist content author should be something other than anonymous. Can we attribute these posts to something like "ContentBot"?

**Comment by jimafisk** [comment]
Looks like it would be trivial to set author to a value coming from Salesforce: https://www.drupal.org/node/2651562

This could provide context for who to contact regarding a particular record since we would know where it originated. 

Using an arbitrary author looks like it'd require a custom module. @matthewcrist please let me know if you'd like me to work on that!

**Comment by matthewcrist** [comment]
We can create a user to assign it to if that makes it cleaner. Would prefer not to use a module for this @jimafisk.

**Comment by jimafisk** [comment]
That could work, we'd just need DND to supply the value from Salesforce - they'd need to add a field and make sure it is populated with "ContentBot" (or whatever we call the user) on each record. The current admin interface doesn't allow assigning arbitrary values for author unfortunately. Might not be a terribly hard thing to add that capability with a few hooks. But as it currently stands from what I can tell, assigning anything other than "anonymous" requires a value coming from Salesforce.

**Comment by matthewcrist** [comment]
Okay. Can you work with DND to get them to add it?

On Tue, Apr 25, 2017 at 11:20 AM Jim Fisk

<
mailto:Jim Fisk <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

That could work, we'd just need DND to supply the value from Salesforce - they'd need to add a field and make sure it is populated with "ContentBot" (or whatever we call the user) on each record. The current admin interface doesn't allow assigning arbitrary values for author unfortunately. Might not be a terribly hard thing to add that capability with a few hooks. But as it currently stands from what I can tell, assigning anything other than "anonymous" requires a value coming from Salesforce.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/CityOfBoston/boston.gov/issues/534#issuecomment-297065308
, or

**Comment by jimafisk** [comment]
On it! Thanks!

**Comment by jimafisk** [comment]
Following up on an old conversation. DND is hesitant to add a new field to their system that does not provide meaningful information for their reports/process. I think our options are:
* [acceptable] write a patch that allows setting arbitrary drupal user as node author and hope it gets pulled into a stable release of the project in the future (there's an open issue related to this: https://www.drupal.org/node/2651562)
* [acceptable] do nothing and continue having imported nodes assigned "anonymous"
* [not recommended] write a custom module to handle assigning an arbitrary author

**Comment by matthewcrist** [comment]
In the interest of simplicity, we should leave this alone.
