### ISSUE TITLE
Metrolist test data shouldn't come into boston.gov

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#535]
The following appeared in the boston.gov content list today:

![screen shot 2017-03-23 at 3 13 33 pm](https://cloud.githubusercontent.com/assets/20731897/24266547/81fbbf56-0fdd-11e7-8a81-8c63c2408b0c.png)

We should ensure that anything 'test' related - i.e. something with no content from Metrolist/Salesforce shows up in boston.gov > we should build some sort of stop gate for this.

**Comment by jimafisk** [comment]
@reillyzlab what should the gate requirements be? We currently have logic that prevents records from displaying if they are missing certain information (it will not stop the import, but should prevent display in the tables). Did this particular record appear externally?

For your reference we have the following fields on the Affordable Housing object in Drupal (in the format: name, machine name, type):
- Body, body, Long text and summary
- Property Address, field_mah_address, Text
- Zipcode, field_mah_zipcode, Text
- Neighborhood, field_mah_neighborhood, Entity Reference
- Property Manager Contact, field_mah_contact, Text
- Phone, field_mah_phone, Text
- Email, field_mah_email, Text
- Publish to Metrolist, field_mah_publish_to_metrolist, Boolean
- Lottery Application Deadline, field_mah_lottery_deadline, Date
- Lottery URL, field_mah_lottery_url, Link
- Outer Location, field_mah_outer_location, Text
- Lottery Type, field_mah_lottery_type, Text
- Lottery, field_mah_lottery_indicator, Text
- Household Income Limits (AMI), field_mah_household_income_limit, Text

**Comment by matthewcrist** [comment]
After talking with @jimafisk, we should focus on getting DND to not put these into their production data.

**Comment by matthewcrist** [comment]
Closing as this is an issue on DND's end.
