### ISSUE TITLE
Carots appear when adding public notices list to listing or landing page

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#543]
Carots appear when adding public notices list to listing or landing page.

Example:  ![public notice post better exposed filters update](https://cloud.githubusercontent.com/assets/20731897/24422989/7cb0fe22-13c9-11e7-8891-baeef76a9286.PNG)

Found on Firefox here: 
https://edit-dev.boston.gov/test-pn-0

OR 

https://edit-dev.boston.gov/test-pn

**Comment by matthewcrist** [comment]
This is fixed on edit-dev
