### ISSUE TITLE
 Landing page menu overlap

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#544]
On Firefox:

Landing page menu overlap - happens on non-homepage landing pages (Hub), only happens on desktop

![landing page menu bar](https://cloud.githubusercontent.com/assets/20731897/24418402/eee9ace2-13b9-11e7-8e6f-dc09092686fb.PNG)

**Comment by reillyzlab** [comment]
Broke firefox menu on hub altogether

![firefox menu completely broken](https://cloud.githubusercontent.com/assets/20731897/24511255/88d31eda-1539-11e7-83df-1b6c5ca15da2.PNG)

**Comment by matthewcrist** [comment]
That was a bad deploy. Try now.
