### ISSUE TITLE
White bar at top of programs/initiatives page

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#545]
Remove the white bar at the top of the page on program/imitative pages

Gray should connect with the menu bar at top and leave no white area

Without global FYI:
![program and initiatives white space](https://cloud.githubusercontent.com/assets/20731897/24425267/8fe7482c-13d1-11e7-9993-4432086e1855.PNG)

With global FYI:
![screen shot 2017-03-27 at 9 36 04 pm](https://cloud.githubusercontent.com/assets/20731897/24385062/ed3c9992-1335-11e7-9bff-af6c8fa4d9f0.png)

**Comment by matthewcrist** [comment]
Ready on staging.
