### ISSUE TITLE
AJAX issue when try to re-index Hub site search

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#551]
Following AJAX error occurs when try to re-index Hub site search.

Indexing gets nearly complete, but breaks towards the end of the indexing.

![screen shot 2017-03-02 at 6 20 47 pm](https://cloud.githubusercontent.com/assets/20731897/24512732/650f6a4a-153d-11e7-8703-8771e91f7e9b.png)

![screen shot 2017-03-02 at 6 21 06 pm](https://cloud.githubusercontent.com/assets/20731897/24512739/69d36bbc-153d-11e7-998d-3115febde15e.png)

**Comment by matthewcrist** [comment]
There were network errors yesterday. Kicked off another reindex and it's working fine.

**Comment by matthewcrist** [comment]
Nevermind. There's a bad profile causing the issue.

**Comment by reillyzlab** [comment]
Hold - think would potentially be better off to implement Hub search tickets found in search.boston.gov repo.

https://github.com/CityOfBoston/search.boston.gov/issues/9

https://github.com/CityOfBoston/search.boston.gov/issues/10

**Comment by matthewcrist** [comment]
Closing as we'd prefer to just implement Swiftype
