### ISSUE TITLE
Change permissions for content authors

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#558]
I would like to make a permanent change to the permissions of content authors so that they can edit their own listing pages. The button is located here under [permissions in Drupal](https://edit.boston.gov/admin/people/permissions):

![image](https://cloud.githubusercontent.com/assets/7929556/24660103/a4ff98f4-191c-11e7-9e0a-9e913f559e30.png)

**Comment by reillyzlab** [comment]
Once this is completed this should be adjusted in the 'manual'.

**Comment by matthewcrist** [comment]
Ready on staging.

**Comment by matthewcrist** [comment]
Assigning to James, since he created the issue.

**Comment by jduffy2001** [comment]
Looks all set to me on staging.
