### ISSUE TITLE
Sidebar Email Signup Widget

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#559]
**Overview**

We need a sidebar component that a **content author** can deploy in Drupal,  editing the headline, description, and the list the user signs up for. 

**Boston.gov Visitor**

There are two states for the form:

With description:
![8573fc36-186e-11e7-84da-2318770cd2dc](https://cloud.githubusercontent.com/assets/20726937/24673362/0a4a5f7c-1946-11e7-8226-d9c9afcfa4d4.png)

Without Description: 
![857181e0-186e-11e7-89b3-6ea9aac31e58](https://cloud.githubusercontent.com/assets/20726937/24679798/6b98760e-195c-11e7-9d2f-0a36148fa626.png)

The user can click on the box and enter their email address. When they click in the box, the prompt text goes away. If the address is longer than the box, the text disappears left as they type. They then click the button (all buttons are Submit), getting either an error #564 or success #563 message. 

**Component Requirements**

Editor creates a Drupal sidebar component. The component falls below contact info and can be stacked with other sidebar content. 

Three fields:

- Title - this edits the component header. "Stay Connected" in the example.  Default is "Stay Connected" but it is editable. Field should have a 20-character max. Help text: "This is the title. It's a short description of the signup widget. 20-character max."
- Description / Sidebar text - This edits the text below the header but above the email field. "Our new site is in beta..." in the example. Field should have a 120 character limit. Help text: "This is the description. Include a short (120 character max) description of what the newsletter is. i.e. A weekly update on what's going on in the parks department."
- Email List - This selects the email list a submitted address will be added to. This is a dropdown list created in ticket #565 

API Documentation

Subscriber needs to be created in the Upaknee 
http://documentation.upaknee.com/apidocs/call/?id=0&int=52&met=1000

**Comment by joshuagee** [comment]
Other design resources: https://github.com/CityOfBoston/design-team-workflow/issues/261

**Comment by matthewcrist** [comment]
On staging: https://edit-stg.boston.gov/departments/digital-team

**Comment by joshuagee** [comment]
@matthewcrist 

Can we remove "short title" and "contact" since it doesn't do anything?

**Comment by matthewcrist** [comment]
I'm not sure. @jimafisk is it possible to remove these fields just for the sidebar component form?

**Comment by joshuagee** [comment]
Widget won't accept "jgee84+test06082017@gmail.com" which should be a valid email address.

**Comment by jimafisk** [comment]
Unfortunately we're not able to easily remove the "short title" and "contact" fields from only the sidebar since it uses the same underlying component. So these fields will have to appear on the form, but we are able to set different displays based on whether it is sidebar or main. If I can clarify at all, please let me know. Thanks!

**Comment by matthewcrist** [comment]
@joshuagee already done on staging.

<img width="1015" alt="screen shot 2017-06-08 at 1 44 12 pm" src="https://user-images.githubusercontent.com/9234/26942594-9bb3fd82-4c50-11e7-8643-0ddf3873355b.png">

**Comment by joshuagee** [comment]
Oh great!

**Comment by reillyzlab** [comment]
Bug: https://github.com/CityOfBoston/boston.gov/issues/716
