### ISSUE TITLE
Remove Google Image Integration From Hub

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#560]
Remove Google image integration from Hub profiles.

Images that people have aren't meaningful, so don't fulfill purpose of us serving up photos of employees.

Will revisit at later time if there is a better to surface photos.

- [x] Remove from /my-profile page and move name flush left to match rest of page content

- [x] Remove from header and ensure that the avatar always appears

- [ ] Decommission Heroku service servicing this feed

**Comment by reillyzlab** [comment]
Would eliminate #353

**Comment by matthewcrist** [comment]
This is done on staging.
