### ISSUE TITLE
Sidebar Email Signup Widget Completion

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#563]
When a user successfully signs up for an email newsletter (ticket #559), the signup box should disappear and they should be shown a success message "Great. You'll get your first email soon."

![85754dd4-186e-11e7-8119-6d6663fdf302](https://cloud.githubusercontent.com/assets/20726937/24679950/0955d9c2-195d-11e7-8636-7f4ea1ac3273.png)

**Comment by joshuagee** [comment]
Additional design resources:
https://github.com/CityOfBoston/design-team-workflow/issues/261

**Comment by sebastianebarb** [comment]
![signup no text 480 copy 3](https://cloud.githubusercontent.com/assets/20642299/24721779/5f6ab2ee-1a0f-11e7-9c47-a40f91af7a96.png)
![signup w text 480 copy 3](https://cloud.githubusercontent.com/assets/20642299/24721781/5f754fe2-1a0f-11e7-9960-fa601583712d.png)

**Comment by joshuagee** [comment]
I successfully submitted, but I think the module vanished, creating an awkward jump and possibly sending me back to the top of the page. Can we make sure the user stays anchored to that location? Or perhaps keep the component size the same and display that message inside it, rather than switch to text. @matthewcrist

**Comment by joshuagee** [comment]
Talked with @matthewcrist and we don't restrict heights, so that jump will happen. I am not sure if there is anything else, since I think the header problem was just my browser.
