### ISSUE TITLE
Sidebar Email Signup Widget Error

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#564]
We need to produce an error when a user enters a non-valid email address in the signup widget created in #559 . The user should see no error if they are already on the list,  just update their record.

Don't have images, but it should look like this from #564 

![34c8cd5a-1a0f-11e7-9976-d3b3d60aa892](https://cloud.githubusercontent.com/assets/20726937/24726297/e8548eee-1a1f-11e7-8c82-1576844b9e24.png)

**Comment by joshuagee** [comment]
Additional design resources https://github.com/CityOfBoston/design-team-workflow/issues/261

**Comment by joshuagee** [comment]
There is no error message when you enter an incorrect zip code, but the data won't submit. 

Can we lock it to five numerals and show an error message?

**Comment by jimafisk** [comment]
@joshuagee - currently we're not setting any client or server side validation, everything is offloaded to Upaknee. Can we loop in with their team about the digit requirement?

**Comment by joshuagee** [comment]
Let me coordinate.

**Comment by joshuagee** [comment]
@jimafisk Are we validating email address client side?

**Comment by jimafisk** [comment]
Yes, the input has a type of email so that will do basic client side validation:

![email_validation](https://user-images.githubusercontent.com/5913244/26931881-e641c1d4-4c2f-11e7-8dc3-fd26a39a3131.png)

Since that is part of the form, it's something that Upaknee is implementing.

**Comment by joshuagee** [comment]
Cool - this is related to something else I just noticed in #570 , I think.

**Comment by matthewcrist** [comment]
@joshuagee and @jimafisk we do validate zip code server side. we can look into where the error is missing.

**Comment by joshuagee** [comment]
This is good by me with the bug flagged in #715
