### ISSUE TITLE
Drupal Source for Email Newsletters

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#565]
We need a page in Drupal where **site admin** can add newsletters as they are added into Upaknee. This will be the source of truth for our system.

This page will be the source for the dropdown select menu (field 3 in ticket #559)

Not sure if this is relevant, but this is the call to get newsletters:
http://documentation.upaknee.com/apidocs/call/?id=1

**Comment by jimafisk** [comment]
@joshuagee I spoke with @matthewcrist and we'll be structuring the newsletter source as a Drupal taxonomy, aka a list of terms. Are you able to point me to where I can see all the different newsletter options that need to be included? Thanks!

**Comment by matthewcrist** [comment]
@jimafisk The widget takes an id. We need a name.

**Comment by jimafisk** [comment]
Does each newsletter have a name and ID associated with it?

We can add an ID field to the vocabulary. So when configuring the Newsletter widget the admin will select the term name and then in the template we'll substitute in the actual ID since it's associated with the name.

**Comment by matthewcrist** [comment]
Yes. That's how it should work.

**Comment by matthewcrist** [comment]
On staging, you can add newsletter taxonomies.

**Comment by joshuagee** [comment]
Just added a few on staging -- it seems like it works but there's no way to review and see if they are there.

**Comment by joshuagee** [comment]
Wasn't clear that this is where newsletters ended up. Might be nice if after you enter one via:

https://edit-stg.boston.gov/admin/structure/taxonomy/newsletters/add 

it goes to here:

https://edit-stg.boston.gov/admin/structure/taxonomy/newsletters

instead of remaining on that page. 

If that's hard, then this is clear by me and can be closed.

**Comment by joshuagee** [comment]
Deemed not with it by @reillyzlab so good to go.
