### ISSUE TITLE
Search - header and menu links not working

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#568]
In google chrome, firefox, and internet explorer:
On search.boston.gov, none of the links are working in the header or menu.

If you click on any of the links, search.boston.gov simply reloads and does not take you to specified link.

Header/menu still working on 311, which is the other place I for sure new the app layout was applied.

Menu also breaking:
![menu broken](https://cloud.githubusercontent.com/assets/20731897/24711065/e7c06f26-19ec-11e7-9deb-3a6bc59c32cd.PNG)

**Comment by matthewcrist** [comment]
This should be on the search.boston.gov repo, but it's fixed.
