### ISSUE TITLE
Email Signup Widget Main Body Component Error

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#570]
We need to produce an error when a user enters a non-valid email address in the signup widget created in #569 . The user should see no error if they are already on the list,  just update their record.

Don't have images, but it should look like this from #564 

![34c8cd5a-1a0f-11e7-9976-d3b3d60aa892](https://cloud.githubusercontent.com/assets/20726937/24726297/e8548eee-1a1f-11e7-8c82-1576844b9e24.png)

**Comment by joshuagee** [comment]
@jimafisk 

You get different error messages based on the kind of error. I think the first two are client-side and the last one is server side. Not a big deal, but not ideal.

![error2](https://user-images.githubusercontent.com/20726937/26932106-8ac68fbe-4c30-11e7-97fe-f910242b7e54.png)
![error3](https://user-images.githubusercontent.com/20726937/26932105-8ab772cc-4c30-11e7-834c-45dd2e0b2a1b.png)
![error1](https://user-images.githubusercontent.com/20726937/26932104-8ab58f8e-4c30-11e7-83d4-e1f18e26f7ce.png)

**Comment by jimafisk** [comment]
I believe all three examples are client side. The popups with the little yellow icon are produced by your browser because of the "email" type attribute. The "Please enter a valid email address" looks like javascript that Upaknee is implementing. What is the desired outcome?

**Comment by joshuagee** [comment]
Ah I didn't realize my browser was getting in the way. Logged this over in #715 since this isn't a blocker for prod.

**Comment by jimafisk** [comment]
So would you prefer to see only the red error messages and not the popup ones? We could ask Upaknee to remove the type=email attribute from the input and that should remove those. The extra context about what is wrong with the user entered data could potentially be helpful, but Upaknee could write that validation themselves and have the error messages appear in a consistent way.
