### ISSUE TITLE
"Menu" Translation for Select Unreadable

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#574]
When boston.gov is translated into portuguese and vietnamese, the words 'menu' are unreadable because they get covered by the three bars in the 'menu box'

Portuguese:
![menu bar portuguese](https://cloud.githubusercontent.com/assets/20731897/24735429/e0104404-1a50-11e7-9d72-8cb8ee112c17.png)

Vietnamese:
![menu bar - vietnamese](https://cloud.githubusercontent.com/assets/20731897/24735431/e4434b98-1a50-11e7-9405-42946c580a2a.png)

**Comment by jimafisk** [comment]
Updated menu screenshots:
![english](https://cloud.githubusercontent.com/assets/5913244/25629833/f94c14d2-2f38-11e7-9eba-fd0862ab475b.png)
![portuguese](https://cloud.githubusercontent.com/assets/5913244/25629838/fb917232-2f38-11e7-8468-9cfd72c93e9d.png)
![vietnamese](https://cloud.githubusercontent.com/assets/5913244/25629843/fdd86d3e-2f38-11e7-84eb-b63c6cb1b0b6.png)

**Comment by matthewcrist** [comment]
Looks like this caused a regression on the Hub @jimafisk. Can you take a look and submit a hotfix PR to master and one to develop.

<img width="149" alt="screen shot 2017-05-09 at 10 59 51 am" src="https://cloud.githubusercontent.com/assets/9234/25857304/a672b8ba-34a6-11e7-9e71-70f02aee47a0.png">

**Comment by jimafisk** [comment]
@matthewcrist I wasn't able to reproduce this, did you end up fixing? Thanks!

**Comment by matthewcrist** [comment]
@jimafisk you can see this on Hub staging

**Comment by jimafisk** [comment]
![menu_regression1](https://cloud.githubusercontent.com/assets/5913244/26205282/4a80037c-3baf-11e7-9f32-e9fec649d9a6.png)

**Comment by jimafisk** [comment]
Screenshot per fix in PR #681 

![new_menu_style](https://cloud.githubusercontent.com/assets/5913244/26209586/3b4a5810-3bbb-11e7-9ec2-118c8a8d8d39.png)
