### ISSUE TITLE
Boston.gov/events filters overlapping

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#575]
The titles in the filters for "event type" and "neighborhood" on our [events page](https://www.boston.gov/events) are overlapping:

![image](https://cloud.githubusercontent.com/assets/7929556/24813192/1f7d7a44-1b9b-11e7-8d0b-71fc929fbec8.png)
![image](https://cloud.githubusercontent.com/assets/7929556/24813213/2c911bc8-1b9b-11e7-8d28-cda45495ffe4.png)

**Comment by matthewcrist** [comment]
## Testing steps

- Visit /events, click on filters
- Verify that filters are full width in a single column
- Visit /public-notices
- Verify that filters are broken into three equal columns
