### ISSUE TITLE
Emergency Alert Signup Form

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#583]
## Background

We need to build a new signup form for the City of Boston emergency alert system. CodeRED is an emergency alerts system procured by DoIT / Office of Emergency Alerts. We were asked to help simplify the signup form, which is quite long.  Doing discovery, we learned that any tweaks to the form as it currently exists are impossible. We also learned that there is existing API documentation for sending information into the system. 

We also learned that there is a serious signup issue. A user who signs up on the current contact form but lists their address as outside of Boston doesn’t get alerts from us. We can only send alerts to the Boston geographic area. That user instead gets put into a CodeRED national database, over which we have no control. 

Current: sign-up form: https://public.coderedweb.com/cne/en-US/BFB5F355FAB8
Forms transition ticket: https://github.com/CityOfBoston/Forms/issues/332

Additional background: https://docs.google.com/a/boston.gov/document/d/1AVNdIam0gJ186OehMhMbIwvR5mZWxJll28U6G5Pe7ck/edit?usp=sharing

## KPIs

Signup conversion rate
- Baseline - CodeRED doesn't track 
- Target - Ability to track

Qualitative
- Baseline - We’ve gotten several complaints about the signup flow as well as messaging around it. 
- Target - Reduce complaints to near-zero. 

## Data Integration

API documentation for CodeRED can be found here: https://drive.google.com/a/boston.gov/file/d/0B87NxJc5bqvTSU1LQ2hWMWoxY1k/view?usp=sharing

We'll need to send the information into a "group" within the CodeRED system. This let's us go around the account creation system. Jeanne Mallory, CodeRED Account Manager, will be able to set that up for us. 

## Admin Interface 

Captured in #587

We need a way for a *site admin* to drop a CodeRED signup component as a module. The admin can edit the title, subheadline, and body copy. 

## User Interface

A form with the following fields. It would be nice if we could require either email OR phone number. If we can't, neither. 

Text Entry field - labeled "Your email address"

Text Entry field - labeled "Your phone number"

Multiple Choice Check box - options Call me / Text me

Optional fields -- 

Text entry field - First name

Text entry field - Last name

Text entry field - Zip Code

Dropdown field - What language would you like to receive your alerts in: English, Spanish, French and Cantonese Chinese

Check box -- TDD/TTY device - Tone delivery, for hearing impaired

Button - Submit

**Comment by joshuagee** [comment]
Waiting on updated graphics here: https://github.com/CityOfBoston/design-team-workflow/issues/270#issuecomment-293303971

**Comment by joshuagee** [comment]
![](https://cloud.githubusercontent.com/assets/20642299/25136231/6654e1e8-2422-11e7-9132-cb088ac4ee96.png)

![](https://cloud.githubusercontent.com/assets/20642299/25136232/66578592-2422-11e7-8a63-28fcf29ea938.png)

![](https://cloud.githubusercontent.com/assets/20642299/25136233/66594ddc-2422-11e7-9014-573d5508cd35.png)

**Comment by joshuagee** [comment]
![](https://cloud.githubusercontent.com/assets/20642299/25136232/66578592-2422-11e7-8a63-28fcf29ea938.png)

**Comment by matthewcrist** [comment]
This is ready on staging.

**Comment by matthewcrist** [comment]
Had to remove fields for TDD and Language as CodeRed doesn't support via their API. We should still message that in the component and link to CodeRed directly for anyone who needs that support.

**Comment by joshuagee** [comment]
Two notes: 

1. Having some issues with loading an icon. Not sure if this is related to staging or something else. Could use a quick confab with @matthewcrist 

2. Also is there a way to create a page that just has this component on it? Tried that with an article page and it required body text.

**Comment by joshuagee** [comment]
I spoke with @matthewcrist 

1. Icons work fine -- he's sending me the first treatment. 
2. I might experiment with a landing page to meet this potential use case, but there are other use cases as well.

**Comment by joshuagee** [comment]
Overall this is good to go to Production.
