### ISSUE TITLE
Changes to Metrolist Lottery Search Results from Salesforce

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#586]
We need to make some basic changes to Metrolist Lottery search results to make them easier and more helpful for residents trying to find affordable housing. 

Results page -- https://www.boston.gov/metrolist/lottery-and-resale
All the information in this page is pulling from the Affordable Housing object in Salesforce 

Change 1

Add column between "Property Address" and "Contact"
Header = "Household Income Limits ​(AMI%)" -- link that to https://www.boston.gov/departments/neighborhood-development/housing-and-urban-development-income-limits)
Display results = (Household_Income_Limits_AMI__c)

Change 2

Change Lottery URL" header to "Listing Information" 

Change 3

In the Listing Information (Lottery url) search results, change it so it displays "Contact Seller" if "Lottery type" = resale

**Comment by jimafisk** [comment]
@joshuagee - is the request in change 1 to link the actual column header label to the "Housing and Urban Development Income Limits" page or to link each row value in that column to the "Housing and Urban Development Income Limits" page? Currently column header links are used for sorting the table, so using that to link to an internal page is inconsistent with existing boston.gov functionality. It also seems that linking every row in the table to the same page would be redundant. Can we feature this link in the intro text above the table instead?

**Comment by joshuagee** [comment]
Just make the column header a link -- sorry I wasn't clear.

**Comment by jimafisk** [comment]
I spoke with Shana about a couple questions I had about the reqs. Since change 3 would require adding a contrib module (https://www.drupal.org/project/views_conditional) we decided it was acceptable to change the logic to "if Listing Information is empty, display: Reach out to Contact". 

I also mentioned my concerns about changing default navigational structures on the site, since inconsistent experiences have the potential to confuse users. She approved adding the "Housing and Urban Development Income Limits" link to the page description. This will save dev time.

**Comment by matthewcrist** [comment]
This is ready on staging.

**Comment by joshuagee** [comment]
@jimafisk Reviewing it on staging, and I notice two things. 

1. I don't see the "Housing and Urban Development Income Limits" link in the page description.

2. The Household Income Limits ​(AMI%) column appears to be blank. I'm not sure if this is a function of the Salesforce database itself being blank or the connection.

**Comment by jimafisk** [comment]
Hi @joshuagee thanks for testing. Here's what's going on:
1. Given the discussion I had with Shana, the "Housing and Urban Development Income Limits" is going to be a content change. That can be made at any time on stg or prod independent of release.
2. The Household Income Limits ​(AMI%) information has likely not migrated to Drupal yet. Currently Drupal looks for updates in Salesforce before trying to get new information. We can kick this process off by editing and saving the records in Salesforce.

**Comment by joshuagee** [comment]
Those both make sense. Thanks @jimafisk.

**Comment by joshuagee** [comment]
Checked with Shana and we're good to go.
