### ISSUE TITLE
Emergency Alert Signup Form Admin Change

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#587]
A *site admin* to drop a CodeRED signup component as a module #583 

The admin can edit the title, subtitle, and body copy (on the left in the image) but can't tweak anything about the form.

![](https://cloud.githubusercontent.com/assets/20642299/25136231/6654e1e8-2422-11e7-9132-cb088ac4ee96.png)

**Comment by matthewcrist** [comment]
This is ready on staging

**Comment by joshuagee** [comment]
This works.
