### ISSUE TITLE
Adjust Required Fields for Person Profile

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#588]
We're expanding the use of person profiles to include employees beyond cheif/department head level.

- Would like to no longer make 'address' required for person profiles.

Brings no value on pages such as these:
Example: https://www.boston.gov/departments/innovation-and-technology/patrick-flaherty

![address field on person profiles](https://cloud.githubusercontent.com/assets/20731897/25245322/0970201c-25d2-11e7-8f68-57e6830a6ef0.PNG)

- Should also make dashed line under photo disappear if there is no contact information listed

**Comment by jimafisk** [comment]
It looks like the address field is already optional, what's required currently is the address1, city, state, and zip fields _only if_ there is an address. 

![required_fields](https://cloud.githubusercontent.com/assets/5913244/25353760/62b5fbf4-28fe-11e7-8e28-f7eb158e0490.png)

You can remove the address from the person_profile by selecting "None" for country.

![not_required](https://cloud.githubusercontent.com/assets/5913244/25353827/9bdfa0e2-28fe-11e7-8abc-d0fe5deff13a.png)

I agree that the UI isn't intuitive. A low effort change would be setting the "Default country" on the content type to none. That way the page will load looking like the second screenshot on this page and not the first. Thoughts?

**Comment by matthewcrist** [comment]
Makes sense to me. @reillyzlab thoughts?

**Comment by matthewcrist** [comment]
@jimafisk go ahead and implement as you suggest.
