### ISSUE TITLE
Add auto-save to Drupal

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#59]
https://www.drupal.org/project/autosave

This would work for saving a content type, but wouldn't work for adding components since those are AJAX forms and this module doesn't support. We'd need to have the autosave be consistent across all save to be useful.

Is there another module that would work for that purpose?

**Comment by hackajesse** [comment]
@reillyzlab is there context around not having an auto-save option?

**Comment by reillyzlab** [comment]
@hackajesse my understanding is that it was out of scope for MVP.
