### ISSUE TITLE
Fix for 396 - display of grids of places/programs listing pages

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#591]
Places and programs listings pages don't have any space between the last row and the footer and should.

See examples at /neighborhoods

![screen shot 2017-04-23 at 10 43 45 pm](https://cloud.githubusercontent.com/assets/20731897/25321654/ed6bca00-2875-11e7-935d-0cac1dea84e8.png)

**Comment by jimafisk** [comment]
I think we should add a `p-b500` class to the pattern library, then I can update sites/all/themes/custom/boston/templates/views/views-view-unformatted--places--listing.tpl.php like the attached screenshot.

```
.p-b500 {
    padding-bottom: 27.56px;
    padding-bottom: 1.7225rem;
}
```
![p-b500_class](https://cloud.githubusercontent.com/assets/5913244/25343427/048f38e0-28dd-11e7-90a1-686a30bf5010.png)

@matthewcrist does something like that already exist?
