### ISSUE TITLE
Fix for 396 - grid of cards display of grid of programs

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#592]
Grid of programs component - display of the grid boxes is incorrect.

See here:
on staging: /test-grid-cards

![screen shot 2017-04-23 at 10 55 05 pm](https://cloud.githubusercontent.com/assets/20731897/25321842/60fc29fa-2877-11e7-86b7-f23502c5c107.png)

**Comment by jimafisk** [comment]
@reillyzlab can you clarify the requested changes (e.g. Is the image too narrow, is the border not right?)? Thanks!

**Comment by reillyzlab** [comment]
Sorry, disregard most of this.

However, realized the issue was I seeing is that on hover a white line appears between the photo and body content on hover, which is different than the other card scenarios

**Comment by matthewcrist** [comment]
I updated the hover to be consistent with other card hovers.
