### ISSUE TITLE
RSS Feed for News

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#600]
We need to create an RSS feed for /news so that users can get a list of all news on boston.gov

This feed should be able to be filterable.

**Comment by reillyzlab** [comment]
@matthewcrist created a new RSS feed for news: https://www.boston.gov/rss/news

It has the same filters as the News page as well, so you can go to /news, filter the page, then change /news to /rss/news/[filter]. 

Here's an example RSS feed of all news from the Mayor's Office: https://www.boston.gov/rss/news?title=&field_contact_target_id%5B%5D=446&field_published_date_value%5Bmin%5D%5Bdate%5D=&field_published_date_value%5Bmax%5D%5Bdate%5D=

**Comment by matthewcrist** [comment]
Here it is: https://edit-stg.boston.gov/rss/news
