### ISSUE TITLE
Add filter by dept. to events RSS feed

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#604]

**Comment by jimafisk** [comment]
Should use new field_related_departments instead of field_contacts per PR #609. Once merged, I will add this filter and update feature.

**Comment by jimafisk** [comment]
@reillyzlab to clarify, does this RSS feed exist? Is this referring to the upcoming events feed: https://www.boston.gov/api/v1/upcoming-events

**Comment by matthewcrist** [comment]
@jimafisk this is the feed https://edit.boston.gov/rss/events. Filtering by department should be added to https://edit.boston.gov/rss/public-notices as well

**Comment by jimafisk** [comment]
Have we thought about how a consumer of our RSS feeds is to find information about filtering? Are we going to have links to already structured queries for subsets of data? The structure of a query string looks something like this:
- Empty query: `https://www.boston.gov/rss/events?title=&field_event_dates_value[value]&field_event_dates_value2[value]&field_event_type_target_id=All`
- Searching for titles with "Sumner" in them (Returns "Sumner Tunnel Toll Plaza project update meeting" and "Walking Tour of Sumner Hill, Jamaica Plain"): `https://www.boston.gov/rss/events?title=Sumner&field_event_dates_value[value]&field_event_dates_value2[value]&field_event_type_target_id=All` 
- Searching for titles "Sumner" that are also part of Event Type "Outdoor," which has an TID of 181 (Returns only "Walking Tour of Sumner Hill, Jamaica Plain"): `https://www.boston.gov/rss/events?title=Sumner&field_event_dates_value[value]&field_event_dates_value2[value]&field_event_type_target_id[]=181`
