### ISSUE TITLE
Revisit filters on news, events, public notices to match

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#605]
Revisit filters on news, events, public notices to match

Most likely moving to top of page rather than left sidebar.

Should revisit how this appears b/c big drop down of filters seems like poor use case, particularly on mobile

**Comment by BrutiAnteneh** [comment]
Added screen shots for current page views:


## News page filters
![screenshot-2018-6-13 latest city of boston news-1](https://user-images.githubusercontent.com/33470951/41376365-08bdd5a2-6f27-11e8-9e6a-2a8397d375f5.png)

## Events page filters
![screenshot-2018-6-13 events](https://user-images.githubusercontent.com/33470951/41376096-3547c58e-6f26-11e8-9e45-2ea1de6439a3.png)


## Public notices page filters

![screenshot-2018-6-13 public notices](https://user-images.githubusercontent.com/33470951/41376103-3aed844c-6f26-11e8-941f-7c3333709bcf.png)

**Comment by BrutiAnteneh** [comment]
Closing to add to d8 wishlist.
