### ISSUE TITLE
composer update failure

### ISSUE THREAD

**Issue by shelane** [CityOfBoston/boston.gov#617]
Following the developer guide to set up my local environment, the composer update command fails. The message states that packagist.drupal-composer.org/packages.json could not be downloaded. The actual address results in a 404 error.

**Comment by hamhands** [comment]
@shelane I've been having the same issue.

Don't know if this is right, but I got composer update to stop 404-ing out by updating the composer url from `https://packagist.drupal-composer.org` to `https://packages.drupal.org/8`. Got the idea from [this thread](https://www.drupal.org/node/2863895)

**Comment by shelane** [comment]
Boston.gov is a Drupal 7 site, not Drupal 8, so I didn't know the proper path for that. There is no packages.json file at the same path for 7.

**Comment by hamhands** [comment]
Oof, right. Sorry about that.

So [this doc](https://www.drupal.org/docs/develop/using-composer/using-packagesdrupalorg) says that the packages should be hosted on `https://packages.drupal.org/7` or `https://packages.drupal.org/8` respectively. I updated the composer url with `https://packages.drupal.org/7` and it worked on my end.
