### ISSUE TITLE
Match featured events mouseover UX w/News and Announcements mouseover

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#618]
## Summary 
Featured events on an events component should match the featured posts in the News and Announcements component (which currently matches programs / initiatives, grid of cards, and others).

## Example

[Zip file of video examples of the difference](https://github.com/CityOfBoston/boston.gov/files/970896/Archive.zip)

## Requirements

- On mouseover, a featured event should have the same interaction as a featured new component (background changes to optimistic blue, font changes to white)
- Remove "Event details" or "Public Notice details" button (entire card becomes clickable instead)
- Align bottom of featured event card with bottom of image

Ideally...
 - Switch featured card image position from right side to left side to avoid any state change design needs for the date flag AND to match the other event cards (and news and announcements component).

**Comment by BrutiAnteneh** [comment]
Closing to add to d8 wishlist.
