### ISSUE TITLE
Adjust public notice card icon to be fully visible

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#619]
The stock icon image for public notices is partially covered by the date flag for public notice cards. 

Adjust the icon and re-add it to public notices so that the whole icon displays on desktop, tablet, and mobile.

![screen shot 2017-05-02 at 11 52 38 am](https://cloud.githubusercontent.com/assets/3886936/25626559/e67a2228-2f2d-11e7-8e76-2049ecf11405.png)

**Comment by jimafisk** [comment]
@sebastianebarb should the flag be smaller and the focus of the icon be shifted down and to the right? I can work on this if new design is provided. Thanks!

**Comment by sebastianebarb** [comment]
@jimafisk this is something we need to look at across the site. @reillyzlab is this something you want me puting time to now?

**Comment by sebastianebarb** [comment]
![group 4](https://user-images.githubusercontent.com/20642299/31089615-cb78e442-a772-11e7-8757-aec01cc74c5f.png)
Reduce the icon size, inverse the tail of the banner move it and make it smaller? @reillyzlab @matthewcrist, thoughts?
