### ISSUE TITLE
Search filters on /news have no mouseover state change

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#622]
Search by Title, Author, and Date on [Boston.gov/news](https://www.boston.gov/news) do not change state when a user mouses over them and accordingly might not know they're clickable.

At a minimum, the copy should become underlined. A more visible solution is to turn the buttons optimistic blue and switch the font color to white.

Needs input from the design team.

**Comment by BrutiAnteneh** [comment]
Closing to add to d8 wishlist.
