### ISSUE TITLE
Search filters on /events do not change state on mouseover

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#624]
Search by Title, Dates, Event Type, and Neighborhood on [Boston.gov/events](https://www.boston.gov/events) do not change state when a user mouses over them and accordingly might not know they're clickable.

At a minimum, the copy should become underlined. A more visible solution is to turn the buttons optimistic blue and switch the font color to white.

Needs input from the design team.

**Comment by reillyzlab** [comment]
Closing b/c won't implement
