### ISSUE TITLE
Cards on /public-notices do not change state on mouseover

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#625]
Cards on [Boston.gov/public-notices](https://www.boston.gov/public-notices) do not change state when a user mouses over them and accordingly might not know they're clickable.

At a minimum, the title copy should become underlined. A more visible solution is to turn some or all of the card background to optimistic blue and switch the font color to white. If there is a Public Testimony option, that font could change to white, as well instead of staying red to prevent contrast issues.

[Example of current use](https://www.boston.gov/pay-and-apply) on Boston.gov

Needs input from the design team.

**Comment by BrutiAnteneh** [comment]
We won't implement.
