### ISSUE TITLE
Short title bug: Location of short title in workbench admin

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#634]
Bug to ticket in Acceptance QA: https://github.com/CityOfBoston/boston.gov/issues/439

For short title in workbench admin, the following components have the short title appearing as the first field (even above title) which is confusing. The short title doesn't fall within the collapsible admin box for the components.

- [x] Upcoming events

- [x] News and announcements

- [x] iFrame

- [x] Hero image

- [x] User Action

- [x] FYI

- [ ] Featured guides

Note: These are all components that didn't previously have a short title. Short title functionality is new.

**Comment by matthewcrist** [comment]
This is fixed on production.

**Comment by reillyzlab** [comment]
Not fixed for 'featured guides' on either site.
