### ISSUE TITLE
Elected Officials Directory Page

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#65]
Story:
As a site admin I want the ability to create an Elected Officials directory so that the public can see who their elected officials are.

Acceptance criteria:
As a site administrator I want to be able to add a list of people to a listing page. 
As a site administrator I want to be able to select what type of people are displayed on this listing page.

Implementation details:
- Create a list of people view
  *\* View should display people using a Listing view mode
  *\* View should have a contextual filter for Profile Type
- The view should be added to the List component so it can be added to a listing page.
- Create the node.tpl.php override for people listing view.
- Update Architecture Document
  ​\* Export to features (bos_view_*​)
- Write testing steps.

Attached "Grid of People", as there is no Elected Officials Directory Page comp

![grid-of-people-1440](https://cloud.githubusercontent.com/assets/3886936/17486738/edf49f74-5d5f-11e6-9ca4-92bb17b12283.png)

**Comment by jduffy2001** [comment]
I believe this is satisfied with our new City government page:

https://www.boston.gov/departments/311/city-boston-government
