### ISSUE TITLE
local build failing

### ISSUE THREAD

**Issue by shelane** [CityOfBoston/boston.gov#651]
All setup steps are now working. However, the last setp of running the local:build commands fails.
Both ./task.sh build:local and ./hub-task.sh build:local show errors and the sites do not load in the browser.

project > build:local:

 [property] Loading /Users/french/Sites/devdesktop/boston.gov/project.yml
 [property] Loading /Users/french/Sites/devdesktop/boston.gov/build/core/phing/build.yml
     [echo] local.settings.php already exists, ignoring.
     [echo] Executing commands against multisite "hub"
     [echo] Building the db from is set to "sync"
     [echo] Using settings file /Users/french/Sites/devdesktop/boston.gov/docroot/sites/hub/settings/local.settings.php
     [echo] Using "hub" database
 [property] Loading /Users/french/Sites/devdesktop/boston.gov/build/custom/phing/build.yml

project > setup:drupal:settings:

     [echo] local.settings.php already exists, ignoring.

project > local:sync:

     [exec] Unable to load class Drush\Sql\Sql                                   [error]
     [exec] exception 'Drush\Sql\SqlException' with message 'Unable to find a    [error]
     [exec] matching SQL Class. Drush cannot find your database connection
     [exec] details.' in
     [exec] /Users/french/Sites/devdesktop/boston.gov/vendor/drush/drush/commands/sql/sql.drush.inc:597
     [exec] Stack trace:
     [exec] #0
     [exec] /Users/french/Sites/devdesktop/boston.gov/vendor/drush/drush/commands/sql/sql.drush.inc(443):
     [exec] drush_sql_get_class()
     [exec] #1 [internal function]: drush_sql_drop()
     [exec] #2
     [exec] /Users/french/Sites/devdesktop/boston.gov/vendor/drush/drush/includes/command.inc(361):
     [exec] call_user_func_array('drush_sql_drop', Array)
     [exec] #3
     [exec] /Users/french/Sites/devdesktop/boston.gov/vendor/drush/drush/includes/command.inc(212):
     [exec] _drush_invoke_hooks(Array, Array)
     [exec] #4 [internal function]: drush_command()
     [exec] #5
     [exec] /Users/french/Sites/devdesktop/boston.gov/vendor/drush/drush/includes/command.inc(180):
     [exec] call_user_func_array('drush_command', Array)
     [exec] #6
     [exec] /Users/french/Sites/devdesktop/boston.gov/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(64):
     [exec] drush_dispatch(Array)
     [exec] #7
     [exec] /Users/french/Sites/devdesktop/boston.gov/vendor/drush/drush/drush.php(70):
     [exec] Drush\Boot\BaseBoot->bootstrap_and_dispatch()
     [exec] #8
     [exec] /Users/french/Sites/devdesktop/boston.gov/vendor/drush/drush/drush.php(11):
     [exec] drush_main()
     [exec] #9 {main}
     [exec] The external command could not be executed due to an application     [error]
     [exec] error.
     [exec] Illegal string offset 'site' backend.inc:1032                        [warning]
     [exec] The command could not be executed successfully (returned: ssh:       [error]
     [exec] connect to host staging-19375.prod.hosting.acquia.com port 22:
     [exec] Connection refused
     [exec] , code: 255)
     [exec] The external command could not be executed due to an application     [error]
     [exec] error.
     [exec] Error: no database record could be found for source @thehub.test     [error]
     [exec] No Drupal site found, only 'drush' cache was cleared.                [warning]
     [exec] 'drush' cache was cleared.                                           [success]
 [property] Loading /Users/french/Sites/devdesktop/boston.gov/project.yml
 [property] Loading /Users/french/Sites/devdesktop/boston.gov/build/core/phing/build.yml
     [echo] local.settings.php already exists, ignoring.
     [echo] Executing commands against multisite "hub"
     [echo] Building the db from is set to "sync"
     [echo] Using settings file /Users/french/Sites/devdesktop/boston.gov/docroot/sites/hub/settings/local.settings.php
     [echo] Using "hub" database
 [property] Loading /Users/french/Sites/devdesktop/boston.gov/build/custom/phing/build.yml

project > local:update:

     [exec] 'drush' cache was cleared.                                           [success]
     [exec] The drush command 'fra' could not be found.  Run `drush cache-clear  [error]
     [exec] drush` to clear the commandfile cache if you have installed new
     [exec] extensions.
     [exec] Command updatedb needs a higher bootstrap level to run - you will    [error]
     [exec] need to invoke drush from a more functional Drupal environment to run
     [exec] this command.
     [exec] The drush command 'updb' could not be executed.                      [error]
     [exec] The drush command 'fra' could not be found.  Run `drush cache-clear  [error]
     [exec] drush` to clear the commandfile cache if you have installed new
     [exec] extensions.
     [exec] The drush command 'acquia-reset-permissions' could not be found.  Run[error]
     [exec] `drush cache-clear drush` to clear the commandfile cache if you have
     [exec] installed new extensions.
     [exec] Command pm-disable needs a higher bootstrap level to run - you will  [error]
     [exec] need to invoke drush from a more functional Drupal environment to run
     [exec] this command.
     [exec] The drush command 'dis acquia_purge acquia_agent' could not be       [error]
     [exec] executed.
     [exec] Command pm-enable needs a higher bootstrap level to run - you will   [error]
     [exec] need to invoke drush from a more functional Drupal environment to run
     [exec] this command.
     [exec] The drush command 'en stage_file_proxy migrate_ui field_ui views_ui  [error]
     [exec] context_ui bos_development dblog' could not be executed.
     [exec] Command core-cron needs a higher bootstrap level to run - you will   [error]
     [exec] need to invoke drush from a more functional Drupal environment to run
     [exec] this command.
     [exec] The drush command 'cron' could not be executed.                      [error]
     [exec] The drush command 'mrs' could not be found.  Run `drush cache-clear  [error]
     [exec] drush` to clear the commandfile cache if you have installed new
     [exec] extensions.
     [exec] No Drupal site found, only 'drush' cache was cleared.                [warning]

**Comment by cob-hondo** [comment]
Thanks to @finneganh, we now have a basic Docker install that will get you up and running pretty quickly with a fresh DB.
