### ISSUE TITLE
Updated Featured Guides Component

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#66]
Story: As an anonymous user I want the featured topics component to be visually appealing on any device I might be using.
As a stakeholder I want the featured topics component to match the IDEO designs so that the look and feel of the site stays consistent.

@sebastianebarb can you attach relevant comps for featured guides from IDEO?

**Comment by sebastianebarb** [comment]
![news-a-1440](https://cloud.githubusercontent.com/assets/20642299/20446580/64de22d4-ada8-11e6-9233-fb627ce1e67d.png)
![news-768](https://cloud.githubusercontent.com/assets/20642299/20446581/64deaccc-ada8-11e6-85c8-5d886d59ce79.png)
![news-480](https://cloud.githubusercontent.com/assets/20642299/20446582/64e3bbea-ada8-11e6-8a89-1c168654996e.png)

**Comment by hackajesse** [comment]
@sebastianebarb I think this was meant to be the featured _guides_ not the featured events / news. Is there any difference right now between the IDEO comps for guides and what's on the website now?

**Comment by sebastianebarb** [comment]
@hackajesse there is no featured guide mock up. Whats on the site is extremely close to the Ideo mock.

**Comment by sebastianebarb** [comment]
@hackajesse next steps?

**Comment by hackajesse** [comment]
@sebastianebarb the comps are slightly different in that they display the list of links for the guide. Just want to have that detail attached to this story.

**Comment by sebastianebarb** [comment]
![featured guides component](https://cloud.githubusercontent.com/assets/20642299/21431568/caf1ce84-c835-11e6-9540-ba3dabbc5ca7.png) @hackajesse

**Comment by BrutiAnteneh** [comment]
Closing to implement later.
