### ISSUE TITLE
Add Access to Security Questions on Hub

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#666]
Add link to access security questions on Hub

![image 12](https://cloud.githubusercontent.com/assets/20731897/26004920/68186bb2-3705-11e7-8e82-fc05e334c945.png)

Link to: https://oimprd.cityofboston.gov/admin/faces/pages/pwdmgmt.jspx?action=setchallenges&backUrl=

**Comment by jimafisk** [comment]
This should be all set per PR #680. Here's a screenshot of the change locally:

![new_menu](https://cloud.githubusercontent.com/assets/5913244/26206485/f8884666-3bb2-11e7-8156-61940512314b.png)


Currently we're creating this menu by setting the variables in sites/all/themes/custom/boston_hub/template.php via `hook_preprocess_page()`

![template](https://cloud.githubusercontent.com/assets/5913244/26205985/7ad751a4-3bb1-11e7-9bf1-83fdadd44e51.png)

Then we're adding those values to sites/all/themes/custom/boston_hub/templates/default/page.tpl.php for display

![user_menu](https://cloud.githubusercontent.com/assets/5913244/26206011/93ecb436-3bb1-11e7-81f5-d81e3654f241.png)

Probably not a high priority, but we could leverage the existing user_menu to make this configurable so admins could make adjustments without having to write any code.

![existing_user_menu](https://cloud.githubusercontent.com/assets/5913244/26206907/0ea012de-3bb4-11e7-8148-ee6a6b2c8143.png)
