### ISSUE TITLE
Ability to search drawers component with "ctrl + f"

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#679]
When a user comes to a Boston.gov page with a drawers component on it, I want them to have the ability to search for all of the content in the drawers by pressing "ctrl + f."

@matthewcrist and I spoke about potentially setting it up so that when a user presses "ctrl + f", all of the drawers would open on the page, allowing a user to search.

**Comment by jimafisk** [comment]
First stab at this:
![search](https://user-images.githubusercontent.com/5913244/28136297-33e089be-6717-11e7-82b8-e1d558be32f8.gif)

**Comment by matthewcrist** [comment]
@jimafisk this needs to be tweaked so that CMD+F works on Mac and CTRL+F works on Windows.

**Comment by jimafisk** [comment]
@matthewcrist does this look better? I unfortunately couldn't test it on my ubuntu machine. If it's still giving problems, I'll try to grab a mac to test with. Thanks!

**Comment by jduffy2001** [comment]
looks good to me.
