### ISSUE TITLE
Add a citywide option in related content for events, public notices, posts

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#685]
On events, public notices, and posts, please add an option where a user can click a box that says "Citywide" at the bottom of the neighborhoods list:

![image](https://cloud.githubusercontent.com/assets/7929556/26249557/1296b7fa-3c75-11e7-822a-70f9894a9301.png)

This "Citywide" option would function in the same way as checking all of the neighborhood boxes. Also, when it appears on the website, instead of seeing all of the neighborhoods in an event or public notice, like this:

![image](https://cloud.githubusercontent.com/assets/7929556/26249613/485acb24-3c75-11e7-8c86-f3398e0922e4.png)

A user would see the word "Citywide."

**Comment by matthewcrist** [comment]
Assigning to @jimafisk as he has most familiarity with this.

**Comment by jimafisk** [comment]
The first thing I notice when looking at this is there is inconsistency how this functionality currently works across content types.

For example the Public Notice content type uses `field_multiple_neighborhoods` which is a reference to the Neighborhoods taxonomy:
![public_notice_field_multiple_neightborhoods](https://cloud.githubusercontent.com/assets/5913244/26645280/81a981b0-4605-11e7-9073-58309c844687.png)

The Event content type uses `field_place` which is a reference to Place Profile content:
![event_field_place](https://cloud.githubusercontent.com/assets/5913244/26646515/f2d6cca4-4609-11e7-8bb2-56ae34e25161.png)

For content types that use `field_place` (like Events) we use a custom module called bos_form_related_content to separate Neighborhoods from the autocomplete field into checkboxes:
![related_neighborhoods_explained](https://cloud.githubusercontent.com/assets/5913244/26646565/16f8095e-460a-11e7-9386-c9a5df7920cd.png)

Some things to note:
1. Currently he custom module that breaks neighborhoods out from places (bos_form_related_content) only works with Event and Post content forms
![forms](https://cloud.githubusercontent.com/assets/5913244/26646796/fe3f90f2-460a-11e7-9851-0bde39e1928a.png)

2. When using `field_multiple_neighborhoods` (like Public Notices do), the display will list the neighborhoods in the sidebar. However using `field_places` (like Events do) the neighborhoods list will not display in the sidebar
![event_and_notice](https://cloud.githubusercontent.com/assets/5913244/26647112/3cc5fbda-460c-11e7-823f-92c4a7ffe957.png)

3. Using `field_place` (like Events do) will allow events to appear on related neighborhood pages. Using `field_multiple_neighborhoods` (like Public Notices do) will not as far as I know.
![related_events](https://cloud.githubusercontent.com/assets/5913244/26647497/872453d8-460d-11e7-9c4d-ced32c45ce82.png)

**Comment by jimafisk** [comment]
Spoke w @jduffy2001, we can disregard info above pertaining to related content.

PR #703 should add functionality detailed above (https://github.com/CityOfBoston/boston.gov/issues/685#issue-229975193). 

**Note:** Fix requires one content update to be made on stg/prod manually: add a taxonomy term called 'Citywide' to the Neighborhoods vocabulary (/admin/structure/taxonomy/neighborhoods). Are there other site areas using this vocabulary that this term addition will impact? 

Related issues:
- checked '#states' not working: https://www.drupal.org/node/994360#comment-5860156
- default values being overridden by js on page load: https://www.drupal.org/node/2477053#comment-12116210

**Comment by jimafisk** [comment]
This is working on staging for Events. It is not working for Public Notices (I'll need to tweak the module). Posts should be discussed since it does not use field_multiple_neighborhoods.

**Comment by jduffy2001** [comment]
So, this works for events. Definitely seeing the "Citywide" option, and the filtering is working:
https://edit-stg.boston.gov/calendar/event

Looks like for public notices, when you select "citywide," it's still including all of the neighborhoods, instead of just saying "citywide":

![image](https://user-images.githubusercontent.com/7929556/27234189-185cade0-528a-11e7-87ba-5a51e22c0ed5.png)

https://edit-stg.boston.gov/public-notices/27321

I know the "Citywide" option for public notices is pulling from related content, instead of from a taxonomy, the way it is with events. I assume that's causing the issue.

**Comment by jimafisk** [comment]
PR #897 fixes the neighborhoods display for public notices.

**Comment by jimafisk** [comment]
@jduffy2001 I just tested and this appears to be working on stg for public notices, can you confirm if you get a chance? Thanks!

**Comment by reillyzlab** [comment]
@jimafisk 

Tested this again.

1. It is working on public notices, but not working on events or posts [i.e. can't select 'citywide as option]

2. When this shows up, the only display on the front end should be 'citywide' - none of the neighborhoods should appear in the list.
![27234189-185cade0-528a-11e7-87ba-5a51e22c0ed5](https://user-images.githubusercontent.com/20731897/32856820-ee948490-ca13-11e7-932a-a96c33b881d9.png)

**Comment by jimafisk** [comment]
@reillyzlab - I think the first item you identified is happening because there are actually two fields that look similar but act differently. Posts currently do not have the correct field that uses the Citywide option. Events have two similar Neighborhood fields: one is on the "related content" tab (this won't have citywide) and one is on the "events details" tab (this should have the citywide option).

The second item you mentioned about all the neighborhoods displaying is interesting... Is there a chance this test was done on production? It seems to be working when I try on stg:
- Test event: https://edit-stg.boston.gov/calendar/test-event
- Test public notice: https://edit-stg.boston.gov/public-notices/34526

**Comment by reillyzlab** [comment]
Passes so closing
