### ISSUE TITLE
Technical Requirements: Contact Form

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#688]
- When a user clicks an email address [in the ‘contact’ area of the website or ideally anywhere through the website], the site uses JavaScript to open up a form based on the email - key off of email, allows a user to system the form, and then the user receives a ‘success’ message within the same modal.
- If a user has ‘no javascript’ enabled, then the sites will prompt that their email client be opened instead 
- Acts like feedback modal for both form and success message
- Fields for contact form needed:
     - Title line
     - Subject line 
     - Description [area]
     - Name 
     - Email 
- Our system automatically detects/verifies email address so that content editors nor Digital Team do not have manually add emails that should be recognized in another system.
- When a user makes a submission, we should be able to track the time that it takes for a user’s email to get to a department after they hit ‘submit form’ and for a contact/department to respond.
- When a user submits, we should be able to track the following when someone submits:
     - IP address of the submitter and responder
     - Date and time submitted
     - Date and time of original response
- We should only track the initial submission and response, but then remove ourselves from the tracking process if there is additional email exchange

**Comment by joshuagee** [comment]
We've gotten requests from two departments (EMS and Assessing) to have a contact form that can go to different email addresses based on a drop down the user selects. We could build this out in SeamlessDocs, but it might be better to see if we can build it out here. I can see more departments wanting a feature like this, and we should also provide a consistent "contact" UX.
