### ISSUE TITLE
Newsletter subscription component

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#69]
Story: As a content author, I want to be able to add a newsletter subscription component to a page.

This may or may not be a component. It may be a checkbox within certain types of components that simply shows an additional UI.

Acceptance Criteria:
- As a content editor, I can add a newsletter subscription component to any page that allows components.
- As a site user, I can view newsletter subscription component on any page that allows components.
- When filled out and submitted, users information should be in Mailchimp (or other email mailer)
- User can enter name and email address
- If JS is enabled, clicking submit shows that the user submissions was successful inline
- If JS is disabled, clicking submit will send the user to Mailchimp (or other email mailer) confirmation page

**Comment by hackajesse** [comment]
@sebastianebarb is this idea any different from the guides "follow" button? Ref #75

**Comment by reillyzlab** [comment]
Closing b/c created separate epics/tickets
