### ISSUE TITLE
Add workbench schedule to program/initiative profile content type

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#693]
Can we add scheduled publishing to the program/initiative profile content type?

![image](https://cloud.githubusercontent.com/assets/7929556/26367150/a68f668e-3fbb-11e7-94a2-7065def5939e.png)

We also can't schedule publishing on person or place profiles, but I'm not sure if those content types need it. The program profile content type is being used a lot, though, so this would be a nice addition.

**Comment by reillyzlab** [comment]
I'd say let's do all of the remaining content types that are left while we're doing this unless dev. team flags this as a major issue.
