### ISSUE TITLE
Was this Helpful Functionality

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#70]
Story: As an anonymous user I want the ability to provide feedback on if a page was useful to me or not so that the city can better understand how I use their content.

Acceptance Criteria:
- As an anonymous user I want the ability to provide feedback to the city on a post if it was or was not useful to me.
- As an anonymous user I want the ability to provide feedback to the city on an article if it was or was not useful to me.

Implementation details:
- Investigate options for "Was this Helpful" *\* Keep in mind integrity of voting, caching, DDOS, etc...
- Implement functionality for users to provide "Was this Helpful" votes on posts and articles.
- Create and document Testing Steps that exercise the Acceptance Criteria.

**Comment by hackajesse** [comment]
@sebastianebarb are there comps for this? If so, would you add please?

**Comment by sebastianebarb** [comment]
@hackajesse No comps, I can create one. When do you need this by?

**Comment by hackajesse** [comment]
@sebastianebarb end of 2016.

**Comment by sebastianebarb** [comment]
![was this helpful](https://cloud.githubusercontent.com/assets/20642299/21554082/a683b652-cdda-11e6-947b-98b1be1d52b4.png)
https://drive.google.com/open?id=0B0RwQU94BhGeRXZ5T1hCV1dwUGM

**Comment by BrutiAnteneh** [comment]
Closing and adding to d8 wishlist.
