### ISSUE TITLE
Add workbench scheduler to person profile on Hub

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#701]
Add workbench scheduler to person profile on Hub

**Comment by jimafisk** [comment]
@reillyzlab does this screenshot demonstrate what you're looking for?

![workbench_schedule](https://user-images.githubusercontent.com/5913244/26901292-451d38ce-4ba3-11e7-93e7-7c81cf4ac3b4.png)

That's something we'd set via global permissions. Which roles should have access to this functionality? For instance we'd add it for content_editors across content types like this:

![scheduler_permissions_contet_editor](https://user-images.githubusercontent.com/5913244/26901972-97b9449a-4ba5-11e7-9ab0-425b3342d0f4.png)

There is also a "manage schedules" permission:

![scheduler](https://user-images.githubusercontent.com/5913244/26902031-c7b74ef8-4ba5-11e7-896b-5d9065d12035.png)

That would depend on pull request #710 being merged, closing issue #692.

**Comment by jimafisk** [comment]
I've added these permissions to both the "Site Administrator" and "Content Editor" roles on PR #774. If this needs to be revised, just let me know and I'll adjust. Thanks!
