### ISSUE TITLE
Issues with WYSWIG styles breaking on workbench admin

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#707]
Fields not reflecting the changes made in the WYSIWYG field when page is in draft [so content editors can't see what their content formatting looks like when it draft]. Shows up when page is saved or live though.

Example image:
![image](https://user-images.githubusercontent.com/20731897/26842533-2aa32726-4abb-11e7-99fc-aeab91d4d31d.png)

See example on this page: https://edit.boston.gov/node/8656/draft

Gary (DND) has noticed this over the last few weeks.

**Comment by jduffy2001** [comment]
This appears to be a content author only issue. I'm seeing fine as an admin. I only noticed the error when logged in as a user who only has content author permissions.
