### ISSUE TITLE
Issue with numbering and restarting numbering in text fields (using wysiwig)

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#713]
Anytime there is a text area available to enter content in Drupal (ex. text component, drawers component) and a user tries to use the 'numbering' item on the wysiwig AND tries to restarting number' (i.e. start with 2 rather than 1) this functionality does not work.

A user sees that the numbering looks like it's restarting in the administrative view, but when the page is published the list starts at 1, not 2.

Visual examples: 

Admin screen:
![screen shot 2017-06-07 at 10 22 43 am](https://user-images.githubusercontent.com/20731897/26899746-083caad4-4b9e-11e7-9775-031734efb4b6.png)

Saved screen:
![screen shot 2017-06-07 at 10 24 37 am](https://user-images.githubusercontent.com/20731897/26899763-19b5ec26-4b9e-11e7-956b-a8e44a5f00a0.png)

Multiple examples of staging site, but one specifically: https://edit-stg.boston.gov/test-landing -- did confirm issue on staging and production

**Comment by jimafisk** [comment]
@reillyzlab is this only happening across separate WYSIWYG fields? Here's a screenshot to describe what I mean:

![article_separate_fields_1](https://user-images.githubusercontent.com/5913244/28039887-d3803bea-6591-11e7-8ecc-a623e4d01b57.png)

Typically the system will only be aware of numbering sequence within a single text editor box. Are there any use cases in the components you mentioned where we don't want numbering to persist across separate text fields? Drawers example:

![across_multiple_fields](https://user-images.githubusercontent.com/5913244/28040103-a5b8223a-6592-11e7-863e-a64a0ce619a4.png)

**Comment by reillyzlab** [comment]
Closing because not important to prioritze
