### ISSUE TITLE
Different error messages on signup

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#715]
You get different error messages based on the kind of error when you sign up via an email widget. I think the first two are client-side and the last one is server side. 

![error2](https://user-images.githubusercontent.com/20726937/26932106-8ac68fbe-4c30-11e7-97fe-f910242b7e54.png)

![error1](https://user-images.githubusercontent.com/20726937/26932104-8ab58f8e-4c30-11e7-83d4-e1f18e26f7ce.png)

![error3](https://user-images.githubusercontent.com/20726937/26932105-8ab772cc-4c30-11e7-834c-45dd2e0b2a1b.png)

**Comment by matthewcrist** [comment]
i've set the form to novalidate which should prevent chrome from trying to validate the form too.

**Comment by matthewcrist** [comment]
You can test this on staging now @joshuagee.

**Comment by matthewcrist** [comment]
All set @joshuagee
