### ISSUE TITLE
Newsletter sign up component doesn't align accurately in the sidebar on post.

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#716]
Newsletter sign up component doesn't align accurately in the sidebar on post.

![screen shot 2017-06-08 at 3 32 00 pm](https://user-images.githubusercontent.com/20731897/26947333-5d6cf2f8-4c60-11e7-9558-bc3ab85b52b4.png)

https://edit-stg.boston.gov/news/test

**Comment by matthewcrist** [comment]
This is due to the left column being shorter than the "published by" block. This needs to handled via governance.
