### ISSUE TITLE
Help Text Changes

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#719]
I have some edits for the help text of the signup widget. 

![crop](https://user-images.githubusercontent.com/20726937/26947880-4e3856d6-4c62-11e7-95f1-77bf5b9217f9.png)

**Title** 
Current text: This is the title. It's a short description of the signup widget. 20-character max.
New text: This is a short (20 character) description of the signup widget. Use it for a brief call to action. 

**Short Title**
Current: The short title is used to populate the in-page navigation. Please keep it short: one to three words is ideal. Example can be found on boston.gov/winter/. This isn't used on the sidebar version of the newsletter component.
New: This is where you name in-page navigation. It isn't used on the sidebar version. Please keep it short: one to three words is ideal. Example can be found on boston.gov/winter/. 

**Contact**
Current: This isn't used on the sidebar version of the newsletter component.
New: This won't appear in the sidebar version of this component.

**Comment by matthewcrist** [comment]
Done on production
