### ISSUE TITLE
Emergency Sign Up Alert Color 

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#727]
There are two issues with the text color on the emergency alert component on boston.gov

1. In the white theme version of the Emergency Alert signup, after a user hits 'sign up' the text rendering their submitted information is white and blends into the white background color of the component. 

![emergency alert bug](https://user-images.githubusercontent.com/20726937/27046269-d2aa3a1c-4f71-11e7-95b9-9c62b76bf882.JPG)

When the information is processed, the text should display as xx.

2. In the blue theme version of the Emergency Alert signup, the field titles are blue and blend into the background color. 

![screen shot 2018-01-16 at 10 41 13 am](https://user-images.githubusercontent.com/20731897/34997817-6f28403e-faab-11e7-9319-284322db5103.png)

The field headers should be xx.

**Comment by jimafisk** [comment]
@joshuagee is the proposed fix to make the text black? Or should we change the background color? Thanks!

**Comment by joshuagee** [comment]
Very good question. The background is variable. It can be grey, blue, or white. 

Somehow, the form field text changes to accommodate the background color. The submitted information text should do the same.

**Comment by jimafisk** [comment]
This will likely require a CSS change, possibly more specific selector to avoid overrides (testing is difficult due to CORS). Dark background classes, such as `b--b` should have a light `color` style.

@matthewcrist knows the setup best and will look into it. Thanks!

**Comment by joshuagee** [comment]
I should say I'm probably agnostic if the text changes automatically, but I can't think of a font color that works on all backgrounds without changing.

**Comment by joshuagee** [comment]
I should say I'm probably agnostic if the text changes automatically, but I can't think of a font color that works on all backgrounds without changing.

**Comment by jimafisk** [comment]
Totally agree, by design the font color should be dependent on the background color. That should be how the stylesheets are defined by default and not require extra logic to figure out.

**Comment by sebastianebarb** [comment]
For white: The answers should be set in Lara, Italics, Charles River Blue.
For Blue: Field titles should be white.

![66578592-2422-11e7-8a63-28fcf29ea938](https://user-images.githubusercontent.com/20642299/34998912-4f34639a-faae-11e7-8004-a286dd0656a2.png)
![6654e1e8-2422-11e7-9132-cb088ac4ee96](https://user-images.githubusercontent.com/20642299/34998913-4fab7142-faae-11e7-8838-b3d951a75d64.png)
![66594ddc-2422-11e7-9014-573d5508cd35](https://user-images.githubusercontent.com/20642299/34998917-4fba4ac8-faae-11e7-8de4-a3604821593c.png)

**Comment by joshuagee** [comment]
Same thing happens in grey. 

![codered background color](https://user-images.githubusercontent.com/20726937/35398463-eec35cc8-01bf-11e8-9450-40d6bf8cb074.JPG)

**Comment by reillyzlab** [comment]
@BrutiAnteneh to test

**Comment by BrutiAnteneh** [comment]
The issue passed as expected
