### ISSUE TITLE
Map Component

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#73]
Story:

As a content editor I want to be able to add a map component to a page when I need to provide geographical information to a user.
Map Component - Styling
Story:

As an anonymous user I want to be able to see where an event is happening or a place is located when viewing content about the page.
As an anonymous user I want to be able to view a map related to the content I am looking at on any device I might be using.
As a stakeholder I want the map component to be styled per the IDEO designs to keep the sites look and feel consistent.

On Calendars:
Story: \* As a content editor I want a map to be displayed on the calendar listing page with pins on the location of each event that is currently on the list with geographical location.

Story:
- As an anonymous user I want to be able to use the map on an event to understand where this event is happening.
- As an anonymous user I want the ability to view the event map on any device I might be using.
- As a stakeholder I want the map to display per the IDEO desgisn so that the sites look and feel remains consistent

On Events:
Story: \* As a content editor I want to be able to provide geographical information on my event which populates a point on a map.

Integration:
Story: \* As a site administrator I want to be able to use Maps in content on my website.

Implementation details: 
- Investigate options for pulling in maps to Drupal.
  *\* Comps were using [snazzymaps](https://snazzymaps.com)
  *\* See also Drupal 7 module [Styled Google Maps](https://www.drupal.org/project/styled_google_map)
- Create foundation for using maps on the website.
- Document usage of maps on the site

**Comment by reillyzlab** [comment]
Closing b/c we made second ticket
