### ISSUE TITLE
Replace table formatting on websites

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#730]
Replace all of the table formatting on websites

Dependent on: https://github.com/CityOfBoston/patterns/issues/90

**Comment by jimafisk** [comment]
I believe there are two types of tables currently. 

The first are tables that are created via WYSIWYG (`sites/all/themes/custom/boston/src/sass/components/table/_responsive-table.scss`):
- https://www.boston.gov/transportation/performance-parking-pilot#seaport-rate-tables
- https://www.boston.gov/parks-and-playgrounds

The second are tables that use a View template (`sites/all/themes/custom/boston/templates/views/views-view-table--metrolist-affordable-housing--page.tpl.php`):
- https://www.boston.gov/metrolist/affordable-properties
- https://www.boston.gov/metrolist/lottery-and-resale

@reillyzlab are there other ways of creating tables that I'm missing?

**Comment by jimafisk** [comment]
As part of CityOfBoston/patterns#90 we'll take the style from the [budget tables](https://github.com/CityOfBoston/budget.boston.gov/blob/develop/_stylus/main.styl#L5) and create a new component in the pattern library adding the markup with new classes if necessary [here](https://github.com/CityOfBoston/patterns/tree/develop/components/base) and stylesheets [here](https://github.com/CityOfBoston/patterns/tree/develop/stylesheets/components). Then we'll make adjustments in Drupal on boston.gov to ensure those styles are used.

Process for updating editor markup:
1. You can view profile settings in the browser, for example Full HTML can be seen at `/admin/config/content/wysiwyg/profile/full_html`
2. To add a new setting, edit `sites/all/modules/features/bos_text_formats/bos_text_formats.module` and add a new item to the $plugins associative array.
3. Then add a plugin for the new item you created in the `sites/all/modules/features/bos_text_formats/plugins` directory (or edit existing responsive_table plugin to use pattern library classes)

Process for updating view markup:
1. Edit the template file and manually change the class names as appropriate (example: `sites/all/themes/custom/boston/templates/views/views-view-table--metrolist-affordable-housing--page.tpl.php`)

**Comment by jimafisk** [comment]
I created a PR in crispus to add responsive tables (using budget.boston.gov style): https://github.com/CityOfBoston/patterns/pull/115

Currently it uses the same classes being used on boston.gov. That may get revised, but it should hook in as it stands now.

**Comment by matthewcrist** [comment]
Updated styles are on production.

**Comment by matthewcrist** [comment]
-
