### ISSUE TITLE
Iannella spelled wrong in public notice template

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#733]
Can we fix the spelling of "Iannella" here in Drupal?

![image](https://user-images.githubusercontent.com/7929556/27386428-ccf99088-5663-11e7-9094-cf4e2106b42e.png)

It's under the "details" section. Iannella should have two "ns".

**Comment by matthewcrist** [comment]
This is on staging.

**Comment by jduffy2001** [comment]
looks good to me.
