### ISSUE TITLE
WYSIWYG styling should reflect live Boston.gov website

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#736]
It looks like the styling in our WYSIWYG fields has reverted back to the original Drupal styling. When you make changes, it doesn't reflect the styling and size of how the text will appear on the live site.

For example, on the [Small Business page](https://www.boston.gov/departments/small-business-development/small-business-center):
![image](https://user-images.githubusercontent.com/7929556/27444917-e9865fe6-5745-11e7-89b5-eef548eecad5.png)
![image](https://user-images.githubusercontent.com/7929556/27444934-0206f45e-5746-11e7-9e0c-93d8237fc708.png)

Not sure if it matters, but the WYSIWYG field also appears in our components, not just in the body of some component types.

**Comment by matthewcrist** [comment]
Fixed on production.
