### ISSUE TITLE
Put "Neighborhoods" under related content in alphabetical order

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#739]
In the related content sections of "posts", "events," and (eventually) "public notices," the "neighborhoods" section isn't in any specific order. Could we place the neighborhoods in alphabetical order instead?

You can see what I mean here:
![image](https://user-images.githubusercontent.com/7929556/27445582-405df926-5748-11e7-9c1f-12c58815de84.png)

**Comment by matthewcrist** [comment]
On staging.

**Comment by jduffy2001** [comment]
All set, looks great.
