### ISSUE TITLE
Portion of open accessibility toolbar shows on mobile/tablet when logged in as site contributor

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#74]
If a user has any site contributor role and they are logged in on Hub or Boston.gov and the accessibility bar is in use then a portion of the open accessibility bar shows up without clicking on the accessibility wheel/opening the accessibility toolbar. 

Happens because editing workbench/admin view isn't configured for tablet/mobile, so the editing toolbar pushes the accessibility toolbar down the page.

Must have for Hub (not immediately), but nice to have for Boston.gov.

**Comment by matthewcrist** [comment]
We removed the accessibility toolbar.
