### ISSUE TITLE
Tabbed links in how-tos not working

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#741]
The links created when you click on a tab in a how-to aren't working.  For instance, with this [birth certificate how-to](https://www.boston.gov/departments/registry/how-get-birth-certificate), when I click on "in person," I'm getting a url that adds "#in-person" to the url. Here's that url:

https://www.boston.gov/departments/registry/how-get-birth-certificate#in-person

When I copy and paste that into my browser, or use it contextually as a link, it doesn't send me to the "in person" tab. I just end up refreshing the how-to, and go to the first tab on the page.

**Comment by matthewcrist** [comment]
This is ready on staging.

**Comment by jduffy2001** [comment]
looks good to me on staging.
