### ISSUE TITLE
Enable "Boston Field Instances" feature in profile

### ISSUE THREAD

**Issue by ygerasimov** [CityOfBoston/boston.gov#744]
After installing Public profile (bos_profile) feature "Boston Field Instances" is not enabled. In this way there is no way to add Paragraph components to Landing page.

What do you think about enabling this feature by default in the profile?

**Comment by matthewcrist** [comment]
Sounds like a good idea.

**Comment by matthewcrist** [comment]
This is done.

**Comment by ygerasimov** [comment]
Thank you Matthew
