### ISSUE TITLE
Follow Feedback form

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#75]
Story: As an anonymous user I want to be able to provide feedback on the usefulness of the "Follow" functionality on the Topics pages.

Story: As an anonymous user I want to be able to provide feedback to the City of Boston on the follow button in a format that is visually appealing and works on any device I visit the site with.

Acceptance Criteria: 
- Navigate to the boston.gov website
- Navigate to a guide page.
- Verify there is a section for "Follow" that has a form to allow user feedback
- Verify that the Follow button is styled according to the attached comp.
- Verify clicking the "Follow" button displays a modal that matches the attached comps
- Verify you can select an option from the feedback form.
- Verify you can select an option and it tracks your selection
- Verify you can refresh the page and your selection stays selected.

Description: 
Create Custom HTML and styling for the follow feedback component form that displays on topic pages.
- This should include implementing the JS libraries needed for the graphs. 
- This should include Desktop, Tablet and Mobile styling

@sebastianebarb would you attach the comp(s) for this feature?

**Comment by sebastianebarb** [comment]
![screenshot 2016-11-18 15 49 29](https://cloud.githubusercontent.com/assets/20642299/20446256/c7ee0616-ada6-11e6-8e65-bcfb851e0782.png)
@hackajesse

**Comment by hackajesse** [comment]
Notes for the future: 
Need to figure out what any emails / SMSs look like.
Need to figure out what the triggers are for pushing an update. Simple change? What constitutes a "major" change?
Not on Posts. Events makes sense if there's a change to the location / time, etc. Could do a calendar feed instead. 
Not on Department pages.

**Comment by reillyzlab** [comment]
Unsure relevance of this so closing
