### ISSUE TITLE
Make title of "details link" actually appear in event content type

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#753]
Right now, when a user enters a title in the "details link" section of an event, it doesn't appear in the actual event. No matter what you put in that title field, the title becomes, "Event website." I would like to have it set up so that whatever title you put also appears as the title in the event.

The "details link" is located here in the event:
![image](https://user-images.githubusercontent.com/7929556/27687578-5fb2ffbc-5ca5-11e7-8b1e-132d2546af4f.png)

Here's the section:
![image](https://user-images.githubusercontent.com/7929556/27687614-7cdd23e2-5ca5-11e7-8191-15287b5938e7.png)

And here's how it appears live on the website:
![image](https://user-images.githubusercontent.com/7929556/27687652-a3b9170a-5ca5-11e7-87e4-6e0d3ddb1d17.png)

**Comment by jimafisk** [comment]
@jduffy2001 did you happen to notice if the actual link is working in this section? Thanks!

**Comment by jimafisk** [comment]
Seems like these issues might also be found in public notices based on the structure of those templates.

**Comment by jimafisk** [comment]
I take it back, doesn't look like notices have `field_details_link`. Might just be old code hanging out in the template after being copied from a base template or something. Events should be all set per PR #779

![details_link](https://user-images.githubusercontent.com/5913244/28139283-b7491712-6721-11e7-9609-985afe2531df.png)

**Comment by jduffy2001** [comment]
looks good to me
