### ISSUE TITLE
Create separate page for Recycling and Trash Directory

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#754]
The Recycling and Trash Directory is part of our [Trash Day app](https://www.boston.gov/trash-day-schedule). But, users have to click on the tab to get this particular part of the Trash Day app. We've gotten feedback from people that are missing that tab.

I'd like to create another page with a title like, "Recycling and Trash directory," that opens up with this tab first:
![image](https://user-images.githubusercontent.com/7929556/27688404-80ed21e6-5ca8-11e7-835c-dc7be4728fa0.png)

One thing I noticed, there is [this link through the ReCollect app](https://www.boston.gov/trash-day-schedule#!rc-cpage=wizard_material_list). I still think we may need to create another version of the app that opens by default on the directory, but I can use this for now.

**Comment by reillyzlab** [comment]
@jduffy2001 looks like we could embed this to solve this: https://recollect.net/example/wizard/Boston

Check it out and let me know

**Comment by reillyzlab** [comment]
@jduffy2001 don't think we need dev. time for this. Think you could implement if you wanted to. Closing here.
