### ISSUE TITLE
Banner has the same link for Bos image and Mayor title

### ISSUE THREAD

**Issue by sethRait** [CityOfBoston/boston.gov#757]
The header for Boston.gov contains an image (City of Boston) with the name of the mayor next to it (Martin J Walsh).  Currently, these are both the same link to the boston.gov homepage, but users expect to be able to click a name and be taken to relevant information on that name.  Ie. a link title should be a description of its destination.  Therefor, the City of Boston logo should indeed continue to point to the boston.gov homepage, but the name of the mayor should link to [the mayors office](https://www.boston.gov/departments/mayors-office).

**Comment by matthewcrist** [comment]
Thanks @sethRait. I've cleaned up the code a bit, but this will go to Boston.gov in the next couple weeks.

**Comment by matthewcrist** [comment]
This is done on staging.
