### ISSUE TITLE
Digital sign appears to be failing more than normal

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#764]
I usually have to turn the sign off and on again on the first floor twice a day. We're still seeing the same issue as before where more than three notices turn gray on the right, and I think that's creating some bugginess on the left as well.

Next time I swing down, I'll take some screenshots. I believe the underlying issue before was with the software for the sign itself, not the website where the information is pulled from. When you get some time, could you take a look?

**Comment by reillyzlab** [comment]
Closing b/c moved to notice signage repo
