### ISSUE TITLE
Add Beacon Hill to list of neighborhoods in related content

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#765]
In the "Neighborhoods" section of posts and events, can we add "Beacon Hill" as a neighborhood? Right now, it's missing:

![image](https://user-images.githubusercontent.com/7929556/27911797-6328d698-6228-11e7-8e3f-b8976d4063a3.png)

You can see what I'm talking about in this event:

https://edit.boston.gov/node/28427/edit

**Comment by matthewcrist** [comment]
Fixed.
