### ISSUE TITLE
Media Browser Broken When Trying to Add Pre-Existing Documents

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#768]
Any time (i.e. any component that allows you to add a 'document') a user can add a document to the websites using the media browser they should be able to  go into the library and select a file that has been previously uploaded.

Now, when you're in the document 'library' if you select a file and try to hit 'submit', the following error message displays:

![screen shot 2017-07-06 at 1 49 12 pm](https://user-images.githubusercontent.com/20731897/27925226-ff303db4-6251-11e7-8335-1c08ea27e513.png)

**Comment by matthewcrist** [comment]
Fixed on production.
