### ISSUE TITLE
"False" issue when adding images to Boston.gov

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#775]
I wanted to flag this for the group. This page in particular was very buggy when I tried to add images:

https://www.boston.gov/departments/boston-bikes/parking-your-bike

To get them to appear on the page, I had to set the images to "WYSIWYG" instead of "default." If I didn't, instead of the image, you just see the word false.

I know we've seen issues off and on with adding images, but this might be a good page to test.

**Comment by jduffy2001** [comment]
Ideal state here is that when adding images to the website, the "false" error doesn't happen. Not sure if setting images to "WYSIWYG" by default will fix this for all images, but I've seen this issue crop up across the site.

**Comment by reillyzlab** [comment]
I've also seen false appear when images are copied and pasted by hand

**Comment by jimafisk** [comment]
I'm having trouble reproducing this bug. I've tried uploading large images with both the "default" and "WYSIWYG" formats in the "Display as" field. @jduffy2001 are you able to make this behavior occur on this page: https://edit-stg.boston.gov/test-article? Thanks!

Possibly related:
- https://www.drupal.org/node/1963270
- https://www.drupal.org/node/1965536
- https://www.drupal.org/node/2631934

**Comment by jimafisk** [comment]
Spoke with @jduffy2001 and we decided to close for now since this issue hasn't appeared in some time. Feel free to reopen if you experience this issue again.
