### ISSUE TITLE
Older browser support

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/boston.gov#776]
On older browser the site breaks to be completely unusable. We should try to find ways of making it useful, though not pixel perfect. Screenshots from Safari 5.

![screen shot 2017-07-10 at 8 44 43 pm](https://user-images.githubusercontent.com/9234/28119172-e1a1067c-66e1-11e7-8515-8e706a6a504d.png)
![screen shot 2017-07-10 at 8 52 58 pm](https://user-images.githubusercontent.com/9234/28119174-e1a21a3a-66e1-11e7-8768-f1a0ca90f43c.png)
![screen shot 2017-07-10 at 8 54 24 pm](https://user-images.githubusercontent.com/9234/28119175-e1a309f4-66e1-11e7-989a-ce51e82c38c2.png)
![screen shot 2017-07-10 at 8 51 52 pm](https://user-images.githubusercontent.com/9234/28119173-e1a1f60e-66e1-11e7-8b36-2f7ef806d399.png)

**Comment by BrutiAnteneh** [comment]
Closing because QA testing covers legacy browser tests based on latest google analytics data.
