### ISSUE TITLE
Update to cabinets component type

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#777]
We used the cabinet component type to build our [City of Boston government page](https://www.boston.gov/departments/311/city-boston-government).

Under the "Departments, Boards, and Agencies" section of this component, we list out all of the departments associated with a cabinet. Instead of linking to the department page, we're linking to the contact taxonomy. You can see the link at the bottom left here:

![image](https://user-images.githubusercontent.com/7929556/28133454-1d7ade8a-670e-11e7-871f-a075e77de61e.png)

This is leading to dead links on the page.

An ideal version of this component would have this section linking to department pages rather than the contact taxonomy.

**Comment by matthewcrist** [comment]
This is fixed.

**Comment by jduffy2001** [comment]
looks great, thanks hondo.
