### ISSUE TITLE
Issue with Hub posts with intro image

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#780]
Issue with Hub posts with intro image - not sure if it's because of adjustments to breadcrumbs or because of site alert or something different altogether.

Note: White space above intro image and pushed down intro image slightly overlapping breadcrumbs.

See on staging /news/fourth-annual-youth-enrichment-day

![screen shot 2017-07-12 at 10 20 04 pm](https://user-images.githubusercontent.com/20731897/28147732-88b4e5dc-6750-11e7-8775-31772fb69442.png)

Potentially related to: https://github.com/CityOfBoston/boston.gov/issues/461

**Comment by matthewcrist** [comment]
Issue with breadcrumbs is fixed.
