### ISSUE TITLE
Site alert causes gap between alert and hero image on Hub.

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/boston.gov#784]
You can see the gap on news items.

<img width="291" alt="screen shot 2017-07-14 at 9 17 08 am" src="https://user-images.githubusercontent.com/9234/28213699-3ce43790-6875-11e7-8e9d-40879b81f79f.png">

**Comment by jimafisk** [comment]
@matthewcrist this should be all set. I just tested locally with the asset_url set to patterns.boston.gov and it looked ok. Can you take a look when you get a chance? Thanks!

**Comment by jimafisk** [comment]
Testing steps:
1. Sign into the staging site for the Hub. Create a new Site Alert (`/node/add/site-alert`) if one isn't already displayed
2. Check out news content with full spanning hero images across the top to ensure that there is not a gap between the image and the site alert.
3. Test various scenarios, like news pages without a site alert, other content with full spanning images at the top of pages (like events) with and without a site alert
4. Check responsive breakpoints using Firefox or Chrome inspector tools

<details>
  <summary>Testing gif (click to expand)</summary>

  ![alert_gap](https://user-images.githubusercontent.com/5913244/34391925-e8cea062-eb16-11e7-97f0-6b9a13f4e6ce.gif)

</details>

**Comment by BrutiAnteneh** [comment]
The issue did not pass as expected. 

The gap between a Hero image and the Site Alert appears to be resolved for **News pages, Guide pages and How-To pages**. However, _the gap _remains_ on **Event** pages._





_Resolved on **News** pages:_
![news and site alert](https://user-images.githubusercontent.com/33470951/34498108-1ea4135a-efce-11e7-8c2c-b38c833367d7.png)        
![news no site alert](https://user-images.githubusercontent.com/33470951/34499086-68a6cd2c-efd2-11e7-9aa7-de2a9800dfa1.png)



_Gap on **Event** pages:_ 
**Event 1**
![hockey gap site](https://user-images.githubusercontent.com/33470951/34495527-9512e24c-efc3-11e7-8728-e4ee8d69f3ff.png) 

**Event 2**
![pasted image event site alert 12](https://user-images.githubusercontent.com/33470951/34498459-ae9edb06-efcf-11e7-8e4b-d804d00b76a9.png)
