### ISSUE TITLE
Padding or float bug with "cabinets" component

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#796]
The cabinets component has a bug. Instead of the Cabinet head bio being lined up with the rest of the component, it's floating up and to the left above the text and list of departments:

![image](https://user-images.githubusercontent.com/7929556/28464053-8db6951a-6df1-11e7-8efe-1475a688952a.png)

You can see it on the [City government page](https://www.boston.gov/departments/311/city-boston-government).

**Comment by matthewcrist** [comment]
Fixed on staging

**Comment by jduffy2001** [comment]
looks great.
