### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#81]
As an anonymous user I want to be able to contact the city of boston so that I can communicate with the city through the website.
- Enable webforms module
- Configure contact us form
- Add contact us link to footer (migration)
- Export to features
- Write behat tests

As an anonymous user I want the contact form to be usable on any device I might be using.
As a stakeholder I want the contact form to be displayed according the the IDEO designs so the sites look and feel is consistent.

List of forms to convert:
http://dnd.cityofboston.gov/bostonbusinesshub
http://www.cityofboston.gov/assessing/contactform.asp
https://www.boston.gov/feedback

Comps from IDEO:
![feedback-768](https://cloud.githubusercontent.com/assets/20642299/18390347/daaee4f2-7677-11e6-9a7c-a2638e773c8c.png)
![480-contact](https://cloud.githubusercontent.com/assets/20642299/18390346/daad8de6-7677-11e6-8a5b-6f1930d8349b.png)
![contact](https://cloud.githubusercontent.com/assets/20642299/18390348/daafad1a-7677-11e6-83a2-dee41134b3a2.png)

**Comment by reillyzlab** [comment]
Closing b/c addressed with combo of 'contact us' page and epic around new contact form
