### ISSUE TITLE
Revisit removal of profiles/directory item for employees

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#815]
Employees should not show up in the directory once they leave.

See Reilly for more details.

**Comment by matthewcrist** [comment]
@reillyzlab is it possible to get a feed of removed users?

**Comment by reillyzlab** [comment]
Email out to Laura on this.

**Comment by matthewcrist** [comment]
Moving back to grooming until we have a plan on how to do this.

**Comment by jimafisk** [comment]
Additional details per conversation with Matt:

We have a migration from a feed for the Hub that creates User and Profile objects.

Acquia's documentation: https://github.com/CityOfBoston/cob-runbooks/blob/09b1efc1e16e809693cf5f60f8d29396146c3c81/boston.gov/architecture/migration/hub_migration.md

We need to update the migration process to also remove anyone not in the feed. Right now, it's additive only.

The command to run the migration is:
```/usr/local/bin/drush7 @thehub.prod mi User,Profile --force --update &>> /var/log/sites/${AH_SITE_NAME}/logs/$(hostname -s)/drush-hcm.log```

We need to update the `hub_migration` module to remove users and profiles that don't exist in the HUB_HCM_FEED.

This drupal issue is related to what we need: https://www.drupal.org/node/1416672
