### ISSUE TITLE
Ability to add attachments in form for "mailto" links

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#824]
Could we add the ability to add attachments, like pdfs, word docs, and jpgs, to the "mailto" forms on Boston.gov? Right now, you have the options to add your name, email address, a subject, and a message:
![image](https://user-images.githubusercontent.com/7929556/29379420-6eb7ac54-8290-11e7-92b1-8c9531746b28.png)

Some departments use email as a way to apply for programs, so they would like to give people the ability to upload through these forms. We could use the same specs as the media browser:

- Files must be less than 256 MB.
- Allowed file types: jpg jpeg gif png svg txt doc docx xls xlsx pdf ppt pptx pps ppsx odt ods odp mp3 mov mp4 m4a m4v mpeg avi ogg oga ogv weba webp webm

**Comment by matthewcrist** [comment]
We'll need to work with Greg's team to think through any security issues on this. We'd need to trim the file size and allowed types down to make sure nothing malicious can come through.

**Comment by matthewcrist** [comment]
Moving to grooming for more information

**Comment by BrutiAnteneh** [comment]
Closing for now, may implement in the future.
