### ISSUE TITLE
Place profiles 'last updated' displaying incorrectly

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#830]
Place profiles 'last updated' displaying incorrectly

Example: https://boston.gov/historic-district/bay-state-roadback-bay-west-area-architectural-conservation-district

Did a quick scan of other content types and this seems to be the only one that's broken.

![screen shot 2017-08-21 at 5 50 30 pm](https://user-images.githubusercontent.com/20731897/29539769-587c782c-8699-11e7-83a4-2da09d9d7ba0.png)

**Comment by jimafisk** [comment]
The culprit is the `with-hero` class. This class positions the content in a way the disrupts the float of the "last updated" text (class `brc-lu`). It might work removing `with-hero` from the code below (still would need to declare `position: relative`):

```
@media (min-width: 1300px) {
    .with-hero, .node-type-public-notice .node-public-notice {
        width: calc(100% + 100px);
        -ms-transform: translate(50px, 0);
        transform: translate(50px, 0);
        right: 100px;
    }
}
```
```
@media (min-width: 980px) {
    .with-hero, .node-type-public-notice .node-public-notice {
        position: relative;
        width: 100%;
        padding: 45px 50px 0;
        background-color: #fff;
    }
}
```

And add the following:
```
.with-hero .desktop-33-right {
    padding-top: 45px;
}
```
This kind of simplification is nice, but it's a lot of broad sweeping changes that could impact other site areas. A smaller fix would be to offset the `brc-lu` class by 45px when it's in `with-hero`. It currently has `margin-top: -37px;` so we'd just need this to be -82px:
```
.with-hero .brc-lu {
    margin-top: -82px;
}
```

**Comment by jimafisk** [comment]
Here's two gifs to demonstrate these approaches.
<details>
  <summary>Approach 1 (simplify the .with-hero style):</summary>

![approach1](https://user-images.githubusercontent.com/5913244/29988074-642a07b8-8f39-11e7-935e-23435ebb14a8.gif)

(Note the positioning issue of the sidebar overlapping the main content. This happens on my screen before any style updates.)
</details>

<details>
  <summary>Approach 2 (pull the .brc-lu up slightly when it appears within a hero):</summary>

![approach2](https://user-images.githubusercontent.com/5913244/29988013-0d29656c-8f39-11e7-8884-af0b1f714f8d.gif)

(note the slight positioning issue of the "Last Updated" text being too high before the mobile breakpoint)
</details>

**Comment by matthewcrist** [comment]
@jimafisk still appears to be an issue

**Comment by jimafisk** [comment]
That's weird, it looks like the "with-hero" class is still being added:

![with_hero](https://user-images.githubusercontent.com/5913244/31462400-a8120dec-ae9a-11e7-8991-e4335c7261fb.png)

It looks like [these updates](https://github.com/CityOfBoston/boston.gov/pull/854/commits/95c0309a6339cbc5e3cd0181ed34c770d8c824c7) didn't make it into crispus here: https://github.com/CityOfBoston/patterns/blob/develop/legacy/public.styl#L5811

It's possible this was happening around the same time we were moving the last of everything over to the pattern lib. I'll take fix this and make a PR to patterns.
