### ISSUE TITLE
Running cron throws Salesforce error

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/boston.gov#847]
Here is the error

<img width="1788" alt="screen shot 2017-08-29 at 1 00 29 pm" src="https://user-images.githubusercontent.com/9234/29833662-28bc9fe6-8cba-11e7-9889-ec7616dccd41.png">

**Comment by jimafisk** [comment]
This is probably due to DND removing a field that we mapped to. I'll loop in with Shana to see if we can resolve this.

**Comment by jimafisk** [comment]
DND officially removed `Neighborhood__c` on 8/28/17, but they've been using a new field, `Neighborhood_pl__c`, as a replacement for quite some time. I'll update the mapping so the `field_mah_neighborhood` field on our Drupal object points to the new field in Salesforce. When new objects are created or existing objects are updated, it will get the values from the new field and attempt to map them to a neighborhood in our taxonomy: 

![neighborhood__c](https://user-images.githubusercontent.com/5913244/29840374-cc31eb1c-8ccf-11e7-93f9-7172f6e2dd76.png)

**Comment by matthewcrist** [comment]
This is done
