### ISSUE TITLE
Email Widget Text Color

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#856]
Newsletter signup components default to blue text color, even when the background color selected in the component is blue the subtitle and body text disappear. This makes the text unreadable. 

Solution:
Subtitle and body text should be white.

![color error](https://user-images.githubusercontent.com/20726937/30223339-6b97672a-9498-11e7-8f7f-b38db99d8de5.JPG)

Possibly related to #727

**Comment by BrutiAnteneh** [comment]
The issue passes as expected.
