### ISSUE TITLE
Adjustments to footer

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#862]
Please make adjustments to the footer:

1) Add: 
- Terms of use (Josh can provide you accurate link)
- Site Feedback: Links to feedback modal

2) Wrap the lines of text onto top lines and ensure that the links wrap appropriately when on tablet/mobile

**Comment by joshuagee** [comment]
Spoke with @reillyzlab and @jduffy2001 about this today. 

We currently don't have an updated ToS or PP. We do have an existing Privacy Policy. We have updated ones almost finalized. We should:

Phase 1 -- Move the existing PP from Cityofboston.gov onto a boston.gov page and link to that. 
Phase 2 -- Update footer with link to ToS and link to the new versions of each.
Phase 3 -- Various product tweaks for optimal implementation.

We should link to the ones we have, even if the implementation isn't perfect. 

This is also related to this [Design Team request](https://github.com/CityOfBoston/design-team-workflow/issues/443).

**Comment by matthewcrist** [comment]
@sebastianebarb with all the links causing wrapping on large screens now, can we just move to a vertical layout?

**Comment by reillyzlab** [comment]
Updated design: https://waffle.io/CityOfBoston/design-team-workflow/cards/58d17e6c0a4d4735020a635f

**Comment by BrutiAnteneh** [comment]
Closing to add to d8 wishlist.
