### ISSUE TITLE
Grid of People Component Incorporating User Profiles

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#87]
Build a component similar to grid of people grid (same styling) but building so that it runs on 'user profiles' rather than 'person profiles'.

Definitely for Hub, but could be beneficial for Boston.gov

Main use case for this is to pull staff (or at least senior staff) with photos onto dept. profile pages.

**Comment by hackajesse** [comment]
@matthewcrist did you say this would be Hub only per technical difficulty? I don't recall.

**Comment by matthewcrist** [comment]
This is Hub only as Boston.gov doesn't have those profiles.
