### ISSUE TITLE
Create webhook for publishing / needs review in Drupal

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#872]
I'm looking to create a webhook in Drupal that would allow me to get an alert message when content is published or placed in needs review.

The goal would be to use Zapier to connect to that webhook so I could get an alert message in slack. It would also be great to set this up for the Hub as well as the public website.

**Comment by matthewcrist** [comment]
For this, we should add a module that posts to a configurable URL. It should be triggered when a node moves into the needs review state, and moves into published state. 

The action should post JSON to the URL. The JSON should look like this:

```
{
  "node_id": NODE_ID,
  "title": TITLE,
  "author": AUTHOR_NAME,
  "url": ABSOLUTE_PATH_TO_NODE
}
```

**Comment by jimafisk** [comment]
I was able to setup something locally using a test channel and slack's incoming webhooks:

![drupal_slack](https://user-images.githubusercontent.com/5913244/31529043-b08ba7e8-afa4-11e7-9598-4a1768c2fa6d.gif)

This leverages https://www.drupal.org/project/slack + Rules 

@jduffy2001 is there a particular channel you want these alerts posted to?

@matthewcrist can you create a slack webhook, or grant me permission to do so?

Thanks!

**Comment by jimafisk** [comment]
A PR has been created for this integration. You might experience duplicate messages being sent when updating existing content (vs saving new content), which is due to this bug in workbench moderation: https://www.drupal.org/node/1879482

**Comment by jduffy2001** [comment]
@jimafisk looks good on staging to me. 

A nice to have would be to also include the revision log message, located here:
![image](https://user-images.githubusercontent.com/7929556/32066244-263a4492-ba4d-11e7-8124-0deaf99555c7.png)

This isn't a blocker for launching what we already have. If we're OK to close this ticket, I can create another that mentions adding this info.

**Comment by jimafisk** [comment]
Feel free to keep this issue open. There is a `[node:log]` replacement pattern that can be used in the Rules, so this will be a simple fix to add (just updating an existing feature).

**Comment by jimafisk** [comment]
@jduffy2001 this is ready for testing on stg. Thanks!

**Comment by jduffy2001** [comment]
looks good to me @jimafisk. thanks!
