### ISSUE TITLE
Bug with reset button on filtering

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#875]
Reset button on filtering for events, public notices, and news is not working.

Example:
https://www.boston.gov/events?field_event_dates_value%5Bvalue%5D%5Bdate%5D=01%2F01%2F2017&field_event_dates_value2%5Bvalue%5D%5Bdate%5D=12%2F27%2F2017&title=tour

Image:
![screen shot 2017-09-27 at 12 34 52 pm](https://user-images.githubusercontent.com/20731897/30925688-af883210-a380-11e7-8c84-5e72e23d0b40.png)

**Comment by jimafisk** [comment]
The reset behavior appears to work when I tested it using the link provided. However, the icon indeed is not showing up. @reillyzlab is the functionality broken for you, or just the display?

When I look at the path for the icon (https://d2hk73kicft6oi.cloudfront.net/img/icon-refresh.svg) I see access denied. I think we may need to add an icon for refresh to fractal: https://patterns.boston.gov/components/detail/experiential.html

The icon exists in the boston repo: https://www.boston.gov/sites/all/themes/custom/boston/src/img/icon-refresh.svg (https://github.com/CityOfBoston/boston.gov/blob/develop/docroot/sites/all/themes/custom/boston/src/img/icon-refresh.svg)

**Comment by reillyzlab** [comment]
Functionality seems to be working for me, so probably just display.


[image: COB_B_Blue_square-01.png]

Reilly Zlab

Interim Chief Digital Officer, Digital Team <http://boston.gov/digital>

Department of Innovation & Technology

City of Boston | City Hall Room 703

617-635-0057 (w) | reilly.zlab@boston.gov


Keep up with the Digital Team Roadmap
<https://www.boston.gov/departments/digital-team/digital-team-roadmap>
Request <https://goo.gl/forms/rclxItfipgEEumml1> for us to work together

**Comment by matthewcrist** [comment]
This is fixed on prod.

**Comment by reillyzlab** [comment]
Incorrect icon appearing

Showing up as:

![screen shot 2017-10-04 at 11 19 07 am](https://user-images.githubusercontent.com/20731897/31183874-dcd07c08-a8f5-11e7-91f8-a94a7ee300e5.png)

**Comment by jimafisk** [comment]
Looks like the external-link-white.svg is getting loaded. @reillyzlab can you tell which pages are showing this? These ones look ok:
- https://www.boston.gov/events
- https://www.boston.gov/public-notices
- https://www.boston.gov/news

Thanks!

**Comment by matthewcrist** [comment]
This is Hub.

**Comment by matthewcrist** [comment]
This is fixed on prod
