### ISSUE TITLE
Ensure log out button showing up Hub - tablet and mobile

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#877]
Don't believe log out button is option on tablet/mobile on Hub - we need to get added back in.

**Comment by jimafisk** [comment]
It looks like the entire admin menu disappears on screens less than 1025px wide. This happens on both the Hub and Boston. If you are using the admin theme, it also hides the expanded menu but adds the slicknav_menu, which is mobile/tablet optimized, at this breakpoint:
![slick_nav](https://user-images.githubusercontent.com/5913244/32517358-31356684-c3d4-11e7-8f4c-f3c8619769bb.png)

Although that doesn't appear to have the user logout button either. @reillyzlab was the logout option appearing previously?

**Comment by jimafisk** [comment]
I opened a PR in the pattern library to get the display of the "management" menu working on tablet/mobile again. From here, the easiest way to add user profile and logout links would be to add those to this menu, which we can configure here: `/admin/structure/menu/manage/management`

**Comment by reillyzlab** [comment]
Sorry - to clarify I'm not referring to the admin log out -- I"m talking
about this one b/c doesn't appear on mobile:

[image: Inline image 1]

Used to appear but during an update disappeared.

Jim, we can discuss if we need to figure out where to put it on mobile.


[image: COB_B_Blue_square-01.png]

Reilly Zlab

Digital Services Product Manager, Digital Team <http://boston.gov/digital>

Department of Innovation & Technology

City of Boston | City Hall Room 703

617-635-0057 (w) | reilly.zlab@boston.gov


Keep up with the Digital Team Roadmap
<https://www.boston.gov/departments/digital-team/digital-team-roadmap>

**Comment by jimafisk** [comment]
Ahh I'm with you now. What do you think about adding these options to the main menu? 
<details>
  <summary>Here's a gif to demo what I'm talking about (Click to expand)</summary>
 
![hub_logout](https://user-images.githubusercontent.com/5913244/32956877-27ad497c-cb88-11e7-9abd-b05c6a2de827.gif)

</details>

<br />
Is that too hidden?

**Comment by reillyzlab** [comment]
That idea would be great, but can we make it the first item that appears in the menu?

**Comment by jimafisk** [comment]
@reillyzlab yeah definitely. Drupal treats menu items as content (vs config that we export to code and track with git). So I created this manually on stg. Can you take a look and if it's ok I will recreate manually on prod. Thanks!

**Comment by reillyzlab** [comment]
Looks mostly good on staging. 

How displaying looks good.

But, 'log out' isn't appear on staging, just my profile, change pw, and sec.?s

**Comment by jimafisk** [comment]
This has been recreated on the live site. If it needs work, feel free to reopen. Thanks!
