### ISSUE TITLE
Images distorted on mobile

### ISSUE THREAD

**Issue by lflockwood** [CityOfBoston/boston.gov#878]
## Basic details

Images are stretched when displayed on mobile. Screenshot from news page.
URL: https://www.boston.gov/news/one-brand-means-one-message-coming-city

## Browser details

Safari on iOS 11, iPhone 6s

![4ed49072-0f62-4e6e-afcf-a8db197d59e1](https://user-images.githubusercontent.com/20707572/31017535-cfa3ac88-a4f6-11e7-813c-35ac0e7d4a95.jpeg)

**Comment by matthewcrist** [comment]
Looks like the content editor put a fixed height on the image. Removed those from the post.
