### ISSUE TITLE
Text bleeds past component on mobile

### ISSUE THREAD

**Issue by lflockwood** [CityOfBoston/boston.gov#879]
## Basic details

Text in a grid of links component is bleeding past the box (on mobile). Screenshot is from the bottom of the email newsletter page. 

URL: https://www.boston.gov/departments/digital-team/city-boston-email-newsletters

## What did happen / what should happen

Looks like the icon for the external link might be pushing all the text down. The text in a box should prob move up to be in line with (rather than sit below) the external link icon. Alternatively, you could truncate the text.

## Browser/device details

Browser: safari
OS: iOS 11
Device: iPad Air 2

![4313b991-bc99-4232-ae57-fe842567f936](https://user-images.githubusercontent.com/20707572/31018077-c024d9ec-a4f8-11e7-8f10-f0b7542b3bfd.png)

**Comment by joshuagee** [comment]
Cut down the text and will keep an eye on that in the future.
