### ISSUE TITLE
Search options/filters on events and public notices page not working

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#881]
You can't choose a department in the [public notices search](https://www.boston.gov/public-notices). You also can't choose a department, neighborhood, or type in the [event search](https://www.boston.gov/events). The "title" search in public notices also appears to be broken. Doing a simple search like "City Council" for public notices doesn't return any results.

Some examples:
https://drive.google.com/file/d/0B6JFuKRlk0wBSmRQVm9JLUVxS1E/view
https://drive.google.com/file/d/0B6JFuKRlk0wBWl9ySEdXcG1KM3M/view

**Comment by jimafisk** [comment]
I think this may be another styling issue, similar to #875. What I think may be happening in the videos you provided (thank you for those), is those check-box filters are actually being applied, even though they aren't visible, and the combination of those filters yields no results.

**Comment by jimafisk** [comment]
Here's a gif the department filters on https://www.boston.gov/public-notices:
![filters](https://user-images.githubusercontent.com/5913244/31088955-6ddec72c-a770-11e7-92be-f3653e691b4c.gif)

The URL will display the filters applied, in this case: https://www.boston.gov/public-notices?title=&field_contact_target_id[]=46

The server can't load the check-mark image: https://boston.gov/sites/all/themes/custom/boston_public/dist/img/check-mark-dark.png

**Comment by jduffy2001** [comment]
Ahh, yes. You are correct. Just tested this out. The check mark isn't appearing, but it's still filtering by that search.

**Comment by jimafisk** [comment]
I believe this is the icon we want: https://github.com/CityOfBoston/patterns/blob/develop/images/public/icons/check.svg (https://d2hk73kicft6oi.cloudfront.net/images/public/icons/check.svg)

@matthewcrist I'll submit a PR that updates:
- https://github.com/CityOfBoston/patterns/blob/develop/legacy/hub.styl#L631
- https://github.com/CityOfBoston/patterns/blob/develop/legacy/hub.styl#L9923
- https://github.com/CityOfBoston/patterns/blob/develop/legacy/public.styl#L623
- https://github.com/CityOfBoston/patterns/blob/develop/legacy/public.styl#L9249

**Comment by jimafisk** [comment]
PR: https://github.com/CityOfBoston/patterns/pull/160

**Comment by matthewcrist** [comment]
This is fixed on production.
