### ISSUE TITLE
Add language selection to Emergency Alert Signup Forms

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#882]
Related to #583.

## Happening Now

We send emergency alerts in four language (English, French, Spanish, and Hong Kong Cantonese). In our emergency alert widget users can only sign up in English. To sign up in another language, they have to click through to the CodeRED widget, which doesn't work in multiple languages.

## What should Happen

Users should be able to select their language preference when they sign up and enter the rest of their information. There should be a dropdown that defaults to English but lets a user choose one of the four language options.

## Next Steps

If you review ticket #583, you'll see our original comps had this feature. However, we had to cut it for v.1 because the CodeRED API doesn't support it. I am following up with CodeRED to set up a call about making their API more robust.

**Comment by joshuagee** [comment]
Spoke with CodeRED. They've expanded their API since we first built our widget. Attached is a template for sending data over that includes language as the last field.  

[CGtemplate_language (2).xlsx](https://github.com/CityOfBoston/boston.gov/files/1391197/CGtemplate_language.2.xlsx)

The main caveat is that the **language has to be exactly as it is within the CR system**.  Language field should be a dropdown with four options:

- English 
- Chinese (Traditional, Hong Kong S.A.R.)
- French (France)
- Spanish

This is how it was designed in our initial comps. 

![66578592-2422-11e7-8a63-28fcf29ea938](https://user-images.githubusercontent.com/20726937/31668686-e2303dd4-b320-11e7-97c0-8c4be4ed1fba.png)

**Comment by joshuagee** [comment]
@matthewcrist estimates about 3-6 hours to update the API and test. 2-4 hours to update the widget.

**Comment by joshuagee** [comment]
CodreRED Documentation

[CG Import Guide.pdf](https://github.com/CityOfBoston/boston.gov/files/1635669/CG.Import.Guide.pdf)
[CodeRED Web API for Contact Groups v3.0 (1).pdf](https://github.com/CityOfBoston/boston.gov/files/1635670/CodeRED.Web.API.for.Contact.Groups.v3.0.1.pdf)
[ECN FTP Contact Group Instructions.pdf](https://github.com/CityOfBoston/boston.gov/files/1635671/ECN.FTP.Contact.Group.Instructions.pdf)

**Comment by finneganh** [comment]
@joshuagee: is the field called "PreferredLanguage"?

Also, I need clarification: should the values be exactly the strings above, or ISO 639 language codes?

**Comment by joshuagee** [comment]
@finneganh Yes that is the field name. The values need to be exactly as the strings above.

**Comment by reillyzlab** [comment]
Additional requirement: If possible, then detect browser language set and populate relevant language in drop down.

**Comment by finneganh** [comment]
API proxy support in CityOfBoston/codered-proxy#4

**Comment by finneganh** [comment]
Keeping this in inventory until CityOfBoston/codered-proxy#4 is shipped.

**Comment by reillyzlab** [comment]
@BrutiAnteneh to test

**Comment by BrutiAnteneh** [comment]
The issue passed as expected.
