### ISSUE TITLE
Sidebar icons missing in IE, Chrome

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#883]
Looks like the sidebar icons aren't showing up in Chrome and IE. The circles are just appearing with nothing in them:

![image](https://user-images.githubusercontent.com/7929556/31190678-c55d1bee-a909-11e7-9ca9-31f93f1ebd43.png)

It's still working in Firefox.

**Comment by jimafisk** [comment]
This should fix a number of the icon issues: https://github.com/CityOfBoston/patterns/pull/162

**Comment by matthewcrist** [comment]
This is fixed on production.
