### ISSUE TITLE
Social media icons missing from Boston.gov

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#890]
The icons for the "social media links" option under "sidebar components" is not appearing on pages. It looks like the link is actually there, but the icon fails to appear. You can see what I'm talking about on the [Economic Development](https://www.boston.gov/departments/economic-development):
![image](https://user-images.githubusercontent.com/7929556/31398984-b8155d4e-adb8-11e7-894a-62e68f22715f.png)
![image](https://user-images.githubusercontent.com/7929556/31399013-d5bd2854-adb8-11e7-8cda-580aa6fe3acd.png)

**Comment by matthewcrist** [comment]
Fixed on production.
