### ISSUE TITLE
Dep Icons squishing 

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/boston.gov#894]
Noticed these 4 icons look strange on the dep icon page, looks like they're being squished. 
Happy to assist in any way with providing new icons if you need. 

Not sure who to assign this to so feel free to remove yourself

![screen shot 2017-10-12 at 10 10 45 am](https://user-images.githubusercontent.com/22770827/31501118-5911462a-af37-11e7-84cb-db41160b5189.png)
![screen shot 2017-10-12 at 10 10 53 am](https://user-images.githubusercontent.com/22770827/31501119-591f788a-af37-11e7-9c1f-474c25a3a1a0.png)
![screen shot 2017-10-12 at 10 11 03 am](https://user-images.githubusercontent.com/22770827/31501120-592e3050-af37-11e7-9c52-fa049dbf614e.png)
![screen shot 2017-10-12 at 10 11 09 am](https://user-images.githubusercontent.com/22770827/31501121-5941721e-af37-11e7-942b-3b782a0c020b.png)

**Comment by cob-deployer** [comment]
@carolinestj can you send SVG versions of these icons?

**Comment by matthewcrist** [comment]
@carolinestj can you send SVG versions of these icons?

**Comment by matthewcrist** [comment]
These icons have been updated
