### ISSUE TITLE
Common transactions line height/spacing

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#90]
1) Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

URL submitted from: https://www.boston.gov/

line-height and spacing issues in the common transactions section. I'd suggest making the icons on the left a static width (not the icons themselves but the div space it takes up) so the text to the right is aligned all the way down.

2) URL: https://www.boston.gov/

BROWSER: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

It looks like the line spacing of the typography on these cards is a little out of whack. The space between the lines of text is really big, and feels hard to read as one unified item. This looks more like an accident than intentional though, based on the excellent attention to typographic detail on the rest of the page and site.

I'm a UX/visual designer working on federal government websites with 18F. I look to this site for inspiration a lot! Nice work, friends!

**Comment by matthewcrist** [comment]
This is fixed on production
