### ISSUE TITLE
Ability to hide contact form

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/boston.gov#903]
Some email addresses don't work well with the contact form. There should be a way to keep the contact form from displaying.

**Comment by matthewcrist** [comment]
@jduffy2001 and @reillyzlab I added a checkbox to emails on department profiles called Hide Contact Form. If checked, the form won't display. You can also hide the contact form by adding a class of 'hide-form' to the mailto link.

**Comment by jduffy2001** [comment]
@reillyzlab looks like this is working on staging.
