### ISSUE TITLE
Hub menu breaking on IE 11

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#91]
User attempting to access Hub on IE 11.0.9600.18326

Menu is breaking the following way:

Tried having him clear cache and didn't fix.

![a6ee47be-84a2-11e6-9b4e-27995b07d3da](https://cloud.githubusercontent.com/assets/20731897/19532233/d751cf76-9608-11e6-8be8-8c0140183a58.png)

**Comment by matthewcrist** [comment]
This is fixed on production.
