### ISSUE TITLE
Add in page search to Hub doc. library page

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#911]
Add an in page search to Hub page: hub.boston.gov/details-and-forms

Add below the top commons forms but above drawers kind like this: https://www.boston.gov/pay-and-apply

**Comment by jimafisk** [comment]
Currently the doc lib isn't set up to handle filtering in this way. 

On Boston.gov, transactions are actually nodes created by the transaction content type. Then on the https://www.boston.gov/pay-and-apply page we use a List component that pulls in the Main Transactions view (/admin/structure/views/view/transactions/edit). The in-page search is an exposed filter on that view.

On the Hub, details and forms are not actually nodes, instead the are just paragraph content that has been added to the page via the Drawers component. 

A potential solution would be to create a new content type called Details and Forms and recreate the general structure of the Drawer component. Then create a view that aggregates this information. We would also need some way to tag new Details and Forms content with a corresponding Landing Page or category so we can filter the list appropriately (unless this is the only page where Details and Forms would be used and all nodes should be displayed). Then we can set this up in a similar fashion to Boston's Pay and Apply page. Note that this is a significant departure from the current structure.

@reillyzlab - Let me know if you want to discuss tradeoffs. If the search feature is critical, I will start restructuring this content. Thanks!

**Comment by BrutiAnteneh** [comment]
Closing to implement in d8.
