### ISSUE TITLE
News filler icon not showing up in news/announcements component

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#912]
News filler icon not showing up in news/announcements component

See on boston.gov homepage:

![screen shot 2017-11-01 at 10 02 00 am](https://user-images.githubusercontent.com/20731897/32278340-c2de8784-beeb-11e7-88e9-b5dd6b92807c.png)

Image to use: https://drive.google.com/open?id=0B0RwQU94BhGeUFIyUUJDWk05eG8

**Comment by jimafisk** [comment]
I believe this is because there is a value called asset_url in the variable table that needs to be pointed at https://patterns.boston.gov. I'll update the asset_url via drush when deploying this Wed (11/8/17). This value is correct on stg which appears to be working.

**Comment by jimafisk** [comment]
This is also happening for events, see related issue #865

**Comment by jimafisk** [comment]
As part of the deploy to production tonight I updated the asset_url and cleared the varnish cache. This appears to be all set now:

![default](https://user-images.githubusercontent.com/5913244/32590993-3eb8d0a8-c4eb-11e7-9a0d-c27fcf2598ce.png)

**Comment by jduffy2001** [comment]
@jimafisk I'm seeing the news filler icon on staging. looks good.

**Comment by reillyzlab** [comment]
Working; closing
