### ISSUE TITLE
Consistency of size for public notices and events filler image

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#913]
Public notices and events are being pulled into an events component together. Both have filler icons if no thumbnail image is used. However, the icons are different sizes, which becomes noticeable when two of them appear in the same component.

![770b82e4-eef8-11e6-83d5-ade369c151bb](https://user-images.githubusercontent.com/20731897/32281078-27fba162-bef4-11e7-869d-92b229b05746.png)

Can we make the images the same size?

Images to use:

Event: https://drive.google.com/open?id=0B0RwQU94BhGeTEk1SUNGNjhJMlU

Public Notices: https://drive.google.com/open?id=0B0RwQU94BhGeSnlBM3NmY0pWSlU

**Comment by jimafisk** [comment]
@carolinestj it appears we are uploading the default images consistently, so I believe a design tweak is needed here. Can you help with this?

Here are the underlying images:
- News: https://patterns.boston.gov/images/public/icons/news.svg
- Events: https://patterns.boston.gov/images/public/icons/public-notice.svg

Thanks!!

**Comment by jimafisk** [comment]
The actual SVG that Reilly referenced above: https://patterns.boston.gov/images/public/icons/calendar.svg

**Comment by jimafisk** [comment]
@reillyzlab how's this look?

![updated_calendar_icon](https://user-images.githubusercontent.com/5913244/33843328-1126c3a4-de6b-11e7-8500-bc526505e9aa.png)
