### ISSUE TITLE
Email signup forms trapping some subscribers in "pending" status

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#914]
Needs additional grooming, but writing it down so it's not lost. 

## What users want

Users would like to sign up for email alerts from the City and be added to the list after they double-opt in. 

## How it is working now

Our email system uses double opt in. When someone signs up, their address is added to Upaknee via API and they are placed into "pending" status. Upaknee sends them a confirmation email. If they miss that email for some reason, they remain in "pending". Users in "pending" status don't receive emails from the city. If a user tries to sign up again, the system doesn't send them a new email because they are already in pending. This results in users who are stuck in limbo. They continue to try and sign up, but never receive the emails they are signing up for. 

Currently we have a workaround of periodically filtering out everyone who is in pending, but that isn't an ideal user experience. 

## How it should work

If someone submits their email address and it is already in pending, they should be sent an additional confirmation email. In addition, all pending addresses should be removed on a regular basis. We need to update the widget so when someone subscribes to a newsletter, the widget searches for their ID and, if pending, triggers a reconfirm email. 

Updated API info from Upaknee can be found here:
https://drive.google.com/file/d/1DS7MlR7ayjy6lCV5ZKZ29zOkux2sqcRc/view?usp=sharing

**Comment by finneganh** [comment]
https://github.com/CityOfBoston/cob-contact/pull/27
