### ISSUE TITLE
Metrolist nodes shouldn't be showing up in site index

### ISSUE THREAD

**Issue by joshuagee** [CityOfBoston/boston.gov#917]
## What is happening

When you search specific terms on the site, information from Metrolist nodes is appearing. 

![issue1](https://user-images.githubusercontent.com/20726937/32348142-40008b38-bfe9-11e7-9a41-3deaed101e79.JPG)
Link here: https://search.boston.gov/?utf8=✓&query=5+woodworth

![issue2](https://user-images.githubusercontent.com/20726937/32348167-52c66b02-bfe9-11e7-95db-33aca869c4cc.JPG)
Link: https://www.boston.gov/5-woodworth

![issue3](https://user-images.githubusercontent.com/20726937/32348379-f0b949e2-bfe9-11e7-85f5-189cae9c0fa8.JPG)
Link: https://www.boston.gov/node

## What should happen

These pages shouldn't appear in site search. They should also be obscured from external search and not navigable via users. Potentially redirect those pages to Metrolist.

**Comment by jimafisk** [comment]
Since we're currently using the Rabbit Hole module (https://www.drupal.org/project/rabbit_hole) elsewhere on the site already, I think the best solution is to configure this for the metrolist affordable housing objects and re-export the feature.

**Comment by jimafisk** [comment]
I set Rabbit Hole to 301 redirect using this pattern: `/metrolist/affordable-properties?combine=[node:title]`

So once this is deployed, if you go to a metrolist node, for instance `/5-woodworth` you will get redirected to the table with it pre-filtered to look for this value, in this example: `/metrolist/affordable-properties?combine=5 Woodworth`

<details>
  <summary>See this in action:</summary>

  ![metrolist_redirect](https://user-images.githubusercontent.com/5913244/32460939-6024359c-c302-11e7-8757-5acf6b1ce8a8.gif)
</details>

<br />

I also removed new metrolist nodes from being "Promoted to front page" and updated the feature.

**Comment by jimafisk** [comment]
@joshuagee this should be all set on stg.

**Comment by jimafisk** [comment]
So I've spotted one that doesn't work as expected: `/15-25-hemenway-st-units`

This redirects to `/metrolist/affordable-properties?combine=15-25 Hemenway St Units`, however the property address field does not have the word units in it, so no results are returned. Using `/metrolist/affordable-properties?combine=15-25 Hemenway St` would work.

**Comment by jimafisk** [comment]
Needed to use the replacement pattern that corresponds to the field used in the view: `[node:field_mah_address]`

**Comment by jimafisk** [comment]
@joshuagee this should be working on stg now. I ran a couple of tests and it looked ok. Can you confirm? Thanks!

**Comment by joshuagee** [comment]
I think it looks good. Tough to confirm for sure since search bounces me back to the main boston.gov site. But yeah, looking good.
