### ISSUE TITLE
Need ability to add components to Hub program/initiative pages

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#918]
Looks like the component section is missing for program/initiative profiles on the Hub. You can only add to the "basic information" section:

https://hub.boston.gov/node/add/program-initiative-profile

![image](https://user-images.githubusercontent.com/7929556/32448214-4cd3f0ac-c2dc-11e7-9354-ba4b63862f51.png)

As a user, I want to have the ability to add all components to the page, the same way I can for other content types.

**Comment by jimafisk** [comment]
@jduffy2001 this is ready on stg
