### ISSUE TITLE
Get the Advanced Poll to work

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#92]
Needs grooming

**Comment by sugaroverflow** [comment]
I've recently been working a lot with advpoll and core's poll module, so I might be able to help with this! @ me when it's groomed :)

**Comment by hackajesse** [comment]
@sugaroverflow got any examples of those in action?

**Comment by sugaroverflow** [comment]
The project I worked on with polls isn't public yet, but I can find you some general Advanced Poll examples (or maybe set up a demo)!

Do you have an idea of what you need to do with polls?
