### ISSUE TITLE
Timestamp needs to update on unofficial results page

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#921]
The timestamp at the top right of the [unofficial election results page](https://www.boston.gov/departments/elections/unofficial-election-results) is updating, but not with the correct time. 

Ideally, we'd remove this from programmatically overwriting the page metadata, so that a content editor can just update the timestamp manually here on the boston.gov version of unofficial elections results page:

![image](https://user-images.githubusercontent.com/7929556/32560222-121bc63c-c477-11e7-89b6-8fc02866d435.png)

**Comment by jimafisk** [comment]
Testing steps:
1. Visit the page in question (on staging): `/departments/elections/unofficial-election-results`
2. Check the current "Last updated" date displayed in the top right of the page (just note mentally what it is so you can compare)
3. Click the "New Draft" link in the admin toolbar
4. Click the "Page Meta Data" tab in the left sidebar
5. Change the "Updated Date" using the popup calendar (or enter manually)
6. Publish and save the page.
7. Check that the "Last updated" date displayed in the upper right reflects the new date that you just set

<details>
  <summary>Here's a gif to demonstrate (click to expand)</summary>
  
![last_updated_date](https://user-images.githubusercontent.com/5913244/34387293-4e68277a-eafb-11e7-9d88-17304500dc82.gif)

</details>

**Comment by BrutiAnteneh** [comment]
The issue passed as expected.
