### ISSUE TITLE
Map component disappearing as a component option

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#924]
The map component isn't appearing as a component type in the list of components on any content type.

We need to reinstate.

**Comment by jimafisk** [comment]
After adding 'map' to `_bos_core_get_components()` in sites/all/modules/custom/bos_core/bos_core.module this builds properly with the bundles enabled in the component. 

Added via https://github.com/CityOfBoston/boston.gov/pull/937

**Comment by jimafisk** [comment]
Testing steps:
1. Go to the add form for a new Article (`/node/add/article`) and fill out the required fields with test information.
2. Click the "Components" tab in the left sidebar
3. Under "Component type" select "Map" and click the button "Add new Component"
4. Complete the form for the Map component, then save and publish the page.
5. Confirm that the page you saved actually has a map displayed.

Repeat the steps above for all content types that have a component field:
-  Landing Page (landing_page) - node
- Guide (topic_page) - node
- Department Profile (department_profile) - node
- Article (article) - node
- Post (post) - node
- Event (event) - node
- Listing Page (listing_page) - node
- Person Profile (person_profile) - node
- How-To (how_to) - node
- Place Profile (place_profile) - node
- Program Initiative Profile (program_initiative_profile) - node
- Script Page (script_page) - node
- Public Notice (public_notice) - node
- Tabbed Content Tab (tabbed_content_tab) - paragraphs_item

**Comment by BrutiAnteneh** [comment]
This issue passed as expected.
