### ISSUE TITLE
Issue with upcoming events component

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#927]
When a new upcoming events component is added to any page it is only pulling in upcoming public notices, not upcoming public notices _and_ events which is what the component should be doing.

**Comment by jimafisk** [comment]
So I'm not sure this was ever actually working exactly how we intended. Depending on the upcoming events at a given time, it can have the appearance of integrating Public Notices and Events, but in reality it shows public notices first (as long as the start date falls in the correct range) and then shows Events (same filter criteria). So if there are only two public notices in range, you will see two events also in range, but if there are many public notices in range, then it will push the events beyond the first four items that are displayed. I'm looking into a way to update the sort criteria to be closer to what we intended originally, e.g. integration between these two content types based on their date. Ideally we would share a date field between these two content types, however that would require a migration at this point.

**Comment by jimafisk** [comment]
The issue is Views doesn't provide a good way to integrate the sorting of two separate date fields.

Here are a couple of potential workarounds: https://drupal.stackexchange.com/questions/84920/how-can-i-sort-a-view-based-on-a-rewritten-field

As noted in the post we could use [Computed Field](https://www.drupal.org/project/computed_field), but it seems like it would be better to use one consistent date field across both content types. Currently Events use `field_event_dates` and Public Notices use `field_public_notice_date`. There is a field called `field_date` that already exists in the system, we could use that instead. This would require another multi-step field migration.

**Comment by jimafisk** [comment]
Per https://www.drupal.org/node/1260160
> The sort is done as part of the query. The rewrite happens after the query is done.

**Comment by jimafisk** [comment]
One potential solution is to add a query alter to the existing feature. There are details here: https://www.drupal.org/project/views/issues/2133879

**Comment by jimafisk** [comment]
This appears to be working on staging:

![working_upcoming_events](https://user-images.githubusercontent.com/5913244/33559052-97c9e37e-d8d9-11e7-9605-1c545029dc45.png)

@reillyzlab can you confirm if you get a chance? Thanks!

**Comment by reillyzlab** [comment]
Testing steps for issue 927:
Steps:
Create and publish a public notice with the date set for the same day as you test.
Create and publish an event with the date set for the same day as you test. [Note: Start time needs to be at least three hours from time of testing.]
Create a new article page.
Add in all fields to be able to save the content type. 
Add the ‘upcoming events’ component to the page. Select “upcoming_events - Upcoming Events” under “List”.
Save the page.
Verify that you can see the public notice and event that you created in the ‘upcoming events’ page.
Repeat/test on every content type.
Note: The ticket only passes if it works on every content type.

Background: We have a component called Upcoming Events that we use on the site, mainly on the homepage. This should display 4 items, a mixture of Public Notices and Events, based on whatever is the closest in terms of their date and time values. Events that have past by 3 hours or more do not display.

Problem: The component was typically only displaying Public Notices and not Events. This was happening even when there were events happening sooner than the displayed Public Notice (and also not in the past).

**Comment by BrutiAnteneh** [comment]
The issue passed as expected.
