### ISSUE TITLE
Prevent admins from being able to “Delete the account and its content” when removing user accounts

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov#929]
When manually removing users from Drupal, admins are presented with several options:

![delete_user](https://user-images.githubusercontent.com/5913244/33081884-5bca290e-cea9-11e7-88f4-d2680c0f8334.png)

We should disable the last radio button that allows you to delete the content from the system: https://drupal.stackexchange.com/questions/228683/how-can-i-disable-delete-the-account-and-its-content

**Comment by jimafisk** [comment]
Testing steps:
1. Log in to staging as a user that has permissions to manage other user accounts, typically an administrator
2. Go to the "People" section of the admin interface (`/admin/people`) in order to manage users
3. Click the "Cancel account" link all the way to the right of a specific user account (don't use the admin account) and confirm that you can't select the option "Delete the account and its content." (you can then hit "cancel" instead of "cancel account" to avoid actually deleting the user.
4. Go back to the People page (`/admin/people`) and in the leftmost column check the boxes next to a couple of user accounts (again avoid ticking the box for the admin user).
5. Under the "Operations" section at the top of the table choose "Cancel user account" from the select list and then click the "Execute" button. Again confirm that the next screen does not allow you to select the option "Delete the account and its content."

<details>
  <summary>Testing gif (click to expand)</summary>

![user_cancel](https://user-images.githubusercontent.com/5913244/34391431-88815ab8-eb13-11e7-9ab6-e7ba707215e8.gif)

</details>

**Comment by BrutiAnteneh** [comment]
The issue passed as expected.
