### ISSUE TITLE
Can't add/edit links to components on Voting in Boston page

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#931]
I've seen this bug before, but I'm not sure how @matthewcrist fixed it in the past. I can't add or edit links on the page. I'm getting this message, for example, on the transactions grid:

![image](https://user-images.githubusercontent.com/7929556/33273068-2a3d921c-d35a-11e7-9fa2-e51be14ef884.png)

When I try to add another item, I see the same issue:

![image](https://user-images.githubusercontent.com/7929556/33273095-3ffb207e-d35a-11e7-85ab-db06223371b9.png)

I tried adding a whole new transactions grid component as well, but that didn't work. For the Group of Links Grid, Groups of Links List, and mini grid components, I'm only given the option to add a document:

![image](https://user-images.githubusercontent.com/7929556/33273250-b619d8d6-d35a-11e7-88bd-e5e4b3c90efd.png)
![image](https://user-images.githubusercontent.com/7929556/33273265-c2c85986-d35a-11e7-93d6-62a9a9d3ab19.png)
![image](https://user-images.githubusercontent.com/7929556/33273280-ce80ca9c-d35a-11e7-9a8b-5f6c67b4c0a4.png)

**Comment by matthewcrist** [comment]
@jduffy2001 did you try deleting the component, saving the page, then adding again?

**Comment by jduffy2001** [comment]
Looks resolved now.

I think it stems from a permissions issue at the component level, but not 100 percent sure.
