### ISSUE TITLE
New Posts not always showing in related News and Announcements

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov#938]
Some Place Profiles using the related News & Announcements will not display new posts that were just published. Upon closer inspection we're actually using the custom `field_published_date` for sorting this list and not the actual authored date of the node. This causes a couple of things to happen:

1. Since we're using the "Listing Short" view mode in the View, which uses a short date format (e.g. Dec 13), if multiple nodes are published on the same day (even if at different times), these will appear in random order and will change on each page refresh.
2. If you publish a new Post but the date you manually set is further in the past than the currently displayed items, it will not appear in the list.

@jduffy2001 my understanding is this list should display items based on when they were initially created regardless of the event date (the date that is actually displayed publicly), is that correct?

**Comment by jduffy2001** [comment]
Yes, I think this is an example of that.

For what it's worth, I just tried to add a new "news and announcements" component to the page and that post still isn't showing up. Going to see if I can recreate this on staging.

**Comment by jduffy2001** [comment]
@jimafisk Here's another example. [In this post](https://www.boston.gov/news/immigrant-grandmothers-mural-unveiled-east-boston), "Immigrant Advancement" is tagged as a department, but it's not showing up on the [department page](https://www.boston.gov/departments/immigrant-advancement).

This post was published in December, so it should be showing up as the first item in the top left of the "News and Announcements" component.

**Comment by jduffy2001** [comment]
Another example, this time for an event:

https://www.boston.gov/calendar/l-street-brownies-new-years-day-swim

"Centers for Youth & Families" has been tagged in the departments section, but it's not automatically appearing on the department page. I had to manually add it in at the top.

**Comment by jimafisk** [comment]
@jduffy2001 the first couple of examples you mentioned [above](https://github.com/CityOfBoston/boston.gov/issues/938#issuecomment-351419314) seem to be working now. Did you change anything, or did they just start working on their own? If things generally start working after a delay, then I suspect there is some sort of caching issue going on here.

**Comment by jduffy2001** [comment]
@jimafisk Sorry Jim, I was out when you wrote your last comment and never caught up on it.

I actually have two more examples:
https://www.boston.gov/news/robotics-takes-bcyf-menino
https://www.boston.gov/news/meet-david-aka-peter-parker%C2%A0-longtime-camp-joy-participant

Those posts should be appearing on [BCYF's department page](https://www.boston.gov/departments/boston-centers-youth-families) in the "news" section as the latest items, but they're not. Do you think it's a caching issue? They were published a few days ago.

**Comment by BrutiAnteneh** [comment]
The issue passed as expected:

![image](https://user-images.githubusercontent.com/33470951/42522513-4fbffad0-8439-11e8-862b-dff081032ad7.png)
