### ISSUE TITLE
Downloads on events still create links even when nothing is attached

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#94]
On any event, a content author can add a downloadable piece of information. However, if they add a title, like "View filed agenda", but don't upload a file to be hosted on Drupal, the event's published 'Downloads' section creates a hyperlink to nowhere. 

As an event creator, I shouldn't be able to add a download, internal, or external link without a file upload or hyperlink added to the CMS, even though I may have added a Title.

Origin of the upload area on an event. Event details section in the left sidebar.
![screen shot 2016-10-19 at 2 55 12 pm](https://cloud.githubusercontent.com/assets/3886936/19533005/ff686904-960b-11e6-9924-fa8e31442faf.png)

Expanded view of an event on /events:
![screen shot 2016-10-19 at 2 56 23 pm](https://cloud.githubusercontent.com/assets/3886936/19533050/31f7b5be-960c-11e6-9959-4dea2435cc7e.png)

Page view of an event after clicking Event details. Note the section called "Resources". That link is the one that becomes a hyperlink 
![screen shot 2016-10-19 at 2 56 38 pm](https://cloud.githubusercontent.com/assets/3886936/19533051/31f9a32e-960c-11e6-8a27-e62cd864149e.png)

**Comment by reillyzlab** [comment]
Still not fixed for 'document' under downloads.

**Comment by jimafisk** [comment]
This appears to be fixed on stg:
![required_document](https://cloud.githubusercontent.com/assets/5913244/25672699/c4aae896-3002-11e7-965a-762f5de1aeb7.png)

One thing to note is that this fix will prevent new documents from being added with only a title and missing attachment, but will not automatically fix events created improperly in the past. If you try to edit such event however, it will not allow you to save the form until the issue has been addressed.
