### ISSUE TITLE
Prompt message warning users when creating/editing content

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#948]
If a user edits content in Drupal, they're able to click around on the left side of their screen without needing to save their work:
![image](https://user-images.githubusercontent.com/7929556/34160164-d22e50ec-e499-11e7-9485-faddb734995f.png)

But, if a user accidentally clicks the top of their screen, located here:
![image](https://user-images.githubusercontent.com/7929556/34160203-005310b6-e49a-11e7-8ad3-9f78140b96a5.png)

They end up losing their work if they forgot to click "save" at the bottom left hand side of their screen. I got some feedback from a content author yesterday. They asked if we could set up a prompt, warning a user that if they proceed (after clicking a link up top), they will lose any unsaved work.

**Comment by jimafisk** [comment]
Potential options:
- https://www.drupal.org/project/node_edit_protection
- https://www.drupal.org/project/saveguard
- https://www.drupal.org/project/content_lock (this is the least stable option, but the most D8 ready so I think we should start here so we don't add contrib modules to the list we need to port)

**Comment by reillyzlab** [comment]
Closing b/c won't address until D8
