### ISSUE TITLE
Extra dotted line in sidebar on Boston.gov pages

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#951]
Seeing an extra hr in the sidebar section of pages on Boston.gov:

![image](https://user-images.githubusercontent.com/7929556/34212874-aa797fc2-e56b-11e7-91b6-dc652c6cc38b.png)
![image](https://user-images.githubusercontent.com/7929556/34212907-bce22164-e56b-11e7-9972-abc4f8154446.png)
![image](https://user-images.githubusercontent.com/7929556/34213025-116dc0d0-e56c-11e7-820e-0fd12ff8030e.png)

I've seen it on article pages, how-tos, and program pages. Posts and department pages seem fine. Also, for what it's worth, I tested removing the contact information and just keeping the sidebar components, and the extra line was still there.

**Comment by jduffy2001** [comment]
Adding in some example pages:

https://www.boston.gov/departments/environment/renew-boston/how-sign-energy-audit
https://www.boston.gov/departments/fire-prevention/fire-forms-permits-applications-and-fees
https://www.boston.gov/departments/environment/conservation-commission/hearing-dates-and-filing-deadlines

**Comment by jimafisk** [comment]
The issue here is nested `.list-item` elements. Since there is no such thing as a parent selector in CSS3, we can't simply remove the dotted line from `.list-item` elements that have child `.list-item`'s - although that would be nice.

![li](https://user-images.githubusercontent.com/5913244/34265302-7078f1e4-e643-11e7-8902-4b856128e3ca.png)

We could potentially change the markup of the template `sites/all/themes/custom/boston/templates/node/node--how-to.tpl.php` so the wrapper is no longer a `.list-item`

**Comment by jimafisk** [comment]
Testing steps:
1. Visit the example pages that James identified above (make sure you're on the dev site `/departments/environment/renew-boston/how-sign-energy-audit`, `/departments/fire-prevention/fire-forms-permits-applications-and-fees`, `/departments/environment/conservation-commission/hearing-dates-and-filing-deadlines`) and confirm the second dotted line at the bottom of the right sidebar is removed.
2. Create a How-To page (`/node/add/how-to`) and add "Sidebar Info". Then save and make sure the double dashed line is not present.
3. Create an Article page (`/node/add/article`) and add "Sidebar Components." Save and check the display for a second dashed line.
4. Check the responsive behavior of the sidebar/main body content of both Articles and How-To content (Chrome and Firefox both provide a way for testing different breakpoints using their browser developer tools - I'd be happy to walk through this with you if it's helpful).

**Comment by BrutiAnteneh** [comment]
The issue passed as expected. Checked the responsive breakpoints for both How-tos and Article Pages using Chrome and Firefox browser dev tools and found no errors.
