### ISSUE TITLE
Student move in parking 2017 map isn't working

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov#957]
Student move in parking map isn't showing anything: https://www.boston.gov/news/parking-and-traffic-restrictions-during-2017-student-move. The area with the map is grey before clicking "View map" and after clicking it so you can't see any information. We build this map using the maps Drupal module.

<img width="1363" alt="screen shot 2017-12-22 at 1 01 20 pm" src="https://user-images.githubusercontent.com/12868231/34307859-4669da6e-e718-11e7-8a3a-98a624086f30.png">

**Comment by jimafisk** [comment]
This might be a browser specific issue. Are you using Firefox by chance?
<details>
<summary>Working in Chrome (click to expand)</summary>

![chrome_maps](https://user-images.githubusercontent.com/5913244/34415183-448e3b70-ebbb-11e7-8680-7826b4d2aa38.png)

</details>
<details>
<summary>Working in Internet Explorer (click to expand)</summary>

![internet_explorer_maps](https://user-images.githubusercontent.com/5913244/34415193-527fa426-ebbb-11e7-9da7-dc2e34f8bdd9.png)

</details>
<details>
<summary>Broken in FireFox (click to expand)</summary>

![firefox_maps](https://user-images.githubusercontent.com/5913244/34415201-5ea91ed0-ebbb-11e7-9ca1-6281793c40d0.png)

</details>

<br />
@paylakatel do you have easy access to Safari?

**Comment by paylakatel** [comment]
Thanks for looking into this! It works great in safari:
<img width="1429" alt="screen shot 2017-12-28 at 11 07 03 am" src="https://user-images.githubusercontent.com/12868231/34415970-47358294-ebbf-11e7-95a7-003c7f6b2f00.png">

and I was using firefox when I noticed this.

**Comment by jimafisk** [comment]
This should be all set per https://github.com/CityOfBoston/patterns/pull/208

Error: `TypeError: "map--144161" is read-only` ([Details](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Read-only?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default))

**Comment by jimafisk** [comment]
This should be all set in Firefox at this point. @paylakatel if you disagree, please reopen. Thanks!
