### ISSUE TITLE
Line height on person profile listing

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#960]
Problem: 
On a person profile card, if a name or title is too long, then the box will stretch causing a spacing gap at the bottom of the card.

This is particularly evident on a grid of people.

See example here: 
https://www.boston.gov/departments/neighborhood-services#contacts

![2017-11-01 10 24 36_preview](https://user-images.githubusercontent.com/20731897/34533661-3418bfd6-f089-11e7-884c-48e941cefb3f.jpg)

Page that is displaying accurately:
https://www.boston.gov/departments/city-council#city-council-members

![screen shot 2018-01-03 at 1 04 57 pm](https://user-images.githubusercontent.com/20731897/34533109-bbc173e0-f086-11e7-900f-9b413003bb3c.png)

Desired outcome/change requested:
On a grid of people, the cards should not stretch and create extra space after 'send an email'.

Instead, additional padding should be added above the image and below the italic 'title' text. 

Image, name, and title should always display in the middle of the gray box.

**Comment by jimafisk** [comment]
Used `align-self: flex-end` to push the contact information to the bottom of the flexbox and assigned the background color to the card container instead of the content which varies in size: https://github.com/CityOfBoston/patterns/pull/211

**Comment by jimafisk** [comment]
Adjusted PR to use a better approach (`flex-direction: column` and `flex-grow: 1`) and fixes hover behavior.

**Comment by finneganh** [comment]
<img width="1242" alt="screen shot 2018-03-30 at 12 11 18 pm" src="https://user-images.githubusercontent.com/260837/38144615-7bc2b63e-3413-11e8-8f89-b60a821b0a86.png">
