### ISSUE TITLE
CSS: Placeholder of email input misaligned

### ISSUE THREAD

**Issue by scottaohara** [CityOfBoston/boston.gov#969]
# Issue:
In both Safari 11, and FireFox (latest) on macOS High Sierra, the placeholder value for the email input, of the contact feedback form, is misaligned to the `input`.

![Safari screen shot of misaligned email input placeholder text](https://user-images.githubusercontent.com/4152514/34807828-dfb44df4-f658-11e7-9027-c247cf985fbe.jpg)

This issue does not occur in Chrome, and I have not tested on a windows machine.

**Comment by BrutiAnteneh** [comment]
Just tested **on Windows 7** and can confirm the same as above:

This is happening in **Firefox** (latest), but not in Chrome:

![image](https://user-images.githubusercontent.com/33470951/34890720-06c58b6c-f7a1-11e7-9771-2b5a51e40563.png)

**Comment by jimafisk** [comment]
Thanks for reporting @scottaohara! I believe @finneganh's fix should take care of this: https://github.com/CityOfBoston/patterns/pull/218

**Comment by scottaohara** [comment]
@jimafisk confirmed that the placeholder text is now properly aligned in Firefox and Safari per my original tests.
