### ISSUE TITLE
Error uploading files to website

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#971]
I've been trying to upload files to the website, and it's giving me an error message in Drupal:

![image](https://user-images.githubusercontent.com/7929556/34848735-dff012a4-f6ed-11e7-95b6-39fafb92b8d7.png)

The file sizes I'm uploading are below the 256 MB limit, so I'm not sure what's causing the issue. The error is also popping up when I try to upload a document through the "Linkit" option:

https://drive.google.com/file/d/189Zxj4sUhvScf6Sm91dasUQZmHn-1TQ0/view

**Comment by reillyzlab** [comment]
Closing b/c addressing on a larger level: https://github.com/CityOfBoston/boston.gov/issues/977
