### ISSUE TITLE
Accessibility: Links announce multiple times due to redundant text

### ISSUE THREAD

**Issue by scottaohara** [CityOfBoston/boston.gov#972]
# Issue:
On the home page, under common resources, the various cards/links are structured as such:
```
<a href="..." class="..." target="_blank" 
  title="Go to Search property info with Assessing Online">

  <span class="lwi-ic">
    <img src="..." alt="Search property info with Assessing Online"
  </span>

  <span class="lwi-t">
    Search property info with Assessing Online
  </span>

</a>
```
Depending on the screen reader, the above pattern can be announced up to 3 times.
e.g. 
**Safari + VoiceOver announce links like the above as:**
"Link, Search property info with Assessing Online. Go to Search property info with Assessing Online..."
**FireFox or IE11 + JAWS will announce the link as:**
"Search property info with Assessing Online, Search property info with Assessing Online, Go to Search property info with Assessing Online"

This is clearly overly verbose and a poor user experience for users relying on assistive technology to navigate the website.

## Fix:
- The `title` attribute should never be used to essentially duplicate the visible content of a link or form control.  Really, there are very few instances where the `title` should be used.  **Remove the `title` attribute from these links (and any other links where the `title` is identical/near identical to the visible text).**
- Icons, like used in these link patterns, should have an `alt=""` as these images merely serve as visual decoration to the visible text the accompany.  **Set `alt=""` to these `img` elements**

The revised link pattern should look like this when updated:
```
<a href="..." class="..." target="_blank">

  <span class="lwi-ic">
    <img src="..." alt="">
  </span>

  <span class="lwi-t">
    Search property info with Assessing Online
  </span>

</a>
```

Thanks

**Comment by BrutiAnteneh** [comment]
The issue passed as expected 

Tested:
- Safari + VoiceOver
- FireFox + JAWS 
- IE11 + JAWS
