### ISSUE TITLE
mobile: truncated filter button on search.boston.gov results page 

### ISSUE THREAD

**Issue by BrutiAnteneh** [CityOfBoston/boston.gov#976]
### **The Problem:** 
Shortened filter button is causing text and drop-down arrow to overlap on the search results page. 
URL: https://search.boston.gov/?utf8=%E2%9C%93&query=transportation

Screenshot Device Details:
OS: Android 8.1.0
Device: Google Pixel

**Portrait Screen Resolution: 360x640**

![google pixel filter button screenshot_20180117-191225](https://user-images.githubusercontent.com/33470951/35076978-eea62132-fbc8-11e7-82fa-7701856a9072.png)

**Landscape: 640x360**

![landscape 640x360 screenshot_20180117-194117](https://user-images.githubusercontent.com/33470951/35077195-e232463c-fbc9-11e7-8dad-9b850954f64a.png)

**Drop-down menu opened**:
 Shortened as well, though not a major issue:

![open filter button on search dot boston screenshot_20180117-200731](https://user-images.githubusercontent.com/33470951/35077218-fc40643c-fbc9-11e7-9a51-72bfe3977cc4.png)

### Breakpoints:

Tested different breakpoints using Chrome and Firefox browser developer tools. Both confirmed: 

Breakpoint at **839 px**

<img width="804" alt="mobile filter breakpoints breaks at 839 and below screen shot 2018-01-17 at 7 58 12 pm" src="https://user-images.githubusercontent.com/33470951/35077336-c85f7148-fbca-11e7-9509-985841340107.png">

Working at **840 px** and above

<img width="800" alt="mobile filter breakpoints working 840 and above screen shot 2018-01-17 at 7 56 23 pm" src="https://user-images.githubusercontent.com/33470951/35077273-5815a10a-fbca-11e7-9a98-f7d221842e72.png">

### **Desired Outcome:**

To display like the filter button on Events search page. 
URL: https://www.boston.gov/events:

![events filter desired outcome screenshot_20180117-203642](https://user-images.githubusercontent.com/33470951/35077289-75809010-fbca-11e7-8f6a-1f92ac7c9233.png)

**Comment by reillyzlab** [comment]
Closing because we are moving away from search.boston.gov to a search view over the next few weeks which should resolve this.
