### ISSUE TITLE
Move documents management to S3

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov#977]
File storage in our current Drupal database is too small to accommodate our needs.

We should have all of our documents go into an S3 bucket in AWS to host any files we upload.

- [x] Implement S3 bucket in AWS

- [x] Implement module to connect to S3 bucket

- [ ] Migrate files already in Drupal database to the S3 bucket
- [ ] Delete any files fro the Drupal database

- [ ] Migrate files from the old cityofboston.gov site to the S3 bucket
- [ ] Delete any files from cityofboston.gov server
- [ ] Setting up cloudfront in front of this S3 bucket

Content editor experience should remain the same.

**Comment by cob-hondo** [comment]
@reillyzlab we should add a task of setting up cloudfront in front of this S3 bucket as well.

**Comment by reillyzlab** [comment]
Testing: https://github.com/CityOfBoston/boston.gov/issues/1049

**Comment by reillyzlab** [comment]
Not implementing b/c of performance issues. Increasing db space instead. Closing this issue.
