### ISSUE TITLE
Add secondary navigation links to place profile and event content types

### ISSUE THREAD

**Issue by jduffy2001** [CityOfBoston/boston.gov#979]
We're looking to add secondary navigation to our event pages and place profile pages, including community centers, neighborhoods, cemeteries, and parks. As a reference point, our secondary nav links appear here on department pages:

![image](https://user-images.githubusercontent.com/7929556/35233995-bdfda30e-ff6d-11e7-90c4-663830eaa417.png)

These links are controlled by the "short title" fields of components. **For some reason, this field doesn't work on the event and place profile content types.** Please fix on these two pages.

**Comment by jduffy2001** [comment]
Spoke with @davidrkupton about this. He's also going to address the issue of secondary links jumping a user below the title field of a component. Looks like this:
![image](https://user-images.githubusercontent.com/7929556/40368046-d471fe84-5da8-11e8-8ba2-94663c90a356.png)

Should be something like this:
![image](https://user-images.githubusercontent.com/7929556/40368076-ee5eb4d6-5da8-11e8-8653-cdba65b06ebc.png)

The issue is being created by the fixed nav at the top of Boston.gov.

**Comment by davidrkupton** [comment]
Dev notes: The scroll issue only occurs when a link is clicked in the secondary menu when it is not "sticky" (i.e. still inline with the page content below the wavy line).  The issue is that the scroll destination is calculated and set _before_ the secondary menu becomes sticky (i.e. is relocated as a menu-bar and fixed below the main City of Boston page menu (done in an onScroll event)), causing the secondary menu to be misplaced once all the js is finished running.

**Comment by BrutiAnteneh** [comment]
## Administrator Toolbar / Short Title Bar conflict in Drupal Content Editors View and Administrator View
When the toolbar appears after sign-in, it causes the Short Title Bar to become hidden from view.
I've observed this in Place Profile content types. This is not happening on Events pages.
I have not tested other content types.

![image](https://user-images.githubusercontent.com/33470951/41927736-03c27714-7941-11e8-8244-16aa6fc5851d.png)


## Breakpoints: 

- Administrative Toolbar disappears at **1024 pixels and below** 
- Short Title Menu Bar breaks at **1026 pixels and above**
- At **1025 pixels** both work correctly: 


![image](https://user-images.githubusercontent.com/33470951/41928334-d7d0393c-7942-11e8-963b-2ebc998c62db.png)

@reillyzlab I spoke with @davidrkupton about this and he says this won't be an issue in D8, and suggested documenting this for reference.

**Comment by BrutiAnteneh** [comment]
The issue passed as expected. Testing confirmed the following two items listed on the ticket are working:
1. Secondary navigation links (short titles) have been added to place profile and event content types.
2. Secondary navigation links take the user to the top of the Title field.
