### ISSUE TITLE
Hero Image not working on How-To Pages

### ISSUE THREAD

**Issue by BrutiAnteneh** [CityOfBoston/boston.gov#981]
## The Problem
Hero Image component doesn’t cooperate with Intro image field on How-To pages, impacting the appearance of the page in two ways outlined below.
Visible on mobile phones.

## Tested On:
Desktop
Windows 7: Chrome (latest) Firefox (latest)
Mac OS X Yosemite v. 10.10.5: Chrome 10, Safari 10.5, Firefox 58.0

Mobile
OS: Android 8.1.0
Device: Google Pixel

## Screen Shots 
URL: https://edit-stg.boston.gov/how-page
For page URLs, see Table of Component and Content Type Operational Breakdown on issue #970  

### How-to Page with Intro Image uploaded:
![how-to page with intro image - screenshot-edit-stg boston gov-2018-01-09-12-19-40-894](https://user-images.githubusercontent.com/33470951/35292061-55e41f2a-003d-11e8-89ea-8a06b02a4b6b.png)

### Hero Image component added:
![how-to page with hero image added screenshot-edit-stg boston gov-2018-01-09-12-44-15-894](https://user-images.githubusercontent.com/33470951/35292076-61c3c80e-003d-11e8-9f7b-c2cf61325ac0.png)

### No uploaded Intro Image: 
When there is no intro image, the Hero Image repeats within the container instead of going to the default blue background.

![how-to page - no intro image screenshot-edit-stg boston gov-2018-01-09-13-10-15-961](https://user-images.githubusercontent.com/33470951/35292227-ddfef006-003d-11e8-9819-c82b24938cb5.png)

**Does not appear to impact other Content Types with Intro Image Fields
Content types tested:** 

- Event page
- Listing Pages Guide Pages
- Place Profile
- Post
- Program/Initiative profile
- Guide Page

**Does not appear to impact image fields on other components
Components tested:**

- 3 columns 
- Card image
- Photo 
- Quote 
- Transaction (icon field)
- Video Poster

**Comment by reillyzlab** [comment]
Hero image is only intended for landing pages in particularly. The fact that it does not work on this page is not a bug.
