### ISSUE TITLE
Ability for users to share City news pages on social media

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/boston.gov#99]
As a visitor to a Boston.gov post? any page? event?, I want to share that page on Twitter, Facebook, or via email to tell my followers or friends about it.

@sebastianebarb would you attach any comps IDEO did for this?

Comment 1: 
URL: https://www.boston.gov/news/boston-pursuing-25-mph-speed-limit
BROWSER: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
I wish I could easily share the City's news pages on my social media account

Comment 2:
URL: https://www.boston.gov/news/mayor-walsh-announces-early-voting-locations-november-8-presidential-election
BROWSER: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Why can't you share on social media things listed on here?

**Comment by sebastianebarb** [comment]
@hackajesse no such comp exits.

**Comment by sebastianebarb** [comment]
https://drive.google.com/file/d/0B0RwQU94BhGeX2NzUWdKZGFDZEk/view?usp=sharing
![event not found](https://cloud.githubusercontent.com/assets/20642299/20499054/be1c1a20-affd-11e6-9375-fe7be62a10ae.png)

**Comment by sebastianebarb** [comment]
@hackajesse talked this over with Hondo
![post](https://cloud.githubusercontent.com/assets/20642299/20537048/959e8e18-b0b9-11e6-855b-42d7353c347d.png)

https://drive.google.com/open?id=0B0RwQU94BhGeUWdGbWhNUTRUZlE

**Comment by reillyzlab** [comment]
Closing because no feedback requesting this mixed with articles reporting that this creates confusion for users who are used to just grabbing URL and sharing on their own
